### ISSUE TITLE
Filter activity by minimum amount

### ISSUE THREAD

**Issue by Sjors** [ZeusLN/zeus#1011]
### Describe the feature

I get sats streamed from my podcast which means my activity feed is filled with 0 sats keysends. Would be nice if I can filter by minimum amount to see my "normal" transactions.

**Comment by Bosch-0** [comment]
On it, good suggestion. Going to look into bundling transactions that are are similar / occurring at the same time period too as to not spam the activity menu.

**Comment by Bosch-0** [comment]
Love your pod btw Sjors!!

**Comment by kaloudis** [comment]
@Sjors this is now out in v0.7.0. Hope you give it a try.

**Comment by Sjors** [comment]
I just noticed it, nice!

I guess this won't work with keysend, since those show (?) as 0?

**Comment by kaloudis** [comment]
@Sjors that shouldn't be the case - let's fix that in v0.7.1

What backend do you use?
