### ISSUE TITLE
IPv6 host URL not correctly parsing

### ISSUE THREAD

**Issue by HaosGames** [ZeusLN/zeus#1027]
### Describe the bug

I am trying to connect to a clightning-rest interface with the following URL in the host field: 
https://[IPv6]
replacing IPv6 with the actual address and not removing the brackets. If I try the same without the brackets I get the same result. 
With this config I get an error from zeus `Error: ReactMativeBlobUtil request error: url == nullnull`

If I try the same but entering https://DOMAIN with the same IPv6 address as an AAAA entry in the domain it works as expected. This leads me to believe that there is a parsing issue here and not a connection issue. 

I am on Zeus [v0.6.5-rc3](https://github.com/ZeusLN/zeus/releases/tag/v0.6.5-rc3)

### Reproduce

Try to connect to any clightning-rest node with the actual IPv6 address surrounded by brackets and the https:// prefix as the host. 

### Zeus version

v0.6.4

### Network

Clearnet

### Device

OnePlus 6T

### Device operating system

Android 11

**Comment by kaloudis** [comment]
Are you still experiencing this issue with v0.6.6?

**Comment by HaosGames** [comment]
Yes. The issue persists

**Comment by HaosGames** [comment]
Yes, this works with brackets. Without brackets would not make much sense since it would be ambiguous if you want to specify a different port.
