### ISSUE TITLE
Missing translation labels in Help menu

### ISSUE THREAD

**Issue by pysiak** [ZeusLN/zeus#1028]
### Describe the bug

Help menu is missing translation labels for:
- Telegram Group
- Twitter (DMs open)
- GitHub Issues

I'm using Zeus v0.6.5-rc2

### Reproduce

Go to Settings -> About -> Help

### Zeus version

v0.6.4

### Network

Tor

### Device

iPhone 11

### Device operating system

iOS 15.5

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/1032
