### ISSUE TITLE
Weird behaviour of back button

### ISSUE THREAD

**Issue by tomaThomas** [ZeusLN/zeus#1038]
### Describe the bug

When viewing a channel and then pressing the back button, it is switching from the channels view to the main view in the background, only after the second back button press the channel details close (and you end up on the main screen). Tested on Android

### Reproduce

Go to channels view, click on a channel and press the back button twice

### Zeus version

v0.6.4

### Network

Clearnet

### Device

Multiple devices / manufracturers

### Device operating system

Android 9 and 12

**Comment by kaloudis** [comment]
I can't seem to recreate this one

**Comment by tomaThomas** [comment]
Strange, I have the google play store version installed (0.6.6 now), and an LND node configured. When I open the App, go to the channels tab, click on a channel, the first back button press does nothing and the second returns to the main view

**Comment by AndySchroder** [comment]
I have the same problem. Using Zeus 0.7.2. Also does it when I'm on the screen to:
1. Create a new channel.
2. Request a payment QR code display
3. Set the memo for a requested payment
4. Send a payment

**Comment by myxmaster** [comment]
I can also reproduce this on Samsung Galaxy S20+, Android 13.

It only happens if you use the Android back button though. The app back button (top left of the screen) works fine.
