### ISSUE TITLE
"Timeout waiting for bootstrap" when trying to connect over Tor

### ISSUE THREAD

**Issue by derlade** [ZeusLN/zeus#1042]
### Describe the bug

During start-up, I am currently getting the following error after ~20 s:

`Error: called Result::unwrap() on an Err value: BootStrapError("Timeout waiting for bootstrap")`

In my current setup, lnd listens on localhost:[PORT] for REST connections, and the .onion-address I am connecting to from ZeusLN is set up as a Tor hidden service, which forwards calls on the specified port to 127.0.0.1:[PORT]. 

This worked a few months ago, but stopped working seemingly at random. During start-up of lnd, a gRPC proxy is successfully started at 127.0.0.1:[PORT], but I haven't found any connection attemps in the logs. What I have found though, is the following log output from Tor in syslog: 

`Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [3 similar message(s) suppressed in last 960 seconds]`

This seems to correlate with my connection attempts from ZeusLN. Is this a Tor issue, a lnd issue or a ZeusLN issue then?

### Reproduce

Simply start the app and wait about 20 seconds.

### Zeus version

v0.6.4

### Network

Tor

### Device

iPhone 12

### Device operating system

iOS 15.5

### Log output

Error: called `Result::unwrap()` on an `Err` value: BootStrapError("Timeout waiting for bootstrap")

**Comment by kaloudis** [comment]
This is a Tor issue. v3 Onion Services are experiencing disruptions

https://status.torproject.org/

**Comment by jonathanalevi** [comment]
I’ve also had this for weeks. Following. anything we can do as a workaround in the meantime short of switching to clear web?

**Comment by kaloudis** [comment]
Not really. TailScale and ZeroTier are solid VPN-like alternatives.

We are also currently working on bringing Lightning Node Connect to React Native and Zeus.
