### ISSUE TITLE
LNURL-auth support for LNDHub accounts

### ISSUE THREAD

**Issue by reneaaron** [ZeusLN/zeus#1045]
### Describe the bug

Scanning a LNURL-auth QR-Code with an LNDHub account currently leads to an error:

`Invalid attempt to destructure non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method`, followed by another error:

`LnurlAuth not supported by your node implementation`

### Additional information

BlueWallet recently added LNURL-auth support for LNDHub accounts by using the LNDHub credentials as the signing key:

 - [Pull Request](https://github.com/BlueWallet/BlueWallet/pull/4493/files#diff-ec4c16453004f9b974f5659081ec5eafd3f4f5ae6a009fbc1bbe953a2de8b9f0)
 - [Signing key pattern](https://github.com/BlueWallet/BlueWallet/blob/6f87a73a52ba648efa3cf33202bf965432b9054a/class/wallets/lightning-custodian-wallet.js#L113)
 - [Discussion with Alby](https://github.com/getAlby/lightning-browser-extension/issues/1128)

### Reproduce

1. Add a LNDHub account to Zeus
2. Try to login using LNURL-auth (e.g. lightninglogin.live, stacker.news, etc)
3. Login fails with the error message provided above

### Zeus version

v0.6.4

### Network

Clearnet

### Device

Pixel 5

### Device operating system

Android

**Comment by kaloudis** [comment]
https://github.com/BlueWallet/LndHub/blob/481758f03a45fb7081744af08c7247f17cacb77b/controllers/api.js#L158

**Comment by kaloudis** [comment]
@Talej is grabbing this one

https://lndhub.io if you need an lndhub account. No sats required to use LNURL-auth

**Comment by kaloudis** [comment]
added here: https://github.com/ZeusLN/zeus/pull/1254

targeting v0.7.2

**Comment by kaloudis** [comment]
Added in v0.7.2
