### ISSUE TITLE
Device not supported in Play Store

### ISSUE THREAD

**Issue by darthginger** [ZeusLN/zeus#1046]
### Describe the bug

Im using Zeus perfectly fine on my Xiaomi Poco F1 with Lineageos 19 (Android 12). But sadly i have to manually install it with the apk because the store tells me "This app is not available for your device". I also can't leave an awesome 5 star review in the Play Store because of it.

### Reproduce

This app is not available for your device

### Zeus version

v0.6.0

### Network

Clearnet

### Device

Xiaomi Poco F1

### Device operating system

Android 12

### Log output

```shell
This app is not available for your device
```

**Comment by kaloudis** [comment]
This should be fixed with https://github.com/ZeusLN/zeus/pull/1047

For now, you can download the app directly from our website or from GitHub.
