### ISSUE TITLE
Handle IPv6 hosts

### ISSUE THREAD

**Issue by wbobeirne** [ZeusLN/zeus#107]
**Describe the bug**
If your `lndconnect` QR code includes an ipv6 address, it stops at the first colon. E.g.
```
lndconnect://[2604:2000...
```
would put `[2604` in the host field 

**To Reproduce**
1. Generate an lndconnect QR code with an IPv6 host
2. Scan it
3. Confirm it put in the partial address

**Comment by kaloudis** [comment]
Nice find. thanks!

**Comment by ZeusLN** [comment]
This is fixed here https://github.com/ZeusLN/zeus/pull/136 and has been added to our latest release, v0.1.1
