### ISSUE TITLE
Distinguish unexpired AMP invoices in UI

### ISSUE THREAD

**Issue by eliotcougar** [ZeusLN/zeus#1071]
### Describe the feature

The use case is like this:
I want to have several AMP invoices and allow people to pay to them repeatedly by showing the respective QRs on the device.

Right now it's hard to find them in the list of payments.
There needs to be a way to filter out and display in a separate list all active AMP invoices that have been generated and haven't expired yet, preferably with the attached memos, and the ability to quickly show the QR.
Alternatively, mark those still active AMP invoices with some icon in the list of payments.

**Comment by kaloudis** [comment]
There is an `is_amp` flag we can leverage to do this

**Comment by kaloudis** [comment]
Fixed in v0.8.2
