### ISSUE TITLE
Changing Timelock Delta does nothing using c-lightning REST

### ISSUE THREAD

**Issue by pabpas** [ZeusLN/zeus#1072]
### Describe the bug

When setting new fees for a channel, Timelock Delta has no effect on the CLN node.

### Reproduce

1. Select channel
2. Set new fees
3. Set Timelock Delta to any value different than the default (34)
4. `lightning-cli listchannels CHANNEL` reports the default value

### Zeus version

v0.6.6

### Network

Clearnet

### Device

iPhone

### Device operating system

iOS 15.6.1

### Log output

```shell
Zeus reports success updating the fees.
```

**Comment by kaloudis** [comment]
Fixed in v0.7.0
