### ISSUE TITLE
iOS: handle commas when setting channel fees

### ISSUE THREAD

**Issue by pabpas** [ZeusLN/zeus#1073]
### Describe the bug

I can't enter base fees with fractional values because my locale uses comma instead of point.

There was a commit solving this for Android and LND but I am running iOS and CLN.

### Reproduce

Set new base fee of 0,1.

### Zeus version

v0.6.6

### Network

Clearnet

### Device

iPhone

### Device operating system

iOS 15.6.1

### Log output

```shell
NaN error.
```

**Comment by kaloudis** [comment]
This is fixed in v0.7.0+, out now. Let us know if you have any issues. Thank you.
