### ISSUE TITLE
Payment Hash

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoin** [ZeusLN/zeus#1082]
With Lndhub connection, after make a payment appear *Payment Hash: [object Object]* and if you click on *Copy The Hash To Clipboard*, the app crash.

We think is this line reference
https://github.com/ZeusLN/zeus/blob/c9dd9175312f461a2ca51a5907275d597bcc7815/views/SendingLightning.tsx#L173

**Comment by SatoshiNakamotoBitcoin** [comment]
![image](https://user-images.githubusercontent.com/65907137/193141615-f8f42740-067e-4694-8a21-07ec5d1010ef.jpeg)

**Comment by kaloudis** [comment]
Fixed in https://github.com/ZeusLN/zeus/commit/6bd47db3f9903ac13cc87e82ce913152be74afb1

Will be released in v0.7.2

**Comment by kaloudis** [comment]
Fixed in v0.7.2
