### ISSUE TITLE
Full integration with SimpleX

### ISSUE THREAD

**Issue by serrq** [ZeusLN/zeus#1083]
### Describe the feature

I would like to see these two beautiful realities (each in its own field) be somehow linked together.

For example, I would like to open Zeus and have the ability to send a payment (or a request for payment) to a contact (or group) that is in SimpleX chat.

Likewise in SimpleX chat I would like to be able to click on a payment request and be catapulted into Zeus and complete the payment there.

More informations:

https://simplex.chat/

https://github.com/simplex-chat/simplex-chat

**Comment by kaloudis** [comment]
Zeus already has app linking. Should work if the invoice is prefixed with `lightning:` or an on-chain address is prefixed with `bitcoin:`
