### ISSUE TITLE
Fiat rate fails to load (backend API issue)

### ISSUE THREAD

**Issue by eliotcougar** [ZeusLN/zeus#1084]
### Describe the bug

For the past week or two I often notice that fiat rate doesn't load, displaying N/A... When that happens I tried opening the API URL 
https://pay.zeusln.app/api/rates?storeId=Fjt7gLnGpg4UeBMFccLquy3GTTEz4cHU4PZMU63zqMBo directly, getting 504 Gateway timeout error...
There needs to be a better way, with some backup third-party sources for the exchange rates, and the ability to choose the preferred source...

### Reproduce

Happens randomly...

### Zeus version

v0.6.6

### Network

Clearnet

### Device

Pixel 4XL

### Device operating system

Android 13

**Comment by kaloudis** [comment]
I think at the very least we should let people pop in their own BTCPay server to pull rates from

**Comment by kaloudis** [comment]
We now have the ability to change the exchange rate backend to Yadio, under currency settings.

We've also made some changes to make the Zeus backend more reliable
