### ISSUE TITLE
A privacy focused Lightning Network (called ZK channels or Bolt)

### ISSUE THREAD

**Issue by serrq** [ZeusLN/zeus#1088]
### Describe the feature

I care a lot about the issue of privacy and resistance to censorship both because of recent events and because we don't know (today) what kind of government we will have in the future.
So the question is, if your government became oppressive, how would you preserve your financial freedom?

A first answer to this is the ZeeKoe (zero knowledge) protocol advocated by Bolt Labs.

It is basically a Lightning Network (L2) with some variations to improve privacy.

According to its developers it can be applied to all those Bitcoin-like blockchains (bitcoin, litecoin, zcash, etc.).

More informations:

https://boltlabs.tech/zkchannels-for-bitcoin/

https://github.com/boltlabs-inc/zeekoe

**Comment by kaloudis** [comment]
Out of scope for ZEUS at the moment, but will keep our eyes peeled on any developments.
