### ISSUE TITLE
Bitcoin sub-units: bitcents and millibits

### ISSUE THREAD

**Issue by serrq** [ZeusLN/zeus#1089]
### Describe the feature

I really liked the Satoshi (sat) subunit so much that I use it in most of the apps that allow me to set up a Bitcoin subunit.

However, realistically, it is not suitable for conversion (convenient from the point of view of price readability) because it is too small unit to represent everyday expenses.

Could you implement bitcents and millibits in future updates?

**Comment by kaloudis** [comment]
I think it's too confusing to have so many different units

NACK
