### ISSUE TITLE
Onboarding process

### ISSUE THREAD

**Issue by ZeusLN** [ZeusLN/zeus#11]
App currently starts for the first time showing you an error and to go to settings

**Comment by kngako** [comment]
I think I might get some free time before the week ends. 

I'm assuming the best/quickest option would be to default to settings activity for as long as no configurations have been set?

**Comment by kngako** [comment]
Also I think the onboarding/configuration process should include or highlight security suggestions for the configuration. I just need to check out what configurations are required for `LND`

**Comment by ZeusLN** [comment]
https://github.com/ZeusLN/zeus/pull/271

**Comment by ZeusLN** [comment]
Released in v0.3.0
