### ISSUE TITLE
Improve fee limit UX when paying an invoice

### ISSUE THREAD

**Issue by otech47** [ZeusLN/zeus#1106]
Following up from https://github.com/ZeusLN/zeus/issues/1090#issuecomment-1276719535, the fix implemented in #1101  improves the UX somewhat since larger payments are more likely to go through with a 100 sat default limit vs 10 sat but there may be a more robust solution perhaps involving some of these ideas:

1. make the field completely optional, leave it blank by default, and attempt the payment with some dynamic fee limit that doesn't exceed X% of the payment amount
2. allow users to enter either a fixed sat limit OR a percentage of the payment
3. leave a default value of 100 sat limit but use fee estimation to detect whether the fee will likely exceed 100 sats, and show an indicator alerting the user they may want increase the fee limit
4. allow the user to change their default fee limit in settings
5. show a proper error message when the route fails due to a low fee limit and allow the user to try again with a higher fee

**Comment by kaloudis** [comment]
I think #1 would be ideal if the endpoint doesn't explicitly need the fee rate set. But we should also attempt to provide #5 if possible as well

**Comment by otech47** [comment]
It seems if left blank it will only consider zero-fee routes... if we take the user leaving it empty to mean "do not set a fee limit" and pass max int to LND

![Screen Shot 2022-10-18 at 10 08 15 PM](https://user-images.githubusercontent.com/4914611/196580530-7ad1e6d3-c2ea-492f-92b1-d3e08916e0a4.png)

**Comment by kaloudis** [comment]
I guess we gotta set our default fee behind the scenes when not specified. Would `10_000` be OK? Seems like max int for Golang in this situation would be a crazy `9223372036854775807` (https://stackoverflow.com/a/6878625)

**Comment by kaloudis** [comment]
`Number.MAX_SAFE_INTEGER` in JS is `9007199254740991`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by otech47** [comment]
10_000 seems reasonable yes or maybe 5% of the payment amount

**Comment by kaloudis** [comment]
Let's use this: basically what the old LND send payment was using:

If amount is 1-1,000 sats, allow a fee of up to 100%, otherwise 5% max

https://github.com/lightningnetwork/lnd/blob/7274cf40d02ca96a39c1521e79cd7d1277518fee/lnwallet/parameters.go#L31

**Comment by otech47** [comment]
@kaloudis hows this look?

![Screen Shot 2022-10-27 at 12 05 30 AM](https://user-images.githubusercontent.com/4914611/198188806-255b9051-99e1-459b-9bcb-5bfb3937dc20.png)

**Comment by kaloudis** [comment]
Love it.

Oct 27, 2022, 00:06 by ***@***.***:

**Comment by otech47** [comment]
For # 3

![Screen Shot 2022-10-27 at 10 10 59 AM](https://user-images.githubusercontent.com/4914611/198308761-c6b685bd-05f8-4dc8-a9ba-1b407b032d71.png)
![Screen Shot 2022-10-27 at 10 11 10 AM](https://user-images.githubusercontent.com/4914611/198308773-d3999b42-e753-48c0-bf3a-fd63ac5c786b.png)

**Comment by kaloudis** [comment]
Looks good, make sure you use `themeColor('error')` for that red so it works across themes

**Comment by kaloudis** [comment]
Checklist

> - [x] make the field completely optional, ~leave it blank by default~, and attempt the payment with some dynamic fee limit that doesn't exceed X% of the payment amount (X = 100% for 1-1000 sats, X=5% if >1000 sats)
> - [ ] allow users to enter either a fixed sat limit OR a percentage of the payment
> - [x] leave a default value of 100 sat limit but use fee estimation to detect whether the fee will likely exceed 100 sats, and show an indicator alerting the user they may want increase the fee limit
> - [ ] allow the user to change their default fee limit in settings
> - [x] show a proper error message when the route fails due to a low fee limit and allow the user to try again with a higher fee

**Comment by kaloudis** [comment]
All completed in v0.7.2. Thanks for the contributions @otech47 and @Ovifer13!
