### ISSUE TITLE
Flashlight button in Camera Scan

### ISSUE THREAD

**Issue by faustinoaq** [ZeusLN/zeus#1109]
### Describe the feature

This app is awesome!

I just would like to add a Flashlight button to the camera scanner in case you are paying something and the ambient light is not good.

![Screenshot_20221027-090135_Zeus](https://user-images.githubusercontent.com/3067335/198306156-95688fe3-c8bb-4698-a29b-8fedfcd217d2.jpg)

**Comment by kaloudis** [comment]
added here: https://github.com/ZeusLN/zeus/pull/1118

will be out in v0.7.0 next week

**Comment by kaloudis** [comment]
Out in v0.7.0
