### ISSUE TITLE
New invoice has incorrect expiry value

### ISSUE THREAD

**Issue by 0xtrr** [ZeusLN/zeus#1112]
### Describe the bug

When I create a new invoice for my CLN node through Zeus, the expiry field in the bolt-11 encoded string is set to a unix timestamp instead of the number of seconds. Based on [this page](https://github.com/lightning/bolts/blob/master/11-payment-encoding.md#tagged-fields), I think this is a bug in Zeus.

### Reproduce

1. Connect your Zeus app to a CLN node
2. Create a new invoice with the expiry set to e.g. 3600
3. Deode the BOLT-11 string and find the expiry field

### Zeus version

v0.6.6

### Network

Tor

### Device

Iphone 12

### Device operating system

iOS 16.0.2

**Comment by kaloudis** [comment]
@0xtrr is this in  C-Lightning-REST or Spark?

**Comment by 0xtrr** [comment]
> @0xtrr is this in C-Lightning-REST or Spark?

This is with C-Lightning-REST

**Comment by kaloudis** [comment]
Fixed in v0.7.0
