### ISSUE TITLE
FDroid URL throws 403 error

### ISSUE THREAD

**Issue by jlopp** [ZeusLN/zeus#1114]
### Describe the bug

I noticed I didn't have Zeus set up in FDroid, so I tried going to https://fdroid.zeusln.app but it throws a 403 error

### Reproduce

Visit https://fdroid.zeusln.app

### Zeus version

v0.6.6

### Network

Clearnet

### Device

Android

### Device operating system

Any

**Comment by kaloudis** [comment]
Known issue. The URL should work if loaded into the F-Droid app though. We need to see if the F-Droid server supports putting a HTML page with instructions here.

**Comment by jlopp** [comment]
Gotcha. On my phone after scanning the QR I didn't get any prompt to share it with Zeus; it just opened in my browser. Sad that F-Droid doesn't have QR scan import natively in the app...

**Comment by kaloudis** [comment]
@nicheosala it's not supposed to be accessible via the web: that URL must be inputted into F-Droid and it will work

we'll investigate to see if we can add an explainer page when it is access over the web

**Comment by dzid26** [comment]
The description here https://zeusln.com/download should be changed to Open F-droid and Manage Repository and then scan QR code.
