### ISSUE TITLE
Add Signet support

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#1115]
### Describe the feature

Zeus currently supports Testnet and Regtest. Let's add support for Signet. It should be a light lift.

**Comment by kaloudis** [comment]
Let's also look into adding Simnet and any other potential networks

**Comment by kaloudis** [comment]
Less work needed than I thought. Should probably just update the labels

https://twitter.com/openoms/status/1588628602056495105

**Comment by openoms** [comment]
what's missing still is the invoice parsing which needs a workaround for bitcoinjs.
![IMG_20221105_092559](https://user-images.githubusercontent.com/43343391/200113131-6936f328-35b6-4353-8598-5041e27fdd47.jpg)

**Comment by kaloudis** [comment]
Fix released in `v0.8.3`
