### ISSUE TITLE
Xpub import to allow drafting channel opens via PSBT

### ISSUE THREAD

**Issue by djkazic** [ZeusLN/zeus#1121]
### Describe the feature

Allow Zeus to import external accounts via xpub so you can open a channel from cold storage, join market/Samourai etc. Generate a PSBT to sign and take the signed PSBT and broadcast it.

**Comment by kaloudis** [comment]
Work has started here: https://github.com/ZeusLN/zeus/pull/726

We're targeting v0.8.0
