### ISSUE TITLE
Alternative connection URIs for nodes

### ISSUE THREAD

**Issue by pseudozach** [ZeusLN/zeus#1129]
### Describe the feature

When defining a node, it could be more convenient to be able to add multiple URIs with order preference so Zeus could use local IP:port and then tailscale and then Tor.
This should help with initial connection speed, specially when Tor network is having issues.

I understand the same thing is possible now by just adding new nodes and switching between them manually. Just checking if there is interest in such a capability.

**Comment by kaloudis** [comment]
I think this introduces too much complexity and potentially some security issues. 

NACK
