### ISSUE TITLE
I can't pay with custom amount

### ISSUE THREAD

**Issue by fefolamas** [ZeusLN/zeus#113]
I can not push the button to pay when I press "pay custom amount"
it happens to me in Samsung galaxy s8

![zeus](https://user-images.githubusercontent.com/51958893/59688847-e7c37d00-91b4-11e9-9b36-fe27936f5dc4.jpeg)

**Comment by mjlamb** [comment]
I have the same issue, the button below the "Pay Custom Amount" is completely hidden, this only occurs with Lightning invoices, normal bitcoin address payments are fine. Huawei P10
![Screenshot_20190707-101740](https://user-images.githubusercontent.com/2274034/60761662-49368780-a0a1-11e9-9521-dbe28095290e.jpg)

**Comment by ZeusLN** [comment]
This is fixed in https://github.com/ZeusLN/zeus/pull/135 which is in the latest release v0.1.1
