### ISSUE TITLE
Increasing font size on Android leads to cut off fields

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#1137]
https://twitter.com/eliotcougar/status/1597975692808888322

<img width="287" alt="Screen Shot 2022-11-30 at 10 33 54" src="https://user-images.githubusercontent.com/1878621/204840542-0c62e0b1-e89b-4e0d-8f41-e8ed535a421a.png">

**Comment by eliotcougar** [comment]
I just updated to 0.7.0. The glitch with text fields is still present... :(

**Comment by kaloudis** [comment]
We don't have a fix yet.

**Comment by eliotcougar** [comment]
Just updated to 0.8.0... I'm glad to report that text in the input fields now looks good when the font size is set to large...
The issue can be closed...
