### ISSUE TITLE
Can't pay on-chain by scanning BTCPayserver QR

### ISSUE THREAD

**Issue by ILayZ** [ZeusLN/zeus#114]
**Describe the bug**
Can't pay BTCPayserver QR format:
**bitcoin:[btc_addr]?amount=[amt]**

**To Reproduce**
1. Create BTC on-chain invoice in your BTCPayserver App
2. Try to pay in Zeus for Android by scan QR code 
3. See error

**Expected behavior**
Should decode BTC_ADDR and amount and show user to confirm

**Screenshots**
![image](https://user-images.githubusercontent.com/23453629/59750094-e9f60c00-9286-11e9-84dc-d0671c1dde38.png)
![image](https://user-images.githubusercontent.com/23453629/59750056-df3b7700-9286-11e9-9d62-f81ca3a031ad.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi 5 Plus
 - OS: Android 7.1
 - Zeus Version v0.1.0

**Comment by ZeusLN** [comment]
This has been fixed here https://github.com/ZeusLN/zeus/pull/138 and added to the latest release, v0.1.1
