### ISSUE TITLE
LNBits: received payments aren't displayed in Activity view

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#1145]

**Comment by kaloudis** [comment]
Can't seem to recreate with lndhub.io

**Comment by kaloudis** [comment]
This appears to be an LNBits specific issue

**Comment by kaloudis** [comment]
Appears that LN.tips uses LNbits' backend. Lot of reports from users on this issue.

**Comment by kaloudis** [comment]
Looks like the `/getuserinvoices` endpoint on LNbits can't handle the `limit` url param. We currently have it set as `/getuserinvoices?limit=200`

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/1333

**Comment by MrRomanJohn** [comment]
Steps to recreate this issue:
Note: For this instance we will use a wallet from 
https://legend.lnbits.com/wallet?usr=0c50f4b76d9e42a7971db69dcf77dfb1&wal=1f926b996ad54670a4950513176260cf


Step 1: Open the wallet from the above link or set up an LNbits wallet on umbrel or any other platform
Step 2: under extensions, enable LNDHUB
Step 3: using the LNDHUB extension export Admin Wallet to a Zeus iOS 
Step 4: send couple sats to the wallet by generating an LNinvoice on Zeus
Step. 5: Send couple sats from Zeus to another wallet.
[Repeat step 4 and 5 upto 3 times if necessary]

You will now see that under transaction history in Zeus it will only show spent transactions not received transactions.

**Comment by MrRomanJohn** [comment]
oh if im not wrong looks like this issue has been fixed and merged. oh well haha

**Comment by kaloudis** [comment]
Fixed in v0.7.3, out now.
