### ISSUE TITLE
Upgrade to react-native 0.60

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#116]
https://facebook.github.io/react-native/blog/2019/07/03/version-60

**Comment by kaloudis** [comment]
One of the most ridiculous upgrades I've ever experienced

https://github.com/ZeusLN/zeus/pull/222

**Comment by kaloudis** [comment]
Investigate deprecated UIWebView for iOS https://medium.com/@NumberShapes/uiwebview-app-store-submission-kickback-issue-bb07d77a902

**Comment by ZeusLN** [comment]
This is live in v0.2.1
