### ISSUE TITLE
LNC connect, spaces at end of pairing phrase auto-delete

### ISSUE THREAD

**Issue by orbitalturtle** [ZeusLN/zeus#1181]
### Describe the bug

I encountered a funny UI thing when using the LND (LNC) "node interface." When I enter the pairing phrase in the text box, it won't let me type a space at the end. So say I type "elbow" it won't let me add a space before entering the next word.

Got it working fine by typing out all the pairing words without spaces and then going back and adding the spaces last. It just seems to delete spaces when they're at the _end_.

Btw, awesome new feature, psyched to use it :)

### Reproduce

Think I described this above.

### Zeus version

v0.7.0

### Node interface

LND (Lightning Node Connect)

### Network

Clearnet

### Device

Google Pixel 7

### Device operating system

Android 13

**Comment by kaloudis** [comment]
good catch. easy fix.

I've just been using the QR scanner so I missed this.

**Comment by kaloudis** [comment]
@orbitalturtle this is fixed in v0.7.0-beta1
