### ISSUE TITLE
"unmarshal v2 field data extends past end of buffer"

### ISSUE THREAD

**Issue by HamishMacEwan** [ZeusLN/zeus#122]
After selecting "scan lndconnect config" & scanning (and that little port with the scanning line is awful for the large QR codes lndconnect seems to require) a QR code the error above was reported.

![unmarshal v2 field data extends past end of buffer Screenshot_20190912_174230_com zeusln zeus](https://user-images.githubusercontent.com/388061/64764610-884bf200-d596-11e9-8536-eae1da1f38ee.jpg)

Once this occurs other setting options (host/port/macaroon) don't seem to reset the problem.

**Comment by kaloudis** [comment]
I think this is from an invalid macaroon
