### ISSUE TITLE
LNURL Withdraw invoice generation fails because of rounding amount

### ISSUE THREAD

**Issue by Siimone** [ZeusLN/zeus#1221]
### Describe the bug

Zeus fails to generate the invoice correctly during LNURL WITHDRAW flow when amount  is not divisible by 1000.
Amounts like `1111 msats` or `1234 sats` don't work, for example when min sendable is equal to max sendable.

I think that the error is inside Receive component ([link](https://github.com/ZeusLN/zeus/blob/030167f2ce39d9ed7508b1ab2d8f238b78b1525c/views/Receive.tsx#L89))

### Reproduce

You can test with this playground: https://lnurl-toolbox.degreesofzero.com/.
Just create an LNURL-Withdraw of `1111 msat` and proceed.

### Zeus version

v0.7.0

### Node interface

Multiple (specified in comments)

### Network

Clearnet

### Device

Android

### Device operating system

Android 12

**Comment by kaloudis** [comment]
@Siimone what interface are you using for this?

**Comment by Siimone** [comment]
> @Siimone what interface are you using for this?

Sorry forgot to mention. LND!

**Comment by kaloudis** [comment]
@Siimone I don't think I'm quite able to recreate. What error do you get?

**Comment by kaloudis** [comment]
ah, disregard. I can recreate it now

**Comment by kaloudis** [comment]
Easy fix here: https://github.com/ZeusLN/zeus/pull/1222/files

We'll put this out in v0.7.1

**Comment by kaloudis** [comment]
This is fixed in v0.7.1, which is out now. Let us know if you have any issues. Thank you.
