### ISSUE TITLE
Invisible UTXOs in Select UTXOs screen

### ISSUE THREAD

**Issue by 1ma** [ZeusLN/zeus#1226]
### Describe the bug

I just updated to 0.7.0 and noticed that the UTXOs disappeared from the Select UTXOs screen when making an on-chain payment. There should be 3 UTXOs in this example (the Coins screen displays them correctly). They can still be pressed but just aren't displayed. Quite annoying.

![photo_2022-12-24_20-39-19](https://user-images.githubusercontent.com/1456708/209452855-ffdb3171-6149-4bca-81e6-5da2aa0ce04f.jpg)

### Reproduce

Have a few UTXOs on your node and try to make an on-chain payment using coin control.

### Zeus version

v0.7.0

### Node interface

Core Lightning (c-lightning-REST)

### Network

WireGuard

### Device

Pixel 4a

### Device operating system

Android 13

**Comment by kaloudis** [comment]
Thanks for the report. Fixed in https://github.com/ZeusLN/zeus/pull/1227

Will push this out in v0.7.1 in the next week or so.

**Comment by kaloudis** [comment]
This is fixed in v0.7.1, which is out now. Let us know if you have any issues. Thank you.

**Comment by trijenhout** [comment]
i am testing the coin control in the v0.7.1. i can select utxo now, but zeus is not using the selected utxo's.  selecting 3 utxo's total of +/-1300 sats send out 500 sats. zeus not using selected utxo....

**Comment by trijenhout** [comment]
tested today with bigger utxo's. works ok. 
 Thanks for the work.

**Comment by kaloudis** [comment]
Cheers.
