### ISSUE TITLE
"Error Scanned QR code was not a valid Bitcoin address or Lightning Invoice"

### ISSUE THREAD

**Issue by HamishMacEwan** [ZeusLN/zeus#123]
![Zeus QR Fail Capture](https://user-images.githubusercontent.com/388061/64823711-46f62980-d60c-11e9-98ec-54aafa996a40.JPG)
![QR code not a valid Screenshot_20190913_094231_com zeusln zeus](https://user-images.githubusercontent.com/388061/64823709-465d9300-d60c-11e9-9f61-1b3c21a95fc9.jpg)

This QR code was successfully interpreted and paid by lntxbot.

**Comment by ZeusLN** [comment]
Looks like this is an all-caps issue. This can be easily remedied. I will do my best to get this into v0.1.1. Thanks for the report @HamishMacEwan

**Comment by ZeusLN** [comment]
This should be fixed with the following changes to the QR scanner:

https://github.com/ZeusLN/zeus/pull/126
https://github.com/ZeusLN/zeus/pull/120

Both changes are now available in v0.1.1
