### ISSUE TITLE
Bring zeus@0.1 to f-droid

### ISSUE THREAD

**Issue by chpio** [ZeusLN/zeus#125]
**Describe the bug**
* Current zeus version is v0.1.
* The latest version on [F-Droid is v0.0.8](https://f-droid.org/en/packages/com.zeusln.zeus/).

**Expected behavior**
The latest version should be released on F-Droid.

**Comment by chpio** [comment]
There seem to be a commit to update zeus on f-droid: https://gitlab.com/fdroid/fdroiddata/commit/32ba3c0ba52c8d09f39dfa0c8ff8e034b812ec83

**Comment by kaloudis** [comment]
Hey @chpio, thanks for opening the issue. I'll try to explain.

We need this change to be made to our F-Droid config: https://gitlab.com/fdroid/fdroiddata/merge_requests/4716/diffs#cfb6f1b11aaaa01cc4ceaee3c0e20dfb89b00c1d_66_75

```init:
      - npm install
      **- npm run patch-android-release**```

Unfortunately the camera library is problematic and won't build without this patch file applied to it. I tried explaining but they closed the PR on me.

**Comment by kaloudis** [comment]
@chpio new PR submitted: https://gitlab.com/fdroid/fdroiddata/merge_requests/5604

Please upvote and/or comment if you have a Gitlab account

**Comment by chpio** [comment]
> Build succeeded 

https://f-droid.org/wiki/page/com.zeusln.zeus/lastbuild_10

**Comment by chpio** [comment]
version 0.1 got released

https://f-droid.org/en/packages/com.zeusln.zeus/

**Comment by licaon-kter** [comment]
FYI  https://gitlab.com/fdroid/fdroiddata/-/commit/52fc08cb4c4b2e8ea1f016daa650b4a9aa710473
