### ISSUE TITLE
CLN-REST: Channels are missing from channels list

### ISSUE THREAD

**Issue by sha-265** [ZeusLN/zeus#1253]
### Describe the bug

When opening the channels list view, the list is empty even when there are online (and offilne) channel in the connected, via CLN-REST, node. I.e:
![image](https://user-images.githubusercontent.com/4103710/210561133-bdc9a566-4209-4eee-bc9c-c40f8f2c21e5.png)

### Reproduce

1. Connect Zeus to CLN node via CLN-REST.
2. Make sure there are online/offline channels.
3. Open the channels list view, and see if channels exists or not.

### Zeus version

v0.7.1

### Node interface

Core Lightning (c-lightning-REST)

### Network

Clearnet

### Device

Pixel 4a

### Device operating system

Android 13

**Comment by kaloudis** [comment]
I cannot recreate. What CLN version and C-Lightning-REST versions are you using?

**Comment by sha-265** [comment]
@kaloudis CLN v0.12.1, and CLN-REST v0.9.0

**Comment by kaloudis** [comment]
Fixed in v0.7.3, out now.

**Comment by sha-265** [comment]
It's probably unrelated, but now when I'm refreshing the channels view, the channels are disappearing and reappearing when refreshing few times again.

![image](https://user-images.githubusercontent.com/4103710/224009800-227408fe-d8a8-45ca-8fb4-d1d9137f5f3f.png)

**Comment by sha-265** [comment]
yes, we should probably open a new issue.

**Comment by nixbitcoin** [comment]
I'm getting exactly this issue on Zeus 0.7.5. Seems to have started with the fix in 0.7.3.

**Comment by nixbitcoin** [comment]
> I'm getting exactly this issue on Zeus 0.7.5. Seems to have started with the fix in 0.7.3.

https://github.com/fort-nix/nix-bitcoin/pull/599 fixes this.
