### ISSUE TITLE
Need a lightning tab and select it by default if you import a Lightning node

### ISSUE THREAD

**Issue by rolznz** [ZeusLN/zeus#1257]
### Describe the feature

I imported my Alby wallet into Zeus, and it took me back to the home page. I was confused, because it still said $0.

Finally I realized I was on the onchain bitcoin tab, and I had to click the accounts button on the bottom left, but there is not really any "lightning dashboard". If I reopen the app it's back to onchain bitcoin and $0.

It would be great for your home page to be based on what account you have, and for lightning show your history (received/sent payments) on there.

**Comment by kaloudis** [comment]
If you go to Display settings, you can choose which view to make your default view. The first view you're referring to is for quickly sending / creating invoices. It is not an on-chain dashboard

to see your activity swipe up on the balance pane (the left tab). there is a little arrow you can swipe or tap on.
