### ISSUE TITLE
Routing: fees collected show up in multiples sometimes

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#1260]
If you tap one of the time period selections (D - 1W - 1M - 3M -  6M - 1Y) rapidly, you'll trigger multiple calls that will result in a multiple of the sats collected for that time period

h/t HappyBear for the bug report on Telegram

**Comment by Talej** [comment]
https://github.com/ZeusLN/zeus/pull/1281

**Comment by kaloudis** [comment]
Fixed in v0.7.2
