### ISSUE TITLE
Decimal symbol shown multiple times on "Bitcoin" tab

### ISSUE THREAD

**Issue by yanascz** [ZeusLN/zeus#1271]
### Describe the bug

When inputing sats on the "Bitcoin" tab, tapping the decimal symbol multiple times leads to buggy behaviour:
![Screenshot 2023-01-29 at 10 38 59](https://user-images.githubusercontent.com/37251117/215319049-2be57104-1569-41c5-8d72-72178e188edf.png)

### Reproduce

Just tap the decimal symbol multiple times.

### Zeus version

v0.7.1

### Node interface

LND (REST)

### Network

Clearnet

### Device

iPhone 13

### Device operating system

iOS 16.2

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/1277

**Comment by kaloudis** [comment]
Fixed in v0.7.2
