### ISSUE TITLE
Unexpected behaviour of the back button on the Node Info screen

### ISSUE THREAD

**Issue by yanascz** [ZeusLN/zeus#1272]
### Describe the bug

Tapping the back button on the Node Info screen takes me back to the main page instead of expected(?) Settings screen.

### Reproduce

1. From the main screen, tap the Settings icon.
2. Tap Node Info.
3. Tap the back button.

### Zeus version

v0.7.1

### Node interface

LND (REST)

### Network

Clearnet

### Device

iPhone 13

### Device operating system

iOS 16.2

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/1276/files

**Comment by kaloudis** [comment]
Fixed in v0.7.2
