### ISSUE TITLE
Broken UI on the Edit network fee screen

### ISSUE THREAD

**Issue by yanascz** [ZeusLN/zeus#1273]
### Describe the bug

1. Text base line of labels and amounts is different.
2. Custom fee input box has incorrect size.

![Screenshot 2023-01-29 at 11 13 07](https://user-images.githubusercontent.com/37251117/215319640-fde45ae8-29c6-44d3-b697-e4063b1c6e82.png)

### Reproduce

1. Tap the Channels tab.
2. Tap the + button to open a channel.
3. Tap the Satoshis per byte input.

### Zeus version

v0.7.1

### Node interface

LND (REST)

### Network

Clearnet

### Device

iPhone 13

### Device operating system

iOS 16.2

**Comment by kaloudis** [comment]
Was able to recreate on iPhone X. Will try to get this fixed up for v0.7.2

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/1275

**Comment by kaloudis** [comment]
Fixed in v0.7.2
