### ISSUE TITLE
Receive on-chain button leads to create invoice screen 

### ISSUE THREAD

**Issue by yanascz** [ZeusLN/zeus#1274]
### Describe the bug

I can understand described behaviour on LN layer but not on the base layer. As a user, I'd expect the above action to generate a new on-chain address.

In addition, when I generate an invoice this way and accidentally close the screen with QR code, the on-chain address is no longer accessible from nowhere.

### Reproduce

1. Tap the On-chain box.
2. Tap the Receive button.

### Zeus version

v0.7.1

### Node interface

LND (REST)

### Network

Clearnet

### Device

iPhone 13

### Device operating system

iOS 16.2

**Comment by kaloudis** [comment]
One of the challenges here is with LNDHub: detecting whether or not the backend supports on-chain receiving or not.

LNBits and LNBank do not support it, whereas vanilla LNDHub does.

**Comment by kaloudis** [comment]
@myxmaster one thing to consider here is we can only track addresses generated in Zeus. if you're using a second interface like CLI or a web UI, you can easily have an incomplete picture of your addresses

**Comment by kaloudis** [comment]
@myxmaster let's close this one out and take discussion of on-chain address history to https://github.com/ZeusLN/zeus/issues/1930 - I have a discovery
