### ISSUE TITLE
Invoice details are not displayed if clicked on it in Activity view

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1290]
### Describe the bug

When you click on items in the Activity view, usually details are displayed. This doesn't work for (paid or unpaid) invoices though.

### Reproduce

-

### Zeus version

v0.7.1

### Node interface

LND (REST)

### Network

Tor

### Device

Samsung Galaxy S20+

### Device operating system

Android 13 (Kernel 4.19)

**Comment by kaloudis** [comment]
Which details aren't displayed?

**Comment by kaloudis** [comment]
@myxmaster can you try v0.7.2-beta2?

**Comment by myxmaster** [comment]
Did that, and it worked, BUT I just found out it has nothing to do with that :D It doesn't work when I switch to German language! Spanish works, France doesn't. Didn't check more.

**Comment by kaloudis** [comment]
Fascinating. We need to figure out what's causing the problems there. do Transactions and Payments load up without issue when on those languages?

**Comment by myxmaster** [comment]
yes, for (lightning and on-chain) transactions the details are displayed correctly when i click on them.

but i also noticed that for invoices, instead of german translations it only says "Invoice". so maybe those 2 problems are somehow connected?

![invoice](https://user-images.githubusercontent.com/77545287/216143062-e9111590-a19d-4444-bef6-7ca57caeb97d.PNG)
