### ISSUE TITLE
Replace MD5 with SHA256 in build.sh & README.md

### ISSUE THREAD

**Issue by emanuelb** [ZeusLN/zeus#1297]
MD5 algorithm is old and not recommended to use due to issues: https://en.wikipedia.org/wiki/MD5#Security

MD5 is used in:
https://github.com/ZeusLN/zeus/blob/a1828c8c3fad9d11364723fedab59dc62ccd1d30/build.sh#L12
https://github.com/ZeusLN/zeus/blob/a1828c8c3fad9d11364723fedab59dc62ccd1d30/build.sh#L18

Suggestion is to use:
1. other more secure algo like sha256 with sha256sum or blake2/blake3 with b2sum/b3sum commands, using sha256 makes sense as that what used in signed manifest files attached as asset to github releases such as: https://github.com/ZeusLN/zeus/releases/download/v0.7.1/manifest-v0.7.1.txt
2. rephrase "You can compare MD5s with the ones provided on" as MD5 hashes are not provided there, there SHA256 hashes in the signed manifest in assets (also in link named "Signed Manifest") 
https://github.com/ZeusLN/zeus/blob/cfe0f8494f278c8208a18c6f1c27cb773ca39abb/README.md#L134

**Comment by kaloudis** [comment]
Done here: Done here

**Comment by kaloudis** [comment]
Fixed in v0.7.3, out now.
