### ISSUE TITLE
Add support for scanning QR codes with Settings configs

### ISSUE THREAD

**Issue by ZeusLN** [ZeusLN/zeus#13]
Let's support getting connected to a BTCPay instance by scanning its credential QR code and adding similar support to https://github.com/ZeusLN/lnd-hex-macaroon-generator

**Comment by ZeusLN** [comment]
BTCPay support: https://github.com/ZeusLN/zeus/pull/14

**Comment by kaloudis** [comment]
https://github.com/LN-Zap/lndconnect

**Comment by openoms** [comment]
Adding an option to scan a macaroon as QR code would be a great addition. https://github.com/rootzoll/raspiblitz/issues/337#issuecomment-465992240

**Comment by ZeusLN** [comment]
https://github.com/rootzoll/raspiblitz/pull/390

**Comment by ZeusLN** [comment]
https://github.com/rootzoll/raspiblitz/issues/337
