### ISSUE TITLE
Always show all units when user can input an amount

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1304]
### Describe the feature

For example in the view: Balance View -> Lightning or Bitcoin -> Receive
or when you scan a LNURLp QR
etc.

**How it is now:**
If you picked a FIAT currency in the settings, and the amount input is in FIAT mode, the amount is calculated live in sats and BTC and also the rate (BTC/FIAT) is displayed below the input. It only does this for FIAT mode though. When the input is in sats (or BTC) mode, only the BTC (or sats) amount is calculated - no FIAT amount is calculacted, no rate is displayed.

**How it should be:**
I think it would be good, if all other units (and the rate) are always displayed below the input, no matter if you are in FIAT, sats or BTC mode.

(FIAT amount and the rate (BTC/FIAT) would obviously only be calculated/displayed if enabled in the settings.)

![3](https://user-images.githubusercontent.com/77545287/216850646-65826b67-849f-4b6e-a49f-09c9a2f8d84f.jpg)
![1](https://user-images.githubusercontent.com/77545287/216850640-222cf979-0025-4490-8495-578d7e076e25.jpg)
![2](https://user-images.githubusercontent.com/77545287/216850645-e1b78ee0-e3cf-4045-bf3e-8e619aa1219c.jpg)

**Comment by kaloudis** [comment]
Added in v0.7.4

**Comment by myxmaster** [comment]
Do you mean v0.7.5? I can't see it in v0.7.4.
(e.g. here: Balance View -> Lightning or Bitcoin -> Receive)

**Comment by kaloudis** [comment]
You're right, it'll be patched in v0.7.5

https://github.com/ZeusLN/zeus/pull/1400

**Comment by myxmaster** [comment]
Found another one. At least I think the FIAT amount should also be displayed when an invoice was scanned, so it doesn't only show amount in sats.

Here I'm not sure: Activity -> Details of a payment
Payments in the past calculated with current rates... But maybe it would still be helpful like this:
10,000 sats
now: 2,55 €
