### ISSUE TITLE
Investigate why we can't load payments from certain Nostr clients

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#1307]
- Amethyst (Android)

**Comment by greenart7c3** [comment]
For amethyst it was the wrong intent with lightning:// instead of lightning: and it's fixed on the next update

**Comment by kaloudis** [comment]
@serrq what backend are you using?

**Comment by kaloudis** [comment]
@serrq what kind of node or account are you using?

**Comment by kaloudis** [comment]
Amethyst fixed: https://iris.to/post/note13frcnr7l5qylfkxag7t8jhk49fm84ndmnzau5x79jqh3v0wfusaskhmkql

serrq's issue sounds like the login process is not happening for LNDHub accounts on hotlink. We can look into that.

**Comment by kaloudis** [comment]
I think this is generally resolved. We have one lndhub race condition in v0.8.0
