### ISSUE TITLE
Square POS: Tell me, what is it?

### ISSUE THREAD

**Issue by AndySchroder** [ZeusLN/zeus#1311]
### Describe the feature

In version 0.7.2, there is a new Square POS feature listed in the release notes. I have no idea what this is supposed to do and I can't find it anywhere in the app. Is this a hidden option or what?

**Comment by kaloudis** [comment]
Here's the first draft of our POS docs: https://deploy-preview-15--zeus-docs.netlify.app/category/using-the-zeus-point-of-sale/

**Comment by AndySchroder** [comment]
That helps a lot. It looks like this feature is a way to auto-populate an invoice amount from data fetched from an existing accounting system (that is part of the Square POS). Basically, I think it's a way to keep the "cashier" from having to double input the order if they already use the Square POS and had already put the order in there. The document linked above explains a lot how to use the feature, but it's not clear until reading it all what the purpose of the feature actually is. I'd add  simple high level statement on the first page explaining this, it would go a long way!

**Comment by kaloudis** [comment]
new overview page: https://docs.zeusln.app/pos/overview
