### ISSUE TITLE
Add setting to include hop hints by default

### ISSUE THREAD

**Issue by niteshbalusu11** [ZeusLN/zeus#1315]
### Describe the feature

Add a setting to add hop hints to an invoice by default. I always use zeus that is connected to a node which has a single private channel to my routing node. I always have to make sure I check the route hints button when creating an invoice else payments fail. It’ll be nice to have an option to always add them if enabled in settings.

**Comment by kaloudis** [comment]
@Ovifer13 this could be good to add to payment settings as well

**Comment by kaloudis** [comment]
Dupe of https://github.com/ZeusLN/zeus/issues/1149

Coming in v0.7.4
