### ISSUE TITLE
show transaction memos in the transaction list

### ISSUE THREAD

**Issue by AndySchroder** [ZeusLN/zeus#1322]
### Describe the feature

https://github.com/ZeusLN/zeus/pull/1146 adds the memo to the transaction details when you press on a transaction. It would be very useful to also display the first X (where X varies based on the screen size) characters of the transaction memo in the transaction list so that you don't have to keep pressing on different transactions to try and figure out what they all were for. There seems to be plenty of blank space on each line of the transaction list, so I think it should fit.

**Comment by kaloudis** [comment]
Added in v0.7.4
