### ISSUE TITLE
"Channels" filter in transaction/activity list doesn't seem to do anything that makes sense

### ISSUE THREAD

**Issue by AndySchroder** [ZeusLN/zeus#1325]
### Describe the bug

"Channels" filter in transaction/activity list doesn't seem to do anything that makes sense

### Reproduce

1. Open ZEUS
2. Press on the Parthenon tab in the lower left
3. swipe up
4. Press the filter/funnel icon in the upper right
5. Unselect "Lightning payments", "On-chain payments", "Sent", and "Received".
6. Leave "Channels" selected
7. Press the X in the upper left to go back to the transaction list
8. Channels don't show up in the transaction/activity list. All I see is one 0 sat transaction and I don't know what that transaction was related to. What is this feature supposed to show? I assume it is supposed to show all opening and closing channel transactions, but I'm not really sure.
9. Re-try with "Sent" and "Received" selected and it does the same thing.

### Zeus version

v0.7.2

### Node interface

LND (REST)

### Network

Clearnet

### Device

Android

### Device operating system

Lineage OS

**Comment by kaloudis** [comment]
Channel transactions used to show up as 0 amt on-chain txs in LND but I think that has changed with anchor inputs

**Comment by kaloudis** [comment]
Removed in v0.7.4
