### ISSUE TITLE
Crash on open when LNC node selected as default.

### ISSUE THREAD

**Issue by dadofsambonzuki** [ZeusLN/zeus#1336]
### Describe the bug

Been doing a lot of zapping on nostr and have noticed that Zeus crashes on start-up if an LNC connected node is selected.

If Zeus is already unlocked, it does not crash.

If Alby is selected as my node then Zeus starts fine from a cold start.

### Reproduce

As per description.

### Zeus version

v0.7.3

### Node interface

Multiple (specified in comments)

### Network

Clearnet

### Device

Pixel 5a

### Device operating system

Android 13

**Comment by myxmaster** [comment]
probably a duplicate of this: https://github.com/ZeusLN/zeus/issues/1278

**Comment by kaloudis** [comment]
@myxmaster I'm not convinced it's quite the same issue. Shouldn't be having the init issue with LND REST but we'll find out. Fix is linked above.

**Comment by dadofsambonzuki** [comment]
Confirmed fixed in latest rc.

This is why open source will rule the world. 🤙
