### ISSUE TITLE
Fee Limit percentage not working with decimal number

### ISSUE THREAD

**Issue by LukasVinc** [ZeusLN/zeus#1339]
Plattform: iOS
Version: Zeus v0.7.2
If I set may Default Fee Limit to a percentage like 1,35 % it is not working and i get an error that a route cannot be found.
When I try afterwards wir a Default fee rate in sats, the fee rate percentage is lower than what i set the limit to.
Maybe the problem does not occur with  a dot (.) instead of a coma (,), but the iOS default number key pad only lets me use a comma.
When I set the fee rate to 2 % it works flawlessly.

**Comment by kaloudis** [comment]
We've seen this issue before on other fields. We'll get this fixed up for you in the v0.7.3 general release

**Comment by kaloudis** [comment]
Fixed in v0.7.3, out now.
