### ISSUE TITLE
No longer seeing received transactions (c-lightning REST)

### ISSUE THREAD

**Issue by Sjors** [ZeusLN/zeus#1348]
### Describe the bug

Since a few weeks I'm only seeing spends in the transaction list, not received.

I'm at a little over 11K received payments, so maybe that's part of the problem :-)

### Reproduce

Open app, go to list of payments, see only spends.

### Zeus version

v0.7.2

### Node interface

Core Lightning (c-lightning-REST)

### Network

Clearnet

### Device

Pixel 7

### Device operating system

GrapheneOS

### Log output

```shell
Not sure where to find relevant logs...
```

**Comment by kaloudis** [comment]
What version of c-lightning-REST?

**Comment by Sjors** [comment]
I updated it from v0.9.0 to v0.10.1 today, but that didn't fix it.

**Comment by Sjors** [comment]
At other times I get an infinite (? at least a few minutes) spinner on the transactions screen.

**Comment by kaloudis** [comment]
Filters are applied client side

**Comment by Sjors** [comment]
Did you try with >11K transactions? I updated c-lightning and c-lightning-REST yesterday and still only see sent transactions.

**Comment by kaloudis** [comment]
@Sjors could you test this in the newly released v0.7.6?

**Comment by Sjors** [comment]
No change. I still only see sent transactions.

**Comment by kaloudis** [comment]
@Sjors are you still having this issue with the new CLNRest interface?

**Comment by Sjors** [comment]
Nope, CLNRest works like a charm.
