### ISSUE TITLE
Copied on-chain addresses should not begin with "bitcoin:"

### ISSUE THREAD

**Issue by NateNate60** [ZeusLN/zeus#1359]
### Describe the bug

When copying Bitcoin addresses from the "request payment" flow, the copied address beings with "`bitcoin:`". This is not canonically part of a Bitcoin address and therefore is not compliant with [BIP 173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) and [BIP 13](https://github.com/bitcoin/bips/blob/master/bip-0013.mediawikiZ). Indeed, most Bitcoin wallets will actually reject such an address as invalid, requiring the user to paste the address somewhere else first and manually delete the "`bitcoin:`" prefix.

Additionally, the copied address for P2WPKH (Bech32 native Segwit addresses) is all capitalised. This is unusual and most other implementations of this address format use all-lowercase characters instead. This isn't a bug and most wallets do still accept it, but it just looks strange.

### Reproduce

Go to the balances tab on the left, tap "on-chain", then "receive", then enter any information. Select "on-chain", then copy the address. The copied address will begin with `bitcoin:`.

### Zeus version

v0.7.3

### Node interface

LND (REST)

### Network

Clearnet

### Device

OnePlus Nord N20

### Device operating system

Android 12

**Comment by kaloudis** [comment]
This behavior has been changed in v0.7.4
