### ISSUE TITLE
lnd back end RPC errors

### ISSUE THREAD

**Issue by jlopp** [ZeusLN/zeus#1371]
### Describe the bug

Connecting to lnd 0.15.4 via REST

It connects fine, but when I try to create invoices the app is a bit wonky and sometimes skips forward to the completed invoice screen before I can add extra details.

I notice a ton of the following error in my lnd logs at the same time:

[ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: rpc error: code = NotFound desc = unable to find node

### Reproduce

Reproduce the bug step by step.

### Zeus version

v0.7.3

### Node interface

LND (REST)

### Network

Clearnet

### Device

Android

### Device operating system

GrapheneOS

### Log output

```shell
[ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: rpc error: code = NotFound desc = unable to find node
```

**Comment by kaloudis** [comment]
To add details to an invoice you can go to the Balance sliders pane and hit Receive OR you can hit the pencil icon on the keypad pane. You're likely just hitting Receive there which is a shortcut to create a quick invoice.

As far as the RPC error, we're using that endpoint to enrich channel data, including aliases. `GetNodeInfo` returns the latest advertised, aggregated, and authenticated channel information for the specified node identified by its public key - so you're likely not getting info for that node on your network graph.

**Comment by jlopp** [comment]
Gotcha
