### ISSUE TITLE
stranded after lightning payment (back button missing)

### ISSUE THREAD

**Issue by marimes** [ZeusLN/zeus#1394]
### Describe the bug

After a successfully completed lightning payment, I land on the confirmation screen with the white checkbox in the green circle. In previous versions, there was a way to go back to the wallet from this screen. In this version I am stuck on the screen, cannot scroll up or down, and don't see a back button anywhere. To pay the next invoice I need to quit and re-start the app.

### Reproduce

it happens every time I pay an invoice

### Zeus version

v0.7.4

### Node interface

Core Lightning (c-lightning-REST)

### Network

VPN, local access

### Device

iPhone 8

### Device operating system

16.1.2

**Comment by marimes** [comment]
![IMG_7799](https://user-images.githubusercontent.com/12594437/227048225-77a3831b-e0ec-4b74-a0f1-e007e43bbdd4.PNG)

**Comment by kaloudis** [comment]
Thanks for the report. Fixed in this commit: https://github.com/ZeusLN/zeus/commit/dd4f148ec75de8b44024c013f93271f07c64f302

Will roll out beta2 tomorrow

**Comment by kaloudis** [comment]
v0.7.4-beta2 is out now
