### ISSUE TITLE
Malaysian Ringgit not shown properly

### ISSUE THREAD

**Issue by hazrulnizam** [ZeusLN/zeus#1412]
### Describe the bug

Malaysian Ringgit symbol should be 'RM' instead of 'MR'

### Reproduce

Just open the balance page.

### Zeus version

v0.7.4

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy

### Device operating system

Android

**Comment by kaloudis** [comment]
Fixed in v0.7.5
