### ISSUE TITLE
LNURLw still broken on 0.7.4

### ISSUE THREAD

**Issue by prusnak** [ZeusLN/zeus#1419]
### Describe the bug

It seems to me that LNURLw is still broken in 0.7.4.

When I scan a QR code containing LNURLw, it seems the amount value is not picked up - it stays at 0 and I cannot change it.

### Reproduce

1. Scan a QR code containing a LNURLw with fixed amount (eg. min = 10 sat, max = 10 sat)
2. Observe that the amount field cannot be edited and contains 0
3. Pressing "Create invoice" leads to error (since an invoice with amount 0 is not allowed?)

This does not happen when `min != max` in LNURLw only when `min == max`

### Zeus version

v0.7.4

### Node interface

LndHub

### Network

Clearnet

### Device

iPhone

### Device operating system

iOS 16

**Comment by kaloudis** [comment]
@prusnak Would you mind testing the fix provided in https://github.com/ZeusLN/zeus/pull/1427?

**Comment by prusnak** [comment]
I confirm the issue has been fixed via https://github.com/ZeusLN/zeus/pull/1427

(I installed 0.7.5-alpha1 from TestFlight)
