### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by bityogi** [ZeusLN/zeus#1429]
### Describe the bug

I tried to pay someone through a zap on nostr. 

The payment never went through and the app crashed and now every time I open the app and try to go to the activity tab (3rd tab on bottom navigator), the app crashed. 

I am on iOS. 

### Reproduce

Try to zap someone using the Damus app. 

Then follow the steps mentioned above. I am connecting to a lite node on voltage.cloud FYI. 

Also, I tried deleting the app and installing it again, but it looks like there is some data that doesn’t get deleted as it remembers my PIN as well as node info. 

### Zeus version

v0.7.4

### Node interface

LND (REST)

### Network

Tor

### Device

iPhone 13

### Device operating system

iOS 16

**Comment by kaloudis** [comment]
You can clear out data with the v0.7.5 build in TestFlight. There's some odd bug in iOS causes weird behavior like crashes and white screens, but it is cleared out with a v0.7.5 uninstall and reinstall.

**Comment by kaloudis** [comment]
TestFlight: https://testflight.apple.com/join/gpVFzEHN

**Comment by bityogi** [comment]
That worked. Thanks!
