### ISSUE TITLE
Fiat: add currencies: BOB, CRC, GTQ, NIO, PYG, UYU

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#1438]
BOB | Boliviano | 🇧🇴
CRC | Colón | 🇨🇷
GTQ | Quetzal | 🇬🇹
NIO | Nicaraguan Córdoba | 🇳🇮
PYG | Paraguayan Guarani | 🇵🇾
UYU | Peso | 🇺🇾

**Comment by shubhamkmr04** [comment]
I'll do it
