### ISSUE TITLE
Accessibility: Add in: Button Labels, Arrow Labels, Camera visible to scan QR code

### ISSUE THREAD

**Issue by mouxdesign** [ZeusLN/zeus#1442]
Mo here over from the Bitcoin Design community, we would very much like to help to contribute to making lightning wallets more accessible. So we did a few basic tests to test out Zeus wallet.

We made a quick summary of the observations:
- Labelling of the back arrows
- Labelling of buttons

We hope this is useful for you as a team and if there's any questions about the notes we've made please feel free to ask. Also you can join us over at the community on Discord [here. ](https://discord.gg/YMcRh3s8)

![Group 2 (1)](https://user-images.githubusercontent.com/90313394/233592282-98e56e95-fe0f-47cc-9b40-f18feb08728a.jpg)

**Comment by sha-265** [comment]
Hi @mouxdesign, I have few questions:

1. What do you mean "Bitcoin symbol" and "Transactions" here: 
![image](https://github.com/ZeusLN/zeus/assets/4103710/3731239a-db0a-4994-aaad-f69a5b5a5dff)
2. What do you mean "inaccessible" here:
![image](https://github.com/ZeusLN/zeus/assets/4103710/ae45e038-d7b7-413f-9410-d3f1a2526074)
3. What do you mean "this" here. What is not working?
![image](https://github.com/ZeusLN/zeus/assets/4103710/787373ce-0e3e-4b52-9d20-137fac29ce50)

Thanks!

**Comment by mouxdesign** [comment]
@sha-265 Thanks for following up on this one. 

To answer your questions;
1. I'll retest this screen to check (would do that in the week of 17th - 22nd July) 
2. I'd simply check here if the account buttons are labelled. For example the label could read:
- Lightning; Click here to use your lightning balance, you have XXX sats.
- Onchain: Click here to use your on chain balance, you have XXX bitcoin
Not sure if that it possible on the development side. 

Account buttons: 
Just incase those don't have labels you could label them. 
Receive: Receive or click here to route
Routing; Route or click here to route
Send; Send or click here to send

3. This I is just a note here I think that the app had to be restarted.

**Comment by kaloudis** [comment]
Added in v0.8.0!
