### ISSUE TITLE
Full support for LNURL-w Bolt Cards

### ISSUE THREAD

**Issue by Satoshi-Samourai** [ZeusLN/zeus#1448]
We are seeing more and more NFC Bolt Cards on the market.
These cards are programmed with LNBits or are Bolt Cards from Coincorner. They contain not just simple LNURL-w but specific URL for payments that are right now not fully supported in many applications and/or wallets.

Please, consider this feature for implementation in the future. This would greatly improve the UX of Zeus and incentivise even more people to use it.
Thank You.

Please find the Bolt Card specifications here:
https://github.com/boltcard/boltcard/blob/main/docs/SPEC.md

**Comment by kaloudis** [comment]
Closing as a duplicate
