### ISSUE TITLE
Add ability to copy payment hash, preimage, and memo on invoice details screen

### ISSUE THREAD

**Issue by benthecarman** [ZeusLN/zeus#1452]
Would be nice to be able to get the information off of this screen without having to screenshot it

![Aimage](https://user-images.githubusercontent.com/15256660/235780442-b81f0c1f-02e6-4009-8571-5acb32905ac6.png)

**Comment by Ovifer13** [comment]
@kaloudis can I get this one ?

**Comment by Ovifer13** [comment]
@kaloudis For this one this can be done.
![image](https://github.com/ZeusLN/zeus/assets/86666889/11cdd6cf-4402-4e6a-8b89-7441e6199107)
But the `lurkerMode`  won't allow the user to copy the text.
I don't know how to work around this. If I Just delete the `lurkerMode` variable or delete the `!!`, those are the fixes I've encountered.
Let me know what do you think!

**Comment by Ovifer13** [comment]
@kaloudis this can be closed
