### ISSUE TITLE
Add nostr as a topic to this repository

### ISSUE THREAD

**Issue by gourcetools** [ZeusLN/zeus#1457]
Hello,

This repository is listed on the [Awesome Nostr](https://github.com/aljazceru/awesome-nostr) list, which is a collection of useful Nostr projects. However, it seems that the 'nostr' topic is missing from this repository's topics.

Adding the 'nostr' topic will help users discover your project more easily and recognize its relevance to the Nostr ecosystem. To add the topic, please follow these steps:

1. Navigate to the main page of the repository.
2. Click on the gear icon next to "About" on the right side of the page.
3. In the "Topics" section, type 'nostr' and press Enter.
4. Click "Save changes."

Thank you for your attention and for contributing to the Nostr community!

**Comment by kaloudis** [comment]
Added. Thanks
