### ISSUE TITLE
Wallet balance not updated if connected to lndhub

### ISSUE THREAD

**Issue by petrjedlicka83** [ZeusLN/zeus#1458]
### Describe the bug

Hello,

Zeus doesn't refresh balance if connected to lndhub (LNBits 0.10.6)
I would expect behavior like refreshing on balance screen (swipe down) or something like this. Currently balance refresh is done only on connect/reconnect.

### Reproduce

1)Connect zeus to lndhub account. (LNBits 0.10.6)
2) Invoice is created, sats successfuly received from another lightning wallet,
3) Transaction is visible in history of received transactions (GET /lndhub/ext/getuserinvoices), but main wallet balance is never refreshed until reconnect.

GET /lndhub/ext/balance is called only on connect/reconnect.

### Zeus version

v0.7.5

### Node interface

LndHub

### Network

Tor

### Device

Google Pixel 6a

### Device operating system

GrapheneOS (android13)

**Comment by kaloudis** [comment]
Fixed in https://github.com/ZeusLN/zeus/pull/1450 which is on master

This fix will go out in v0.7.6

**Comment by kaloudis** [comment]
Fixed in v0.7.6
