### ISSUE TITLE
Iphone forgets previously saved connected node

### ISSUE THREAD

**Issue by bakerb15** [ZeusLN/zeus#1463]
### Describe the bug

after adding a tor connected node. App works as expected but at some point forgets the saved node causing me to have to re-add the node.

### Reproduce

Reproduce the bug step by step.

### Zeus version

v0.7.5

### Node interface

LND (REST)

### Network

Tor

### Device

iPhone 13

### Device operating system

IOS version 16.4.1 (a)

**Comment by kaloudis** [comment]
This could happen if you skip v0.7.4 before upgrading to v0.7.5

Or has this happened entirely while using v0.7.5?

**Comment by bakerb15** [comment]
I believe entirely on v0.7.5.

Yesterday was first day that I added node. It happened immediately after adding the node. I then re-added and it was good for about 24 hours.

I'm going to attempt to reproduce a 3rd time. I do have a fair amount of technical skills, just not familiar with apple products; this is my first iphone EVER!
I'll try to figure out how to produce some logs if possible.

**Comment by bakerb15** [comment]
Kept the configuration for 3 days and just dropped it. This time i know it wasn't due to any upgrade.

**Comment by kaloudis** [comment]
Switched over to iPhone for my daily driver to diagnose this.

Had this happen to me day 1 with a node connected over LNC

**Comment by kaloudis** [comment]
My theory is that the keychain is often accessed by other apps and that causes this value to not be fetched properly, which then leads to the rest of the Zeus keychain data to be cleared

https://github.com/ZeusLN/zeus/blob/7d281e88bfc7255c1ffb0fb05d6e93edb2a777e3/ios/zeus/AppDelegate.m#L32

**Comment by kaloudis** [comment]
perhaps not though.

related issue: https://github.com/emeraldsanto/react-native-encrypted-storage/issues/116

**Comment by kaloudis** [comment]
Should be partially alleviated with https://github.com/ZeusLN/zeus/pull/1561 - but there are still some cases in which it gets triggered without hitting the `Restart` button
