### ISSUE TITLE
On iOS during payment 'Send', blank screen is shown instead of confirmation

### ISSUE THREAD

**Issue by dirtbag-sats** [ZeusLN/zeus#1471]
### Describe the bug

With both Core Lightning node and LND node, after on 'Send' and then pasting from clipboard a bolt 11 invoice, Zeus will decode the invoice but where you would expect to see the confirmation screen, instead a blank page appears. (Blank white, or blank black if in 'Dark mode'). This happens on iOS for both Zeus App Store version and Test Flight version. Nodes are Core Lightning on LAN via direct IP and LND over Tor. 

Video demo here: https://youtube.com/shorts/lwVeaC3B3x0?feature=share

### Reproduce

- Acquire Bolt 11 invoice on clipboard from WoS or Phoenix or anywhere. 
- Click 'Send' in Zeus.
- Paste invoice.
- Brief screen with 'Lightning invoice' title appears and yellow animation shows processing. 
- Blank window appears with no ability to exit, confirm, or anything else. In previous versions, this is the screen that would appear to confirm a transaction after it had been decoded. 

Happens with both CLN and LND, clearnet or Tor. 

### Zeus version

v0.7.5

### Node interface

Multiple (specified in comments)

### Network

Tor

### Device

iPhone SE

### Device operating system

iOS 16.4.1 (a)

**Comment by kaloudis** [comment]
Temp fix is to uninstall and reinstall the app. Have seen this happen before.

Note that this will cause you to have to reconnect your nodes and settings

**Comment by dirtbag-sats** [comment]
Re-install resolved this issue. Since this doesn't seem to be easily reproducible and isn't common, closing this issue.
