### ISSUE TITLE
Add online/offline to the filter in channels screen

### ISSUE THREAD

**Issue by HappyBear-btc** [ZeusLN/zeus#1476]
### Describe the feature

Add online/offline to the filter in channels screen
![IMG_20230601_160336_923](https://github.com/ZeusLN/zeus/assets/122559990/442b4656-dc93-4d15-916b-883fd21887c1)

**Comment by kaloudis** [comment]
Opted to make this a toggle filter instead of a sort filter, for more functionality: https://github.com/ZeusLN/zeus/pull/1923
