### ISSUE TITLE
Enhancement: Payment successful screen often doesn't fit on screen

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1484]
### Describe the bug

There are lots of different screen resolutions of course, but I think it is possible to make the "Payment successful" screen so it usually fits on a phone screen without the need to scroll. Right now I often have to scroll, although my phone is 1440 x 3200 px.

### Reproduce

-

### Zeus version

v0.7.6

### Node interface

LND (REST)

### Network

Tor

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

**Comment by yanascz** [comment]
Same on iPhone 13 with iOS 16.5.
![IMG_1326](https://github.com/ZeusLN/zeus/assets/37251117/2920835e-b4d2-4330-a8e3-cfa4113eb097)
![IMG_1325](https://github.com/ZeusLN/zeus/assets/37251117/1336e918-56a6-4ef9-8df8-84708cec6960)

**Comment by yanascz** [comment]
Same on iPhone 13 with iOS 16.5.
![IMG_1325](https://github.com/ZeusLN/zeus/assets/37251117/fad8800b-6b42-44bf-81fa-c3029268b59f)
![IMG_1326](https://github.com/ZeusLN/zeus/assets/37251117/2441151e-1465-4a07-9356-f19cd0acfb10)
