### ISSUE TITLE
History doesn't include all transactions when using lndhub

### ISSUE THREAD

**Issue by Dehumanizer77** [ZeusLN/zeus#1510]
### Describe the bug

I don't see complete transaction history in Zeus, some transactions are shown, some are not, I wasn't able to figure out any pattern there. 
I am connecting to my node with lnbits using lndhub via clearnet  and I think this has started after I have received one transaction via lnurl, but I'm not 100% sure if it's related or just coincidence. 
The history in lnbits is complete, the problem is only with Zeus. It was happening in 0.7.5 and the issue is still present in 0.7.6
I can help with debugging if anyone is willing to take care of the issue.

### Reproduce

It seems to me that the problem is only with outgoing transactions, but also not 100% sure.

### Zeus version

v0.7.6

### Node interface

LndHub

### Network

Clearnet

### Device

Xiaomi Poco F3

### Device operating system

Android 12 (Pixel Experience ROM)

**Comment by kaloudis** [comment]
@Dehumanizer77 please let us know what you find in debugging. I suspect LNDHub API incompatibility through the different implementations

**Comment by Dehumanizer77** [comment]
@kaloudis well at the moment the history is almost non-functional in Zeus. I can't even see the transactions done in Zeus itself. My last transaction visible in Zeus is now from Jul 18th, while in LNbits I see 6 other transactions after that, most of them done via Zeus.

**Comment by kaloudis** [comment]
@Dehumanizer77 can you provide more information about the lnbits instance your are using? It is self hosted? Is it the legacy or new version?

**Comment by Dehumanizer77** [comment]
I have lnbits on my own node running Raspiblitz 1.9.0 with lnbits version 0.10.6

**Comment by Dehumanizer77** [comment]
This is still happening. Plus sometimes when I want to create invoice or pay, I'm getting "unexpected end of stream" even though when I do the same directly through lnbits web interface it works. Any news on this? I can help with debugging if needed

**Comment by Dehumanizer77** [comment]
Ok good news, I have upgraded to lnbits 0.10.9 and the history in Zeus (0.7.7) started to work! At least it looks like it on the first sight, I'll test it some more tomorrow.

**Comment by Dehumanizer77** [comment]
@myxmaster thanls for the heads up,  it seems to be fixed now. I'm closing the issue.
