### ISSUE TITLE
back button after transaction successfully sent behaves weirdly

### ISSUE THREAD

**Issue by AndySchroder** [ZeusLN/zeus#1511]
### Describe the bug

Pressing the back button after getting to the transaction successfully sent screen does weird stuff, it:

1. Goes back to the invoice details screen asking me if I want to pay the invoice again, then pressing a second time,
2. Starts trying to scan a QR code again, then pressing a third time,
3. Finally returns to the home screen.

I would expect steps 1 and 2 to be skipped and a single back button press return directly to the home screen.

This problem is not new, it has been around for a year or so.

### Reproduce

1. Send a payment
2. Press back.

### Zeus version

v0.7.6

### Node interface

LND (REST)

### Network

Clearnet

### Device

oneplus

### Device operating system

android

**Comment by myxmaster** [comment]
I agree it should go back to the screen which was displayed before user opened QR scanner. With https://github.com/ZeusLN/zeus/pull/1491 it will not go to QR scanner anymore, but invoice details is still showing up. So this needs another fix.

**Comment by AndySchroder** [comment]
Yeah, still having this problem.

**Comment by myxmaster** [comment]
I just tested, for me it goes back to invoice details, then to wallet. Scanner doesn't come up.
-> So, not the original issue, but still buggy.

But I noticed general problems with back button behaviour and will look into it soon. I don't think we need to reopen this issue here.
