### ISSUE TITLE
QR code scanner keeps re-scanning after an invoice has been scanned

### ISSUE THREAD

**Issue by AndySchroder** [ZeusLN/zeus#1512]
### Describe the bug

Zeus seems to keep re-scanning an invoice over and over again. If I try to scan the invoice, I get the camera mode come up, I scan the invoice and then the invoice is decoded and presented on the screen asking me if I want to pay. If I keep holding the phone in the same spot and don't move, that decoded invoice screen keeps refreshing itself. It appears as though Zeus is scanning the QR code over and over again even though I don't see a view of the camera on the screen. If I move the phone away from the QR code, the refreshing of the screen stops.

Not only is this repeated scanning of the QR code very annoying and confusing, I don't have confidence to know when Zeus actually has the camera on or off (major privacy issue) because it seems to be recording video even when not showing it on the screen. Also, I'm sure this extra effort uses unnecessary battery power.

### Reproduce

1. Scan an invoice
2. Don't move your phone.

### Zeus version

v0.7.6

### Node interface

LND (REST)

### Network

Clearnet

### Device

oneplus

### Device operating system

android

**Comment by shubhamkmr04** [comment]
Hi @AndySchroder , This issue is resolved in this [PR](https://github.com/ZeusLN/zeus/pull/1491), It will be live in our next release

**Comment by kaloudis** [comment]
Fixed in v0.7.7
