### ISSUE TITLE
Filter for unconfirmed transactions.

### ISSUE THREAD

**Issue by seedor-io** [ZeusLN/zeus#1517]
### Describe the feature

I'd like to see a filter where I can see all unconfirmed transactions. Currently the mempool is rather fool and it would be great to have this as an option

**Comment by myxmaster** [comment]
What do you think about this mockup @kaloudis 

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/dff75bc1-c7b1-41fa-8d2a-d69b289821c1)

**Comment by seedor-io** [comment]
That looks perfect. Thanks for the quick work
________________________________

**Comment by kaloudis** [comment]
Out in v0.8.1
