### ISSUE TITLE
CLN + Zeus does not show channel balances, but only "NaN" 

### ISSUE THREAD

**Issue by martinneustein** [ZeusLN/zeus#1521]
### Describe the bug

Hi,

I use Raspiblitz 1.9.0 with CLN 23.02.2 and Zeus 0.7.6 shows no balances on the channel page:

![IMG_2517](https://github.com/ZeusLN/zeus/assets/137636939/2cd80abf-53c2-48d3-995e-c5341a6d65ec)

Raspiblitz came with c-lighning-rest 10.2, an update to 10.4 didn't solve the issue.

### Reproduce

Reproduce the bug step by step.

### Zeus version

v0.7.6

### Node interface

Core Lightning (c-lightning-REST)

### Network

Clearnet

### Device

iphone 12

### Device operating system

iOS 16.5.1

**Comment by myxmaster** [comment]
Can you try it with newest CLN (v23.05.1)?

**Comment by martinneustein** [comment]
CLN v23.05.* solves the issue, thank you.

**Comment by martinneustein** [comment]
Update to any 23.05 version fixes the problem.
