### ISSUE TITLE
Signet invoices are rejected

### ISSUE THREAD

**Issue by afilini** [ZeusLN/zeus#1540]
### Describe the bug

Zeus rejects signet invoices with the error "Unknown coin bech32 prefix". I tracked it down to the bolt11 lib, but it looks like recent versions support it[^1], so it should only be a matter of upgrading the dependency.

Zeus uses `1.2.7` which is 6 releases behind the latest one, `1.4.1`

[^1]: https://github.com/bitcoinjs/bolt11/blob/v1.4.1/payreq.js#L31

### Reproduce

Try paying a signet LNURLp URL.

If trying to pay an invoice directly the error becomes "Value provided is not a valid Bitcoin address or Lightning address", which i believe is just a nicer looking version of the same underlying failure.

### Zeus version

v0.7.6

### Node interface

LndHub

### Network

Clearnet

### Device

Google Pixel

### Device operating system

Android 13

**Comment by kaloudis** [comment]
Will get this patched for you this week in v0.7.7. Thanks for the report

**Comment by kaloudis** [comment]
@afilini can you test v0.7.7-beta2? We've bumped the `bolt11` version in that build

**Comment by kaloudis** [comment]
Fix released in `v0.8.3`
