### ISSUE TITLE
Creating an invoice in BTC always results in 0 sats

### ISSUE THREAD

**Issue by ldwrs** [ZeusLN/zeus#1550]
### Describe the bug

Creating an invoice on iPhone for 0,XXX BTC always results in 0 sats. I don't know if this is relevant but 'm in Europe and my iPhone uses ',' to seperate decimals instead of '.'

### Reproduce

Open zeus wallet (ios). Tap "Lightning" -> "Receive" -> amounts "0,001" -> tap "sats" to switch to Bitcoin logo (Bitcoin unit), tap create invoice. Now in LND I see an invoice for 0 sats.

### Zeus version

v0.7.6

### Node interface

LND (REST)

### Network

Tor

### Device

iPhone 12 mini

### Device operating system

16.5.1

**Comment by kaloudis** [comment]
@ldwrs this is fixed in `v0.7.7-beta1`
