### ISSUE TITLE
Balance pane -> rate in sats: decimal separator can be displayed in wrong place

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1569]
### Describe the bug

When FIAT conversion is enabled and the amount on balance pane is displayed in sats, the rate (sat/USD) can also be displayed. But in case BTC rate ends with some zeros (e.g. 1 BTC = 20,000 $), the rate won't be displayed as `0.00,02 sat/USD` but as `0.0,002 sat/USD`.

This is a good opportunity to discuss it more general though:
I personally think it is weird to display it like this anyway. I mean, I get the idea: You have full USD, then Cents (2 digits) and then decimal places. But to divide a number like this: `0.00,123,456,789` is just so weird for me, when I saw it the first time I had absolutely no idea what that means. Plus, counting to 2 isn't that hard, so telling what is full USD and what is Cents isn't hard anyway - no help needed by some weird decimal (thousands? whatever...) separator.

So, for me it would be much easier to simply display: `0.00029465992 sat/USD`, which simply means `1 sat = 0.00029465992 USD`.

But... Who wants to know how much is 1 sat in FIAT? Maybe we should always stick to the rate in BTC/FIAT (not sat/FIAT).

Would love to hear some feedback from the community on this one.

### Reproduce

-

### Zeus version

v0.7.7

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

**Comment by kaloudis** [comment]
Took a stab at Moscow time here: https://github.com/ZeusLN/zeus/pull/1588
