### ISSUE TITLE
Unit is regularly reset to sats

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1578]
### Describe the bug

On many occasions the unit is automatically reset to sats. It should stick with the unit selected by the user.

### Reproduce

- Go to Receive screen
- Switch unit to Bitcoin
- Enter amount
- Click "Create Invoice"
- Go back
- Go to Receive screen
-> Unit is reset to sats

### Zeus version

v0.7.7

### Node interface

LND (REST)

### Network

Clearnet

### Device

Android Emulator Pixel 7 Pro

### Device operating system

Android 13

**Comment by kaloudis** [comment]
Related to https://github.com/ZeusLN/zeus/issues/1417
