### ISSUE TITLE
Keysend screen: Wrong amount is used when passed from Keypad with unit != sats

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1580]
### Describe the bug

When you pass an amount from Keypad screen to Keysend and the unit is not sats, the amount was always interpreted as sats.

Quick solution is there already: https://github.com/ZeusLN/zeus/pull/1577

But as mentioned in the PR, a better solution is needed to avoid problems in the future (code maintenance, hard to test).

### Reproduce

- copy a lightning node pubkey to clipboard
- go to Keypad screen
- switch unit to BTC
- enter any amount bigger than 0.001 BTC (if smaller, Zeus will crash later)
- click `Send`
- paste node pubkey (to make a keysend payment)
-> original BTC amount is there, but unit now is sats

### Zeus version

v0.7.7

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

**Comment by kaloudis** [comment]
Out in v0.8.1
