### ISSUE TITLE
Turkish characters (Ş,Ç,Ö,ĞÜ) look slightly weird in the app. 

### ISSUE THREAD

**Issue by efecini** [ZeusLN/zeus#1596]
### Describe the bug

Turkish characters look slightly weird in the app. It might be because of the font package that Zeus uses.

![0f19016c-a400-4f68-ae5a-553e0f0aeb48](https://github.com/ZeusLN/zeus/assets/3943422/9d2b82ab-6e8e-490f-b0cd-286fcfc8ab58)

### Reproduce

Select Turkish language.

### Zeus version

v0.7.7

### Node interface

LND (REST)

### Network

Tor

### Device

iphone 13 Pro Max

### Device operating system

iOS 16.6

**Comment by kaloudis** [comment]
The font has changed since this was reported. Would appreciate it if you could check and report back @efecini

**Comment by efecini** [comment]
It looks nice now 👍
![x](https://github.com/user-attachments/assets/7fd71b3b-efca-4256-af56-d6d27d828bc1)
