### ISSUE TITLE
Typo in a transifex source

### ISSUE THREAD

**Issue by efecini** [ZeusLN/zeus#1599]
### Describe the bug

There is a typo in a transifex source below:

A bug happened!You can turn off the LSP entirely and save on these fees by navigating to Settings > Lightning Service Provider (LSP), but you will **sacfrifice** these privacy and payment performance gains.

### Reproduce

Change it from the source.

### Zeus version

None

### Node interface

LND (REST)

### Network

Tor

### Device

iPhone 13 Pro Max

### Device operating system

iOS 16.6

**Comment by kaloudis** [comment]
Thanks fixed in https://github.com/ZeusLN/zeus/pull/1564/commits/6acc0b6084fcd78d2b4ae27e355183e12f98321b
