### ISSUE TITLE
QR codes: "Quiet zone" should be increased to 4 modules

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1604]
### Describe the bug

Not really a bug (at least I personally don't have issues with scanning Zeus QRs) but in general, QR codes need a "quiet zone" (white space) of 4 or more modules:

![marginImage](https://github.com/ZeusLN/zeus/assets/77545287/4710d614-865d-4916-baab-83d570cbd228)
-> https://www.qrcode.com/en/howto/code.html

So even if it usually works like it is now (1 module quiet zone), there is a chance scanning works generally better if we increase it to 4.

### Reproduce

-

### Zeus version

v0.7.7

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

**Comment by kaloudis** [comment]
I think there's a tradeoff here as taking more quiet zone makes the image more dense. we can experiment though

**Comment by myxmaster** [comment]
There is enough space around, so it won't be a difference, here is a mockup:

Before:
![grafik](https://github.com/ZeusLN/zeus/assets/77545287/e993e9fb-12d0-4789-903e-ba8917e0d076)

After:
![grafik](https://github.com/ZeusLN/zeus/assets/77545287/7bcd5254-e513-4042-89e2-e87df2192807)
