### ISSUE TITLE
"You're about to leave Zeus" modal: Close modal by clicking outside or sliding down

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1605]
### Describe the feature

When the "You're about to leave Zeus" modal is displayed, there is some space above the modal. It would be nice if the modal disappeared when you click on that empty space.

Also, the modal slides in from the bottom, so it would also be nice to be able to slide it down to make it disappear.

**Comment by kaloudis** [comment]
I think I've already fixed this on the Pegasus branch. Good call out though

**Comment by kaloudis** [comment]
This is now on master
