### ISSUE TITLE
No auto locking of app when syncing node

### ISSUE THREAD

**Issue by satscoffee** [ZeusLN/zeus#1632]
### Describe the bug

When syncing node in background. App does not time out and lock requiring a pin. 

### Reproduce

Add an embedded node…begin syncing. Switch apps. Wait until the auto lock should typically occur. Switch back to Zeus and verify no PIN is required. 

After looking through settings, I know you can check the toggle to always require a PIN when switching apps. This is working fine. I may be wrong but I thought there was also a timeout as well. If not, disregard. If so, I think there’s a bug. 

Thanks!

### Zeus version

v0.8.0

### Node interface

Embedded LND

### Network

Tor

### Device

iPhone XS Max 

### Device operating system

16.6

**Comment by myxmaster** [comment]
So far there is no time out setting for locking Zeus, but it will come soon™ (https://github.com/ZeusLN/zeus/issues/1615).
