### ISSUE TITLE
Support for Core Lightning's native CLNRest plugin?

### ISSUE THREAD

**Issue by schmitmd** [ZeusLN/zeus#1637]
### Describe the feature

It would seem that the Core Lightning folks have created their own REST API plugin.  Do you see this as a potential feature option to be added?  It looks like it would use a Rune (part of the native core LN service if I understand correctly) rather than Macaroons for auth and permissions.  Any thoughts?

https://github.com/ElementsProject/lightning/tree/master/plugins/clnrest

**Comment by schmitmd** [comment]
#1068 possibly related

**Comment by kaloudis** [comment]
We want to upgrade to this and deprecate c-lightning-REST

We've got a bounty for lnmessage over at https://github.com/ZeusLN/zeus/blob/master/docs/Bounties.md#core-lightning-commandolnmessage-connection. Perhaps we'll add a smaller one for the CLNRest plugin

**Comment by svpi11** [comment]
Same here. The "native clnrest plugin" of CLN integration, would be appreciated a lot !

**Comment by bitcoinlizard** [comment]
"Me to."  I would pay into the bounty.  Now that Ride the Lightning is using the native plugin I could disable c-lightning-REST if Zeus migrated as well.

**Comment by kaloudis** [comment]
Please reach out to support AT zeusln.com via email to coordinate donations to the bounty.

No progress has been made. Commando is somewhat close though.

**Comment by sha-265** [comment]
I did something few mouths ago, but didn't finish it. If there will be a bounty maybe I will free some time to finish it.

**Comment by bitcoinlizard** [comment]
I emailed support AT zeusln.com to commit to a bounty for this feature.

**Comment by schmitmd** [comment]
@kaloudis you mentioned back in January that Commando was "somewhat close", has anything progressed there?

**Comment by kaloudis** [comment]
CLNRest is coming in v0.9.0. Progress hasn't been made on Commando. Related issue: https://github.com/ZeusLN/zeus/issues/1068

**Comment by kaloudis** [comment]
Bounty is paid out and functionality is rolling out in v0.9.0 (currently in rc1 - please test if you can)

**Comment by bitcoinlizard** [comment]
> Bounty is paid out and functionality is rolling out in v0.9.0 (currently in rc1 - please test if you can)

I just tested this and it works as expected.  Great job!

**Comment by ElucGeek** [comment]
Works well thanks!
