### ISSUE TITLE
LNDHub: Zeus crashes when opening activity details

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1656]
### Describe the bug

Zeus crashes when opening activity details.

This is the value of r_hash:

```
{
  "data": [
    109, 227, 192, 103, 47, 45, 30, 57, 202, 189, 188, 5, 175, 217, 16, 114,
    172, 128, 99, 171, 52, 27, 62, 209, 71, 169, 157, 33, 201, 187, 43, 115
  ],
  "type": "Buffer"
}
```

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/00036e17-86c5-46b7-82d0-fe3cc7f1ef41)

### Reproduce

- Connect to an LNDHub node
- Go to activity
- Tap on a payment request or received payment

### Zeus version

v0.8.0

### Node interface

LndHub

### Network

Clearnet

### Device

Android Emulator Pixel 7 Pro

### Device operating system

Android 13

### Log output

```shell
See screenshot
```

**Comment by kaloudis** [comment]
Fixed in https://github.com/ZeusLN/zeus/pull/1652
