### ISSUE TITLE
Close channel with custom fee creates blank screen

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1658]
### Describe the bug

When you try to close a channel and click on the custom fee input (not even needed to enter an amount) and then go back, you get a blank screen:
![grafik](https://github.com/ZeusLN/zeus/assets/77545287/d2bf3593-a143-4f88-b15c-26f9b6606d36)

### Reproduce

- go to channels screen
- click on any channel
- click on "close channel"
- click on fee input
- click on "custom" and optionally enter a fee amount
- click "confirm fee" or go back via arrow on top left or use android back button
-> screen is empty

### Zeus version

v0.8.0

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

**Comment by kaloudis** [comment]
LOL it's the scroll position
