### ISSUE TITLE
Theme colors sometimes incorrect

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1659]
### Describe the bug

When you switch themes, some colors are not loaded correctly.

Example: "(Optional) Sat per byte closing fee" label in the following screenshots. It definitely has the correct theme color, so when using theme "Light" it should be black, but it is not:

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/bb332d1b-b83b-42b0-a5ae-e2608a2e1cae)

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/4ead2973-99e1-4cbe-bd9f-9138c29e7ca3)

### Reproduce

- enable theme dark
- enable theme light
- go to channels screen
- click on any channel
- click on "close channel"
-> label "(Optional) Sat per byte closing fee" is invisble because of wrong color

### Zeus version

v0.8.0

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

**Comment by kaloudis** [comment]
The instance here is fixed with https://github.com/ZeusLN/zeus/pull/1660
