### ISSUE TITLE
A few display issues: Android

### ISSUE THREAD

**Issue by mjlamb** [ZeusLN/zeus#168]
**Describe the bug**
A few display issues on android.
Full screen not visible, screen cut off bottom and unable to scroll to view contents.

**To Reproduce**
1. Click [Receive]
2. Lightning, add a few sats, click [Create Invoice]
3. On this "Successfully created invoice" see ![attached1](https://user-images.githubusercontent.com/2274034/67827707-add88f00-fb35-11e9-9d44-01b84c5e7cd6.jpg)
 the bottom screen detail is inaccessible "Expiration (in seconds)" below is not visible.

4. Also Once invoice is created, click [Show QR]
5. On this "QR" screen is not centered and bottom is cut off see ![attached2](https://user-images.githubusercontent.com/2274034/67827714-b16c1600-fb35-11e9-9c0d-b51c0b9fda44.jpg)

**Expected behavior**
To see all screens and able to scroll if more below.

**Screenshots**

 - OS: Android

 - Device: Android
 - Zeus Version [e.g. v0.1.2]

**Comment by kaloudis** [comment]
Thanks for filing this issue. We'll definitely fix this in the next release

**Comment by ZeusLN** [comment]
Fixed in v0.2.1

**Comment by mjlamb** [comment]
Working great in v0.2.1
