### ISSUE TITLE
JSON Error - meaningless.

### ISSUE THREAD

**Issue by mjlamb** [ZeusLN/zeus#169]
**Describe the bug**
Create a lightning invoice, with no sats value. receive json error.
Should display a validation error that not sats value entered.

**To Reproduce**
1. Click [Receive]
2. No Memo, No Amount, just click [Create Invoice]
3. Error displays
Error creating invoice "unexpected end of JSON input"

**Expected behavior**
A clear message to enter sats invoice value.

**Screenshots**
![1](https://user-images.githubusercontent.com/2274034/67827870-25a6b980-fb36-11e9-877e-9f2a6d602443.jpg)

 - OS: Android
 - Zeus Version [e.g. v0.1.2]

**Comment by kaloudis** [comment]
Another great find. We need to add proper input validation instead of just depending on the REST API

**Comment by ZeusLN** [comment]
alleviated in v0.2.2

**Comment by mjlamb** [comment]
This is still an error. I think you have defaulted in 100 satoshi, But if removed and tap "Create Invoice" I still receive the same JSON error ver 0.2.2
