### ISSUE TITLE
Sending and receiving on-chain: No indication of TX being unconfirmed (embedded LND + testnet)

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1699]
### Describe the bug

I tried this from within the embedded LND in testnet.

When you receive or send sats to/from your on-chain wallet, there is no indication of the TX being unconfirmed. When you receive, you don't see anything until the TX is confirmed. When you send, the amount is deducted from the balance like it is confirmed already.

### Reproduce

-

### Zeus version

v0.8.0

### Node interface

Embedded LND

### Network

Clearnet

### Device

Android Emulator Pixel 7 Pro

### Device operating system

Android 14

**Comment by kaloudis** [comment]
This is a Neutrino constraint
