### ISSUE TITLE
Recovery process (24 words) is confusing

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1700]
### Describe the bug

When you recover an embedded node with the 24 words, you get to this screen:
![grafik](https://github.com/ZeusLN/zeus/assets/77545287/f26c122a-06a0-4016-b639-70517a7998e0)

Instead it should display a message that the import was succesful and then take the user to the balance pane e.g.
Instead right now, when you use the arrow-left icon on top left, it takes you back to settings and even back to intro splash screen.

### Reproduce

-

### Zeus version

v0.8.0

### Node interface

Embedded LND

### Network

Clearnet

### Device

Android Emulator Pixel 7 Pro

### Device operating system

Android 14

**Comment by kaloudis** [comment]
Let's just have it go straight to the main view on success. LND will throw an error if the seed phrase is invalid.

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/commit/1521f60a9eb2c47787657fcd5966848752d3764a
