### ISSUE TITLE
Embedded node sync screen: can display wrong numbers & stops updating when at 100%

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1708]
### Describe the bug

When you leave the sync screen open while syncing until 100%, you can get this:
![grafik](https://github.com/ZeusLN/zeus/assets/77545287/57c7679d-80ce-46c2-b90a-ac4cb544e94c)

It should keep updating although it is at 100%.

### Reproduce

-

### Zeus version

v0.8.0

### Node interface

Embedded LND

### Network

Clearnet

### Device

Android Emulator Pixel 7 Pro

### Device operating system

Android 14

**Comment by kaloudis** [comment]
Is this on a specific build or on master?

**Comment by kaloudis** [comment]
approach #1 should be taken with this block: https://github.com/ZeusLN/zeus/blob/master/stores/SyncStore.ts#L49 - could you take a look and see why it isn't working
