### ISSUE TITLE
Path screen stuck if alias is not retrieved

### ISSUE THREAD

**Issue by HappyBear-btc** [ZeusLN/zeus#1709]
### Describe the bug

If Zeus is unable to retrieve an alias to one of the nodes in the path screen it frezzes and the only option is to kill the app and restart. 

### Reproduce

Swipe up to go to activity screen, choose outgoing payment, expand to see path.
App will freeze if it unable to retrieve one of the aliases 

### Zeus version

v0.8.0

### Node interface

LND (REST)

### Network

Clearnet

### Device

Android

### Device operating system

Android

**Comment by kaloudis** [comment]
addressed in https://github.com/ZeusLN/zeus/commit/d356ae23346a990447ef4de7f19ca897bde05627

**Comment by kaloudis** [comment]
Now rolled out in v0.8.0-alpha55
