### ISSUE TITLE
Channel Opening defaults to 1 sat/byte

### ISSUE THREAD

**Issue by Brian1-A** [ZeusLN/zeus#1723]
### Describe the bug

A bug happened! Several timed ive opemed channels through zeus, selecting the 'fastest' option.  The channel is opened however the fee is 1 sat/byte.  

### Reproduce

Reproduce the bug step by step. Open a channel in zeus app for android.  Choose any option to open the channel and the result will be the funding fee has a 1 sat/byte fee.

### Zeus version

v0.7.7

### Node interface

Core Lightning (c-lightning-REST)

### Network

Tor

### Device

Pixel 4

### Device operating system

Graphene OS

**Comment by kaloudis** [comment]
Can you provide your Core Lightning and c-lightning-REST versions?

**Comment by kaloudis** [comment]
This has been fixed in v0.8.0

Commit with fix: https://github.com/ZeusLN/zeus/commit/ebf5d0674dd996b0bd9e8c2553188bf8e5783de4
