### ISSUE TITLE
Bug: Multiple Nodes setup, display issue.

### ISSUE THREAD

**Issue by mjlamb** [ZeusLN/zeus#173]
When you have multiple nodes configured, and you switch between them, the "Invoice" count does not clear correctly.

**To Reproduce**
Setup 2 nodes
Switch between them.
Notices the invoices count is incorrect for the node you switched to.

**Expected behavior**
Invoice count should be updated to the node you switched to.

**Screenshots**
Attached

 - OS: Android
 - Zeus Version: v0.1.2

![Capture](https://user-images.githubusercontent.com/2274034/69283003-69ca3d00-0c50-11ea-81be-1fb72137daca.PNG)

**Comment by ZeusLN** [comment]
@mjlamb are you still seeing this behavior?

**Comment by mjlamb** [comment]
Yeah this is working better now. Seems to be updating correctly.
Running v0.2.2
Thanks
