### ISSUE TITLE
Send view: Error can be displayed although input was valid

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1731]
### Describe the bug

When you enter something invalid (e.g. "1"), an error is displayed "Value provided was not a valid Bitcoin address or Lightning Invoice". If you delete the wrong input and then paste something valid, that error is displayed again, although it shouldn't of course.

### Reproduce

-

### Zeus version

v0.8.0

### Node interface

Multiple (specified in comments)

### Network

Clearnet

### Device

Android Emulator Pixel 7 Pro

### Device operating system

Android 14

**Comment by shubhamkmr04** [comment]
Hi @myxmaster, would you please review my fix #1746 on this issue and check if that resolved it?
