### ISSUE TITLE
Application crashes on sync progress screen

### ISSUE THREAD

**Issue by cr0bar** [ZeusLN/zeus#1740]
### Describe the bug

Application crashes when tapping on the sync notification.

### Reproduce

1) Open app after a period of inactivity
2) Tap the sync notification at the top
(You should be taken to the progress screen)
3) Application crashes

### Zeus version

v0.8.0

### Node interface

Embedded LND

### Network

Clearnet

### Device

iPhone 14 Pro Max

### Device operating system

iOS 17.1 (21B5045h)

**Comment by kaloudis** [comment]
I've had this happen to me on a prod install, but never happens to me in dev (both simulator and physical device).

weird one. gotta be a dependency/config thing

**Comment by kaloudis** [comment]
Attaching some crash logs

[crashlog.txt](https://github.com/ZeusLN/zeus/files/12862798/crashlog.txt)

**Comment by kaloudis** [comment]
I wonder if this could possibly be related: https://github.com/software-mansion/react-native-reanimated/pull/5087

**Comment by kaloudis** [comment]
Appears to be fixed with https://github.com/ZeusLN/zeus/commit/6ff0216227e2974f25edfd833e7661ee160ab7c6

Rolling out alpha53 now
