### ISSUE TITLE
Core Lightning REST On-chain Receive does not show address

### ISSUE THREAD

**Issue by newtonick** [ZeusLN/zeus#1772]
### Describe the bug

Core Lightning REST On-chain Receive does not show bitcoin address after you tap "CREATE INVOICE" in On-chain receive.

![image](https://github.com/ZeusLN/zeus/assets/127377/68b3603d-35d4-460e-94f5-65da087b4115)

### Reproduce

Reproduce the bug step by step.Core Lightning (c-lightning-REST) wallet, when tap "On-Chain" -> "Receive"

Then enter amount, tap "CREATE INVOICE" a screen is displayed with no bitcoin address. Only thing showing is the back arrow, close button, and "RECEIVE VIA NFC".

Same behavior in Zeus v0.8.0-alpha56, 53, 52 and 49.

### Zeus version

v0.8.0

### Node interface

Core Lightning (c-lightning-REST)

### Network

Clearnet

### Device

iPhone 13 mini

### Device operating system

iOS 17

**Comment by newtonick** [comment]
I forgot to mention, c-lightning-REST version v0.10.7-beta-p2tr-support and Core Lightning version v23.08.1

**Comment by kaloudis** [comment]
No issues with CLN v23.05 and c-lightning-REST v0.10.3. Looks like an API regression.

My bet is something with the new address endpoint requiring an address type

**Comment by newtonick** [comment]
Resolved in 0.8.0 alpha 60
