### ISSUE TITLE
If lnurl payment fails, payment is visible in activity as "in transit"

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1792]
### Describe the bug

I think this is because zaplocker payments also "fail", and can be in transit for up to 24 hours. So we need to distinguish between those fails.

### Reproduce

-

### Zeus version

v0.8.0

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

**Comment by kaloudis** [comment]
Superseded by https://github.com/ZeusLN/zeus/issues/1900
