### ISSUE TITLE
LNDhub: memo not displayed in Payment Requests in Activity

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1799]
### Describe the bug

When you use Zeus to create an invoice with memo with some LNDhub backend (I tested getAlby and lnbits with LNDhub extension), the memo is not displayed in Activity list. It is displayed if you tap the payment request, but not in the overview (like it is the case when using LND as backend e.g.).

### Reproduce

-

### Zeus version

v0.8.0

### Node interface

LndHub

### Network

Clearnet

### Device

Android Emulator Pixel 7 Pro

### Device operating system

Android 14

**Comment by kaloudis** [comment]
I think the problem with this one is it needs to be groked out from the bolt11 invoice, so it drastically slows down the Activity list
