### ISSUE TITLE
Please bring this software to F-Droid

### ISSUE THREAD

**Issue by d4f5409d** [ZeusLN/zeus#1807]
🙏

**Comment by kaloudis** [comment]
We have a self-hosted F-Droid that you can connect to at https://zeusln.app/download

**Comment by d4f5409d** [comment]
But could you bring it to the main repo?

**Comment by kaloudis** [comment]
We've decided to focus on [our own reproducible builds](https://github.com/ZeusLN/zeus#reproducible-builds) than worry about keeping our F-Droid system build maintained, but others are free to do so.

**Comment by d4f5409d** [comment]
But why?

**Comment by kaloudis** [comment]
Docker and shell scripts are far more general, common, and easier to maintain.
