### ISSUE TITLE
Icon for open zaplocker payments not updated when switching nodes

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1810]
### Describe the bug

First of all, Zeus should check during app start if there are open zaplocker payments and if so, the icon for open zaplocker payments should be displayed in wallet header:
![grafik](https://github.com/ZeusLN/zeus/assets/77545287/d868543e-c944-41e5-a0ca-852a64cc58b6)
Right now, it will only be displayed if user went to Settings -> Lightning address.

So when the icon is there, and user switches to a different node (with different or no LN-address set up) Zeus needs to recheck and show/hide the icon in wallet header. Right now Zeus will continue to show the icon in the wallet header.

### Reproduce

-

### Zeus version

v0.8.0

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

**Comment by kaloudis** [comment]
Everything should be getting reset here: https://github.com/ZeusLN/zeus/blob/master/views/Wallet/Wallet.tsx#L293

**Comment by kaloudis** [comment]
> > Everything should be getting reset here: https://github.com/ZeusLN/zeus/blob/master/views/Wallet/Wallet.tsx#L293
> 
> But refresh() doesn't get called when switching nodes. And when you do a pull down refresh, `SettingsStore.connecting` is `false`.

Seems like a refactor is in order here

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/1816/files
