### ISSUE TITLE
Do not automatically go to 'Send' screen when LN-address is entered

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#1811]
### Describe your enhancement idea

Zeus should not automatically navigate to the 'Scend' screen when a user enters an LN-address. For pasting it is fine, but for typing manually it can be a problem, here is why:
Let's say user wants to send to fren@zeuspay.com, but now somebody made an LN-address 'fren@zeuspay.co'. The user will not be able to type the last char 'm' of the address, because Zeus recognizes a valid LN-address 'fren@zeuspay.co' and navigates to 'Send'.

**Comment by shubhamkmr04** [comment]
In my opinion, we should introduce a button named `PROCEED` to go with the address to solve this issue. What do you think?

**Comment by shubhamkmr04** [comment]
@myxmaster would you please check [PR](https://github.com/ZeusLN/zeus/pull/1819) for this issue?
