### ISSUE TITLE
Password/Pin: Improve layout

### ISSUE THREAD

**Issue by shubhamkmr04** [ZeusLN/zeus#1823]
### Describe your enhancement idea

We would have to refactor the UI of some screens from the password/pin section. 
Some of the views we have to work on:

![Screenshot_1699110443](https://github.com/ZeusLN/zeus/assets/50761978/e84f848d-1a7b-4875-a4ac-d25dce18c745)
![Simulator Screenshot - iPhone 14 Plus - 2023-11-04 at 20 23 03](https://github.com/ZeusLN/zeus/assets/50761978/9a04a8b5-86e6-409f-a8c6-bb4593fd7f35)
![Screenshot_1699110196](https://github.com/ZeusLN/zeus/assets/50761978/aa21c157-a6b6-4af1-9154-04bd84ba87d1)

**Comment by shubhamkmr04** [comment]
Hmm, that might be the case. I'll have to debug what's actually happening in iOS. In android also, we can see some spacing issue once we type in something.

**Comment by kaloudis** [comment]
Fixed in `v0.8.4`
