### ISSUE TITLE
Combined QR Code (BTCPay) with on-chain and LNURL (top-up invoice in btcpay terms) leads to error when scanning

### ISSUE THREAD

**Issue by petzsch** [ZeusLN/zeus#1858]
### Describe the bug

When trying to pay to this QR Code:

![grafik](https://github.com/ZeusLN/zeus/assets/1374810/280d9b6e-88a3-4c26-9ba5-4b81208de45b)

and selecting Lightning as the account, I get the error message:
"Error loading invoice: Error: invoice not for current active network 'mainnet'"

### Reproduce

Create in invoice with "custom Amount" on my [storefront](https://otr.4sats.net/?email=markus@petzsch.eu) and try to scan the resulting QR Code with ZeusLN. (as described above)

To create such an invoice in BTCPay, you simply create a store, with i.e. getAlby as LNDHub backend. Also setup an on-chain wallet and then you can create an invoice without an amount. (top-up invoice)

### ZEUS version

v0.8.0

### Node interface

Embedded LND

### Network

Clearnet

### Device

Samsung Galaxy A52s 5G

### Device operating system

Android 13

**Comment by petzsch** [comment]
Addition: Copying and pasting the LNURL from below the QR code works perfectly fine.

**Comment by kaloudis** [comment]
Draft PR here: https://github.com/ZeusLN/zeus/pull/1859

**Comment by kaloudis** [comment]
Should be fixed in v0.8.1
