### ISSUE TITLE
can't send zaps using 0.8.0-Beta4 with alby wallet

### ISSUE THREAD

**Issue by avaaum** [ZeusLN/zeus#1867]
### Describe the bug

can't send zaps using 0.8.0-Beta4 with alby wallet

### Reproduce

i can't zap using alby on nostr via zeus mobile app anymore. the zap hangs just before completion every time. 

and, i can't zap my zeus wallet from my alby wallet without a zaplocker message that ultimately goes through but takes ~15 min to complete

this is not usual behavior

note: i can zap others using the alby extension. i can receive zaps with alby wallet and zeus wallet. i can zap alby using my zeuspay embedded address. i can send zaps from zeus to alby via zeus.

any suggestions? thx

### ZEUS version

v0.8.0

### Node interface

LndHub

### Network

Clearnet

### Device

Pixel 6 Pro

### Device operating system

GrapheneOS

**Comment by avaaum** [comment]
used alby on a different device. re-added the master key and nostr connections and all is well 🙄

**Comment by avaaum** [comment]
nvm..it's back

**Comment by kaloudis** [comment]
Are we sure this isn't a problem with Alby and their backend?

**Comment by avaaum** [comment]
not sure, but i'm starting to think that. will close this if i get a resolution from their end

**Comment by avaaum** [comment]
closing this because i thought about it and alby nwc with amethyst has no possibility of anything to do with zeus. sorry to bother. stay awesome!
