### ISSUE TITLE
Payment flow from keypad switches currency and causes invoice to be wrong amount

### ISSUE THREAD

**Issue by newtonick** [ZeusLN/zeus#1871]
### Describe the bug

I'm going to suck at trying to describe this, so watch the screen recording. I want to pay $4.75 equivalent of sats to a contact starting from the keypad screen. 2 bugs in this flow.

1) When I change the keyboard currency to USD, enter an amount, then hit send ... the amount to pay screen converts $4.75 to 4.75 sats.

2) If I hit confirm on the amount screen and go to the lightning invoice screen; and then the back button ... even if I change the currency to USD ... the invoice amount is still wrong (5 sats).

### Reproduce

I have 8.0 beta 4 iOS

https://github.com/ZeusLN/zeus/assets/127377/49330a50-4355-4fbe-a38b-326b797bf18b

### ZEUS version

v0.8.0

### Node interface

Core Lightning (c-lightning-REST)

### Network

Clearnet

### Device

iPhone 13

### Device operating system

iOS 17

**Comment by shubhamkmr04** [comment]
Hey @newtonick, would you review #1881 and let me know if it has fixed the bug?

**Comment by newtonick** [comment]
I didn't build myself, but I believe PR #1881 was included in 8.0-rc2 and I verified this bug is fixed there. Thank you!
