### ISSUE TITLE
Font file not found

### ISSUE THREAD

**Issue by chdwlch** [ZeusLN/zeus#1890]
### Describe the bug

When trying to run the react-native app for the first time, the build errors with 
```
/Users/chad/ZeusLN/zeus/assets/fonts/ppneuemontreal-medium.otf 
/Users/chad/ZeusLN/zeus/assets/fonts/ppneuemontreal-medium.otf: No such file or directory
```

I believe in ios/zeus.xcodeproj/project.pbxproj the font has a path dependent on the top level ZeusLN directory.

```
74F9D7E92AF33137007D44BF /* ppneuemontreal-medium.otf */ = {isa = PBXFileReference; lastKnownFileType = file; name = "ppneuemontreal-medium.otf"; path = "../../../../../ZeusLN/zeus/assets/fonts/ppneuemontreal-medium.otf"; sourceTree = "<group>"; };
74F9D7EF2AF33324007D44BF /* ppneuemontreal-medium.otf */ = {isa = PBXFileReference; lastKnownFileType = file; name = "ppneuemontreal-medium.otf"; path = "../../../ZeusLN/zeus/assets/fonts/ppneuemontreal-medium.otf"; sourceTree = "<group>"; };
```

i.e.
`path = "../../../ZeusLN/zeus/assets/fonts/ppneuemontreal-medium.otf`

I had to remove `../ZeusLN` from both paths to resolve the correct path.
`/Users/chad/zeus/assets/fonts/ppneuemontreal-medium.otf`
		

### Reproduce

Fresh clone of zeus and attempt to build for iOS.

### ZEUS version

None

### Node interface

Embedded LND

### Network

Tor

### Device

iPhone 14 Pro

### Device operating system

iOS 16.4

**Comment by kaloudis** [comment]
Addressed with commit https://github.com/ZeusLN/zeus/commit/3e51c3ca17d96874cf9833e12d2b59e5701d249b

@chdwlch can you pull latest and try again?
