### ISSUE TITLE
wallet erased

### ISSUE THREAD

**Issue by ralyodio** [ZeusLN/zeus#1896]
### Describe the bug

i hadn't backed up my zeus key yet and the automatic update installed a new wallet. i had 1M sats in my old wallet, is there anyway to get it back?

### Reproduce

Reproduce the bug step by step.i hadn't backed up my zeus key yet and the automatic update installed a new wallet. i had 1M sats in my old wallet, is there anyway to get it back?

### ZEUS version

v0.8.0

### Node interface

Embedded LND

### Network

Clearnet

### Device

iphone 12

### Device operating system

ios

### Log output

```shell
i hadn't backed up my zeus key yet and the automatic update installed a new wallet. i had 1M sats in my old wallet, is there anyway to get it back?
```

**Comment by kaloudis** [comment]
Known issue regarding iOS

Was able to assist user and get them connected to their BTCPay server again
