### ISSUE TITLE
[bug] Closed channels: crash on sort by Close height

### ISSUE THREAD

**Issue by NEEDcreations** [ZeusLN/zeus#1898]
### Describe the bug

My app on Android is crashing after trying to sort channels by "Close height."

### Reproduce

closed channels, sort, close height (then it crashes)

### ZEUS version

v0.8.0

### Node interface

LND (Lightning Node Connect)

### Network

Tor

### Device

Google Pixel 4A

### Device operating system

Android

**Comment by kaloudis** [comment]
Should be fixed in the v0.8.1 betas

**Comment by kaloudis** [comment]
Fixed in v0.8.1
