### ISSUE TITLE
Reorder and/or group nodes

### ISSUE THREAD

**Issue by satscoffee** [ZeusLN/zeus#1914]
### Describe your enhancement idea

Zeus would be better if you could reorder and/or group nodes. As far as I know, the current protocol only allows for the node order to be chronological in order of create within Zeus. It would be awesome if you could tap/hold or long tap a node to open a drag/drop option to reorder your nodes. 

Additionally, similar to Apple, it would be cool if/when you drop a node on another node, it creates a folder/hierarchy structure. Use case could be adding a group as custodial/non-custodial or grouping your personal node together with Tor, VPN, local IP node configurations.

PS you guys rock. Best Lightning wallet software imo.

![drag drop reorder zeus](https://github.com/ZeusLN/zeus/assets/123999813/84656bbd-ffca-4d99-82e1-91bd30d7eaef)

**Comment by kaloudis** [comment]
Duplicate of https://github.com/ZeusLN/zeus/issues/1642

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/1922

**Comment by kaloudis** [comment]
Out in v0.8.1
