### ISSUE TITLE
The app on Google Play has a surprising versionCode

### ISSUE THREAD

**Issue by Giszmo** [ZeusLN/zeus#1926]
### Describe the bug

I'm trying to reproduce the app and while at that tag the app/build.gradle lists `versionCode: '80'`, the app from Google Play has `versionCode: '80003'`.

I'm struggling a bit with the recent changes in the app introducing `stamp-cert-sha256` and diffs in `AndroidManifest.xml` and try to come to definite rules as to what is by design of how Play Store works and what is in the hands for the app providers. The versionCode I assume should be reproducible.

### Reproduce

Reproduce the bug step by step.

### ZEUS version

v0.8.0

### Node interface

Embedded LND

### Network

Tor

### Device

none

### Device operating system

none

### Log output

```shell
├── AndroidManifest.xml (decoded)
│ ├── AndroidManifest.xml
│ │ @@ -1,9 +1,9 @@
│ │  <?xml version="1.0" encoding="utf-8"?>
│ │ -<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="80003" android:versionName="0.8.0" android:compileSdkVersion="33" android:compileSdkVersionCodename="13" package="app.zeusln.zeus" platformBuildVersionCode="33" platformBuildVersionName="13">
│ │ +<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="80" android:versionName="0.8.0" android:compileSdkVersion="33" android:compileSdkVersionCodename="13" package="app.zeusln.zeus" platformBuildVersionCode="33" platformBuildVersionName="13">
│ │    <uses-sdk android:minSdkVersion="28" android:targetSdkVersion="33"/>
│ │    <uses-permission android:name="android.permission.INTERNET"/>
│ │    <uses-permission android:name="android.permission.CAMERA"/>
│ │    <uses-permission android:name="android.permission.NFC"/>
│ │    <uses-permission android:name="android.permission.VIBRATE"/>
│ │    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
│ │    <uses-feature android:name="android.hardware.nfc.hce" android:required="false"/>
│ │ @@ -214,10 +214,9 @@
│ │      <activity android:theme="@android:style/Theme.Translucent.NoTitleBar" android:name="com.jakewharton.processphoenix.ProcessPhoenix" android:exported="false" android:process=":phoenix"/>
│ │      <service android:name="com.google.android.datatransport.runtime.backends.TransportBackendDiscovery" android:exported="false">
│ │        <meta-data android:name="backend:com.google.android.datatransport.cct.CctBackendFactory" android:value="cct"/>
│ │      </service>
│ │      <service android:name="com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService" android:permission="android.permission.BIND_JOB_SERVICE" android:exported="false"/>
│ │      <receiver android:name="com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastReceiver" android:exported="false"/>
│ │      <meta-data android:name="com.facebook.soloader.enabled" android:value="false"/>
│ │ -    <meta-data android:name="com.android.vending.derived.apk.id" android:value="1"/>
│ │    </application>
│ │  </manifest>
```

**Comment by kaloudis** [comment]
Need to see if we can opt out of this behavior, or at least manually set different version codes ourself

**Comment by kaloudis** [comment]
We can generate different version codes by modifying the `build.gradle` will try to put something together so this is sorted for the general `v0.8.1` release

**Comment by kaloudis** [comment]
It appears we already have the code to do this here: https://github.com/ZeusLN/zeus/blob/master/android/app/build.gradle#L142

So it appears Google is not changing the version codes. Only the universal version should have the same matching version code.

Only diff should be the added Google signature, I believe

**Comment by Giszmo** [comment]
The diff looks similar for v0.8.1. Am I doing anything wrong?

```
│ -  versionCode: '81003'
│ +  versionCode: '81'
```

Also the stamp-cert-sha256 ... what can we do about this? It's in the root directory and the manifest.mf contains its hash but where does it come from? I did some googling but maybe you know?

**Comment by kaloudis** [comment]
> The diff looks similar for v0.8.1. Am I doing anything wrong?
> 
> ```
> │ -  versionCode: '81003'
> │ +  versionCode: '81'
> ```
> 
> Also the stamp-cert-sha256 ... what can we do about this? It's in the root directory and the manifest.mf contains its hash but where does it come from? I did some googling but maybe you know?

Here are the architectures and corresponding version codes:

universal: 81
armeabi-v7a: 81001
x86: 81002
arm64-v8a: 81003
x86_64: 81004 

The `stamp-cert-sha256` is an additional signature from Google

**Comment by Giszmo** [comment]
Ok, I think I figured out how to improve the results. Listing the app as reproducible.
