### ISSUE TITLE
See history of generated receiving on-chain addresses

### ISSUE THREAD

**Issue by jviki** [ZeusLN/zeus#1930]
### Describe your enhancement idea

Make possible to somehow see the history of generated on-chain addresses, e.g. in Activity panel. When I generate few on-chain receive addresses, I quickly loose awareness of them. I cannot double check which address was used for what  purpose.

**Comment by kaloudis** [comment]
@myxmaster this is possible with the following LND API: https://lightning.engineering/api-docs/api/lnd/wallet-kit/list-addresses/index.html

Might add this to v0.9.0 external account efforts

**Comment by kaloudis** [comment]
WIP https://github.com/ZeusLN/zeus/pull/2242

**Comment by kaloudis** [comment]
This has been added in ZEUS v0.9.1
