### ISSUE TITLE
Close channel fee amount is wrong 

### ISSUE THREAD

**Issue by zynos** [ZeusLN/zeus#1937]
### Describe the bug

I closed a channel of mine and set the fees to 35 sat /vbyte in the zeusln app connected to my lnd node. When I looked at the mempool transaction it showed 65.5 sat / vbyte fee! 

### Reproduce

Click on a channel and click on the close channel button. Set a fee and confirm.

### ZEUS version

v0.8.0

### Node interface

LND (REST)

### Network

Clearnet

### Device

iPhone 12 

### Device operating system

17.2.1

**Comment by kaloudis** [comment]
Was it a force close or a mutual close?

**Comment by zynos** [comment]
Cooperative close as Zeus calls it in the app

**Comment by kaloudis** [comment]
There is a bit of a fee negotiation done with coop closes. It is possible your counterparty insisted on a higher closing fee.

**Comment by zynos** [comment]
How can I find out my partner nodes policies for setting the closing fees before I close a channel?

**Comment by kaloudis** [comment]
you can't see it ahead of time. but you can potentially look through your node logs to see what the negotiation looked like

**Comment by zynos** [comment]
You are right @kaloudis . It looks like LND ignores ZeusLNs proposed Fee? Or is The app not sending it correctly to LND?
LND logs that the optimal fee is 6755 and does not mention the fees I entered into Zeus

`01.658 [INF] CHCL: Ideal fee for closure of ChannelPoint(:1) is: 6755 sat (max_fee=20265 sat)`
After that the negotiation takes place, but without changing the "Ideal fee".

```
01.658 [INF] CHCL: Ideal fee for closure of ChannelPoint(:1) is: 6755 sat (max_fee=20265 sat)
01.659 [INF] CHCL: ChannelPoint(:1): shutdown response received, entering fee negotiation
01.660 [INF] CHCL: ChannelPoint(:1): proposing fee of 6755 sat to close chan
02.025 [INF] CHCL: ChannelPoint(:1): computing fee compromise, ideal=6755, last_sent=6755, remote_offer=33184
02.027 [INF] CHCL: ChannelPoint(:1): proposing fee of 7430 sat to close chan
02.633 [INF] CHCL: ChannelPoint(:1): computing fee compromise, ideal=6755, last_sent=7430, remote_offer=29866
02.634 [INF] CHCL: ChannelPoint(:1): proposing fee of 8173 sat to close chan
02.961 [ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: rpc error: code = NotFound desc = unable to find node
02.966 [ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: rpc error: code = NotFound desc = unable to find node
02.969 [ERR] RPCS: [/lnrpc.Lightning/GetNodeInfo]: rpc error: code = NotFound desc = unable to find node
03.024 [INF] CHCL: ChannelPoint(:1): computing fee compromise, ideal=6755, last_sent=8173, remote_offer=26880
03.026 [INF] CHCL: ChannelPoint(:1): proposing fee of 8990 sat to close chan
03.313 [INF] CHCL: ChannelPoint(:1): computing fee compromise, ideal=6755, last_sent=8990, remote_offer=24192
03.316 [INF] CHCL: ChannelPoint(:1): proposing fee of 9889 sat to close chan
03.672 [INF] CHCL: ChannelPoint(:1): computing fee compromise, ideal=6755, last_sent=9889, remote_offer=21773
03.673 [INF] CHCL: ChannelPoint(:1): proposing fee of 10877 sat to close chan
03.997 [INF] CHCL: ChannelPoint(:1): computing fee compromise, ideal=6755, last_sent=10877, remote_offer=19596
03.999 [INF] CHCL: ChannelPoint(:1): proposing fee of 11964 sat to close chan
04.312 [INF] CHCL: ChannelPoint(:1): computing fee compromise, ideal=6755, last_sent=11964, remote_offer=17637
04.315 [INF] CHCL: ChannelPoint(:1): proposing fee of 13160 sat to close chan
04.777 [INF] CHCL: ChannelPoint(:1) fee of 0.00013160 BTC accepted, ending negotiation
04.788 [INF] CHCL: Broadcasting cooperative close tx: (*wire.MsgTx)(..)({
```

**Comment by zynos** [comment]
Maybe related:
https://github.com/lightningnetwork/lnd/issues/8309
