### ISSUE TITLE
LNDHub using wrong server settings

### ISSUE THREAD

**Issue by beinardus** [ZeusLN/zeus#1955]
### Describe the bug

Zeus seems to use the settings of a previous connection type. Causing a failure in the communication over LNDHub because of an incorrect port. Workaround is to reinstall Zeus.

I think the problem is in /backends/LND.ts on line 122:
const url = this.getURL(host || lndhubUrl, port, methodRoute, true);

When "host" is set, "lndhubUrl" is ignored.

### Reproduce

I was trying to connect to my own node using "LND (REST)". I thought this was the gRPC interface and tried communicating over port 10009. When this obviously failed, I switched to "LNDHub". Filled out the server settings: https://[scrubbed]:3015 (I use nginx to forward to port 3000 in Docker). Then I picked the option to create a new account. The next page then opened with a green message on top that the account was created and I had to confirm the settings. After confirmation the account failed.
When looking in the Nginx log, I found only the "/create" API call and nothing else. When inspecting the Redis database I found a new entry for the attempt.
Then I created a proxy tunnel (WiFi -> Fiddler) between the mobile and my desktop. When inspecting the data, it turned out all following calls were still send over port 10009:

https://[scrubbed]:10009/v1/transactions?end_height=-1
https://[scrubbed]:10009/v1/balance/blockchain
https://[scrubbed]:10009/balance
https://[scrubbed]:10009/auth?type=auth

I just couldn't get Zeus to use the configured LNDHub port 3015. I found a workaround by reinstalling Zeus and direcly opting for the LNDHub connection type.

### ZEUS version

ZEUS v0.8.0

### Node interface

LndHub

### Network

Clearnet

### Device

Redmi 5G

### Device operating system

Android

**Comment by kaloudis** [comment]
What version of Zeus are you using?

**Comment by kaloudis** [comment]
This is an exceptional find. Thank you for reporting.

**Comment by kaloudis** [comment]
This should alleviate the issue https://github.com/ZeusLN/zeus/commit/eaf9d57f969e664cbc9099f84594910f3e2c8c1b

Will roll this out in the next `v0.8.1` build

**Comment by kaloudis** [comment]
Address in v0.8.1
