### ISSUE TITLE
[AT&T] SSL error on Lightning address page 

### ISSUE THREAD

**Issue by aChrisYouKnow** [ZeusLN/zeus#1957]
### Describe the bug

I’m getting the following error (screenshot below). It says “Error: An SSL error has occurred and a secure connection to the server cannot be made.” This is on the lightning address screen. When I tap the error it disappears. However, when I reenter the lightning address that is now missing, and hit “create lightning address” the error pops back up. 

Is there any way to get my Lightning address working again? 

![IMG_4649](https://github.com/ZeusLN/zeus/assets/15918863/9ae5cacf-a2a2-4f1c-ae9d-b806b6cea22a)

### Reproduce

Go to settings, select Lightning address, and my Lightning address is gone, with this error above it. 

### ZEUS version

v0.8.1

### Node interface

Embedded LND

### Network

Clearnet

### Device

iPhone 13 mini

### Device operating system

17.2.1

**Comment by kaloudis** [comment]
Would you mind sharing your mobile or internet provider? We've discovered there's an issue with our cert on the AT&T network

**Comment by aChrisYouKnow** [comment]
Yea, I’m using AT&T. Any known fix to manually trust the cert?

**Comment by kaloudis** [comment]
[zeusln-com.pem.zip](https://github.com/ZeusLN/zeus/files/14002485/zeusln-com.pem.zip)

might be able to install the file above. Otherwise you have to use a VPN to work around it for now.

We're going to try to contact AT&T to remedy

**Comment by kaloudis** [comment]
Added an issue on the AT&T Forums here: https://forums.att.com/conversations/att-internet-security/certificate-chain-for-zeuspaycom-broken-on-att-mobile-works-fine-on-all-other-connection/65ad73ff46076f4da647381a

Let's see

**Comment by aChrisYouKnow** [comment]
Thanks. Even after installing the certificate, still was getting the SSL error on AT&T network. I stuck with the VPN though and that works fine. Was giving a zeus demo at a meetup and just instructed those with AT&T to get a VPN if they didn't have one. It was a good demo of how quickly you can be up and running there with https://lnvpn.net . 

Appreciate the quick responses. 

-Chris

**Comment by kaloudis** [comment]
@aChrisYouKnow we've made an nginx config change that seems to remedy the issue. Let us know if it works for you now.

**Comment by aChrisYouKnow** [comment]
Nice, yea, back to working on mobile! I'll mark the issue closed.
