### ISSUE TITLE
Wallet Recovery Fail 

### ISSUE THREAD

**Issue by noeljbass** [ZeusLN/zeus#1972]
Android Galaxy a23

-Downloaded most recent update
-Entered ciolpher seed phrase
-clicked mainnet to pull up/force close existing channels
-loading wallet screen remained for hours
-Attemptes to recover funds multiple times afterwards with cipher seed with same results

The screen never loads the wallet

**Comment by kaloudis** [comment]
We are working on improving the recovery process in v0.8.2 - there is currently very poor error handling.

I recommend uninstalling and reinstalling the app and trying again. If that fails you may have an error in typing in your seed.

**Comment by kaloudis** [comment]
New wallet recovery UI is now rolled out for testing in [`v0.8.2-beta1`](https://github.com/ZeusLN/zeus/releases/tag/v0.8.2-beta1)

**Comment by noeljbass** [comment]
Thank you guys, I finally got into my old account successfully! The new setup for recovery is fantastic.

**Comment by kaloudis** [comment]
Love to hear it. Closing the issue for now, but please re-open or reach out if you have any further issues. Thank you.
