### ISSUE TITLE
LNURL payment amount defaults to current currency

### ISSUE THREAD

**Issue by dadofsambonzuki** [ZeusLN/zeus#1981]
### Describe the bug

When paying an LNURL the amount to pay is whatever the requested sat amount is, but the amount presented it the sat amount in whatever the current default currency.

### Reproduce

I have GBP as the current primary display currency. I scan a 500 sat LNURL. I am presented with a 500 GBP (!) pay screen.

This also applies to having BTC as the default currency.

### ZEUS version

v0.8.1

### Node interface

Embedded LND

### Network

Clearnet

### Device

Google Pixel 7a

### Device operating system

Android

**Comment by kaloudis** [comment]
Fix is now rolled out for testing in [`v0.8.2-beta1`](https://github.com/ZeusLN/zeus/releases/tag/v0.8.2-beta1)

**Comment by kaloudis** [comment]
Fixed in `v0.8.2`. Please reopen if you come across the issue again.
