### ISSUE TITLE
Improve Error Handling for User Clarity

### ISSUE THREAD

**Issue by shubhamkmr04** [ZeusLN/zeus#2003]
### Describe your enhancement idea

Currently, our error messages display entire objects, causing user confusion. We should streamline the error display to show concise, user-friendly messages for better understanding and enhanced user experience.

Some examples would be:
<img width="371" alt="Screenshot 2024-02-27 at 4 09 50 PM" src="https://github.com/ZeusLN/zeus/assets/50761978/e5a797ab-a0fe-4d3c-9ba3-19852aaf8bcf">
<img width="376" alt="Screenshot 2024-02-27 at 4 11 09 PM" src="https://github.com/ZeusLN/zeus/assets/50761978/c5d81d04-dcb4-4b02-8fbd-534a302a66cb">
<img width="374" alt="Screenshot 2024-02-27 at 4 13 05 PM" src="https://github.com/ZeusLN/zeus/assets/50761978/c7207edd-0316-4f43-b6e8-6a1cd2b8548f">

**Comment by kaloudis** [comment]
We can likely add a try-catch block where we parse error strings and try to present the `message` field. Maybe an addition to `ErrorUtils`?
