### ISSUE TITLE
Amount entered on Keypad in PoS is not shown among paid invoices

### ISSUE THREAD

**Issue by jooray** [ZeusLN/zeus#2005]
### Describe the bug

When I request a particular (fiat or sat) amount using the keypad module in PoS, there is a request button that goes immediately to payment screen. Clicking request gives me the invoice and when I pay it and go back to the screen, I see a "custom" entry in PoS (not charged) and I don't see the paid invoice in the list.

What I would expect is that the keypad just adds the custom item with typed amount and I go back to the main PoS screen where I request the invoice. Or if it is like this (immediate payment request after typing the amount) that the custom amount invoice is shown among the list of paid invoices.

This way the staff does not see the paid invoice - not in new, open nor paid invoices. So the invoice can be paid but this cannot be verified by the staff!

### Reproduce

1. PoS settings, enable "Show Keypad"
2. Go to PoS, go to Bitcoin logo to show keypad. 
3. Type "1000 sats", click Request
4. Click Pay for the Custom item of 1000 sats
5. Pay the invoice that is shown
6. After successful payment, go to the list of Paid invoices in PoS - I cannot see it being paid
7. There is a "Charge" with the Custom item that has already been paid. If I create another invoice here (by clicking Charge (1 - 1000 sat) and then Pay, it appears there. But I cannot go to this screen from the keypad flow.

### ZEUS version

v0.8.1

### Node interface

Embedded LND

### Network

Clearnet

### Device

Google Pixel Fold

### Device operating system

GrapheneOS

**Comment by kaloudis** [comment]
Thanks for the report! Was able to recreate. Have a path forward on a fix

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/commit/ff9ce519c3ae561377430087eef7c416329c5a00

**Comment by kaloudis** [comment]
Fix is now rolled out for testing in `v0.8.2-beta1`

**Comment by kaloudis** [comment]
Fixed in `v0.8.2`. Please reopen if you come across the issue again.
