### ISSUE TITLE
Feature: Add 'Send Max' button to on-chain send screen

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#201]
h/t k3tan for the suggestion

**Comment by kaloudis** [comment]
This is going to require fee estimation in LND, I believe.

**Comment by Bosch-0** [comment]
On this screen tapping the on-chain balance will pop up a notification that asks if the user wants to send the entire balance. Was originally going to have a 'Max Send' button but could see the rare case something clicks it on accident and doesn't realize. 

![image](https://user-images.githubusercontent.com/55287964/144196853-21d9382f-8ff9-4b9d-952f-c2275c4f2bea.png)

**Comment by kaloudis** [comment]
`v0.8.0` now has sweep functionality
