### ISSUE TITLE
Light theme: Icon for node reordering is invisible

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#2017]
### Describe the bug

When "light" theme is active, the icon for reordering nodes is invisible.

### Reproduce

-

### ZEUS version

v0.8.2

### Node interface

LND (REST)

### Network

Clearnet

### Device

Samsung Galaxy S20+

### Device operating system

Android 13

**Comment by kaloudis** [comment]
Thanks for reporting. https://github.com/ZeusLN/zeus/commit/e011622db3b5aba5bf9e19315c303bbc435bb439
