### ISSUE TITLE
Tooltip text hidden in Dark Theme mode

### ISSUE THREAD

**Issue by domohawk** [ZeusLN/zeus#2053]
### Describe the bug

With system in Dark Theme mode, the text in popup toolios (e.g. Advanced Settings > Lurker mode, clicking the {i}) becomes white and completely unreadable.

Turning off system Dark Theme the text is black and readable again. 

### Reproduce

With system in Dark Theme mode, the text in popup toolios (e.g. Advanced Settings > Lurker mode, clicking the {i}) becomes white and completely unreadable.

Turning off system Dark Theme the text is black and readable again. 

### ZEUS version

v0.8.2

### Node interface

Core Lightning (c-lightning-REST)

### Network

Clearnet

### Device

Pixel

### Device operating system

Android 14

**Comment by kaloudis** [comment]
Had seen this before but didn't realize what was causing this. We will fix this in `v0.8.3`

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/2057

**Comment by domohawk** [comment]
Wow thanks. They weren't kidding when they said this was the best supported LN manager.

**Comment by kaloudis** [comment]
Fix rolled out for testing in `v0.8.3-beta1`

**Comment by kaloudis** [comment]
Fix released in `v0.8.3`
