### ISSUE TITLE
LNDhub connected "node" opens always for key pad view

### ISSUE THREAD

**Issue by tlindi** [ZeusLN/zeus#2101]
### Describe the feature

Make settings option to select if user prefers UI to open to Balance or Keypad view, please.

I could not find such setting on 0.8.2.

**Comment by kaloudis** [comment]
This feature already exists under `Settings` > `Display` > `Default view`

**Comment by tlindi** [comment]
It changes all the nodes behavior. I was looking for setting for just some/one of nodes to view keypad by Default.

**Comment by kaloudis** [comment]
Not sure we want to add that complexity to the app. We would have to overhaul how all the settings work and surely there would be users who want the old behavior to remain.

**Comment by tlindi** [comment]
I see. No worries.
