### ISSUE TITLE
Adding "fund max" flag in flow of spending a selected on-chain UTXO to on-chain address.

### ISSUE THREAD

**Issue by expatri0tic** [ZeusLN/zeus#2106]
### Adding "fund max" flag in flow of spending a selected on-chain UTXO to on-chain address.

Not sure if this is an enhancement or feature.
Basically, sometimes I close channels and want to sweep those new UTXOs out of Zeus to an onchain wallet.
When I do this I've noticed a key feature is missing. 
A "fund max" option.

There is a sweep option, but this has the negative side-effect of combining all the UTXOs in your wallet. One may want to leave one UTXO behind to help with any on-chain miner fees needed in the closing and opening of channels. Plus, there's always a privacy implication with wanton UTXO combining.

My suggestion is that the work flow be as follows:
1. Hit send
2. Input bitcoin on-chain address
3. Select desired UTXO(s)
4. Select desired miner fee (sat/vB)
5. **[New] Hit fundmax flag**
6. Send entire UTXO to address minus fees

This would prevent the failing of the tx when the chosen send amount doesn't adequately account for miner fees. But sans a visible estimated miner fee (based on api call and tx size) for user to do their own calculation, they're left to trial and error. And unless they go down in increments of one sat, they're bound to end up with a dust UTXO in Zeus after the UTXO is spent and the miner is paid.

I'm aware that Zeus isn't meant to be an onchain wallet primarily. However, it is the case that onchain txs are sometimes needed to be made, and if it's going to be possible to select individual UTXOs (which could have been hidden from us), then we might as well have the ability to easily spend the entire UTXO without creating dust.

Thank you.

Willing to pay anyone 25k sats if they get this merged into Zeus.

Relevant conversations about this:
1. https://github.com/lightningnetwork/lnd/issues/6949
2. https://github.com/ZeusLN/zeus/issues/790

**Comment by kaloudis** [comment]
Added in v0.9.1
