### ISSUE TITLE
Add XAU + XAG exchange rates

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#2113]
![image](https://github.com/ZeusLN/zeus/assets/1878621/770810e4-9400-48eb-9395-c10ef19c3879)

**Comment by Ajeett01** [comment]
@kaloudis can you tell more about this issue. I am a new contributor here!

**Comment by shivamgupta2020** [comment]
Hi @kaloudis, I would like to contribute in this task.

**Comment by shivamgupta2020** [comment]
@kaloudis I have created a PR can u check it once?
