### ISSUE TITLE
Adding custom image to contact or node not possible with setting "Select node on startup"

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#2126]
### Describe the bug

We just fixed https://github.com/ZeusLN/zeus/issues/1880 with https://github.com/ZeusLN/zeus/pull/2122, but now https://github.com/ZeusLN/zeus/pull/2116 leads to Zeus displaying the node list when app was in background, so it will be impossible to add a custom image to a contact or node again.

### Reproduce

- go to Display settings and enable "Select node on startup"
- _Edit:_ go to Security settings and enable "Require login after app returns from background"
- go to node list -> gear icon of a node -> tap on the node image "+" icon -> tap on the "+" icon -> pick an image
--> when you come back from background, Zeus will display the node list and your image setting process is gone.

### ZEUS version

None

### Node interface

LND (REST)

### Network

Clearnet

### Device

Android Emulator Pixel 7 Pro

### Device operating system

Android 14

**Comment by kaloudis** [comment]
have you tested this with `https://github.com/ZeusLN/zeus/pull/2122` on top of it - it's not merged in yet

**Comment by kaloudis** [comment]
Nevermind -

I think this can be fixed on `views/Lockscreen.tsx:69` by changing the if to:
`if (SettingsStore.settings.selectNodeOnStartup && SettingsStore.initialStart) {`

**Comment by kaloudis** [comment]
@myxmaster I'm a bit perplexed here - can't recreate on iOS or Android on `master`

**Comment by kaloudis** [comment]
> Nevermind -
> 
> I think this can be fixed on `views/Lockscreen.tsx:69` by changing the if to: `if (SettingsStore.settings.selectNodeOnStartup && SettingsStore.initialStart) {`

@myxmaster - can you test to see if this will fix it? There may be an edge case where you go into this loop if you try to modify the image before loading a wallet first, but perhaps we also hide the gear icons on the initial load

**Comment by kaloudis** [comment]
`initialStart` is true by default, then is set to `false` when it hits the proceed block. This appears to work as a fix on my end:

```
proceed = () => {
        const { SettingsStore, navigation } = this.props;
        if (SettingsStore.settings.selectNodeOnStartup && SettingsStore.initialStart) {
            SettingsStore.setInitialStart(false);
            navigation.navigate('Nodes');
        } else {
            navigation.navigate('Wallet');
        }
    };

````

**Comment by kaloudis** [comment]
Fixed with https://github.com/ZeusLN/zeus/pull/2122/commits/d946b2dcefda59b60b2307b8e064c40b9a12dbb0
