### ISSUE TITLE
Embedded LND: make fee url configurable

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#2158]
We should also look at self-hosting our own instance https://github.com/LN-Zap/bitcoin-blended-fee-estimator

https://bitcoinchainfees.strike.me/v1/fee-estimates

**Comment by JavierRSobrino** [comment]
Yes, and you should run your own instance because the reliability of the feeurl is critical, as shown in this bug:

https://github.com/lightningnetwork/lnd/issues/8688#issuecomment-2077898327

**Comment by kaloudis** [comment]
v0.9.0 is out now with this functionality

https://github.com/ZeusLN/zeus/releases/tag/v0.9.0
