### ISSUE TITLE
Embedded node wallet.db got locked

### ISSUE THREAD

**Issue by Darth-Coin** [ZeusLN/zeus#2162]
### Describe the bug

BUG: I cannot make payments or receive payments.
Error: "Insufficient funds"
Logs says: "cannot find route, insufficient funds".
Once I click to pay the invoice, the error "Insufficient balance" come up instantly.

### Reproduce

The embedded node open normally, no issues with the connection. I always use good neutrino peers and carefully select them based on ping to be under 100ms. I have 4-5 peers in the list.

I have 3 channels: 1 to Olympus, 1 to Voltage Flow, 1 to Nerv all with more than enough liquidity in and out.

- I checked the channels and appear online. Some peers confirmed that they see my node online too.
- I tried to select a specific channel to send a payment, none of them worked.
- I checked in Settings - Node Info the status. All ok, synced to chain and to graph.
- I checked the logs and I found only few [ERR] - see below the logs.
All the rest of logs are [INF] regular gossip sync and neutrino sync with peers, that seems to be working fine. So I will not bother you posting them here, but if you need them I can provide full logs. The thing is that cannot capture them all at once, only truncated.
- I deleted the neutrino files and restarted the sync
- I cleared the app cache and restarted
- I reset the mission control Settings - Advanced - Pathfinding - reset payment routing. I also switched from bimodal to apriori.
- I compacted the LND database
- I start a rescan wallet
- I reset various times the Express Graph Sync
- I tried various neutrino peers
- I check the number of zombies, is always under a normal level between 150-300
- I increased the fees to even 10%
- I can generate onchain addresses just fine, taproot and segwit

The LN graph looks like this:
![image](https://github.com/ZeusLN/zeus/assets/56997124/2cb35f00-f5b1-4d0b-9b0c-f2f3d2c95fb0)

And LN channels looks like this (online all and enough liquidity)
![image](https://github.com/ZeusLN/zeus/assets/56997124/5fe78514-bd55-4a7d-b0d1-16bd6f137cea)

If you need any further logs, explanations, testing specific versions etc I am willing to help.
I could restore this node into another Zeus instance, I have the backups, but I think is more important that we can find what could trigger this behavior so other users would not have the same issue.
For me this is a testing Zeus instance so is not a problem right now that I cannot make payments, I have other wallets available.

### ZEUS version

v0.8.4

### Node interface

Embedded LND

### Network

Clearnet

### Device

Motorola G9 plus

### Device operating system

Android 12 / Lineage 19

### Log output

```shell
[ERR] DISC: Update edge for short_chan_id(871482811880767488) got: unable to add channel: edge not found
[ERR] CRTR: unable to add channel: edge not found
[ERR] LNWL: Failed to open database: timeout
[ERR] RPCS: [/lnrpc.WalletUnlocker/UnlockWallet]: timeout
[ERR] RPCS: [/lnrpc.Lightning/QueryRoutes]: insufficient local balance
[WRN] CRTR: Failed to find route for payment 213b274930f6ce5babf91780fb541dcf863bd3c2ae7257b0b393ae001b3fe526: insufficient local balance
[ERR] CRTR: Payment 213b274930f6ce5babf91780fb541dcf863bd3c2ae7257b0b393ae001b3fe526 failed: insufficient_balance
```

**Comment by djkazic** [comment]
Sounds like channel.db corruption.

https://github.com/raspiblitz/raspiblitz/issues/2363

**Comment by djkazic** [comment]
Debug logs would also be helpful.

**Comment by Darth-Coin** [comment]
I think we can close this one. Let's consider it that was a database corruption due to my last intents to coop close the channels and I got error.
So I reinstalled Zeus and initiated the recovery process of the funds from channels.
