### ISSUE TITLE
Allow user to pick manual fee even with "Enable Mempool.space fee suggestions" configured

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#2168]
### Describe your enhancement idea

In case there is a problem with mempool.space suggesting fees, you should be able to override it manually. Right now the only solution is to cancle the payment, disable the fee suggestions in settings and start over.

**Comment by kaloudis** [comment]
Press it, there is a manual input field

**Comment by kaloudis** [comment]
Good catch, @myxmaster. Let's definitely fix this for v0.9.0
