### ISSUE TITLE
Knox Enrollment Service camera issue

### ISSUE THREAD

**Issue by austrocoin** [ZeusLN/zeus#217]
When the app open the cam there is a pop-up:

"Knox Enrollment Service
Sorry, the Android camera encountered a problem. You may need to restart."

Cam work perfect in all other apps - restart help nothing.
Thanks

**Comment by kaloudis** [comment]
@swissnode is also experiencing this, you're not alone. I suspect it has something to do with bumping the Android SDK up to 28 but I'm still investigating.

**Comment by austrocoin** [comment]
Great - sadly I can not give more info as there is not more given except this error popup. But mobile is on latest Android incl. update if it help.

**Comment by enoughofme** [comment]
I'm having same issue, first time trying Zeus.

It's giving me the error 

'**In4m** (another app I have installed)
Sorry, the Android camera encountered a problem. You may need to restart the device.'

**Comment by davterra** [comment]
Same problem for me. Using v0.2.1 on Samsung 10

**Comment by kaloudis** [comment]
Samsung users: if you have problems with your camera try giving the Knox Enrollment Service permission to your camera @davterra @enoughofme @austrocoin

**Comment by darioAnongba** [comment]
Hi, I'm experiencing the same issue with Samsung s20. Sadly Zeus is the only wallet that supports Tor at the moment so this issue seems to prevent the Bitcoin community from easily connecting to a Tor node on a mobile app

**Comment by davterra** [comment]
> Hi, I'm experiencing the same issue with Samsung s20. Sadly Zeus is the only wallet that supports Tor at the moment so this issue seems to prevent the Bitcoin community from easily connecting to a Tor node on a mobile app

If your Samsung phone includes a "hidden folder" that you can activate, Zeus and the qr reader work fine when installed into that folder.

**Comment by C00P3RR** [comment]
I've been experiencing this problem too, however I just gave "Knox Enrollment Service" allowed Camera permissions and did a restart and now it works on a Samsung S20. No idea if this helps but it's worth a try?

**Comment by backtheryophag** [comment]
search "knox" on/in play market, download his qrcodescanner. sorry, i'm russian. eanglish don't understand

**Comment by ZeusLN** [comment]
This should be fixed with the new camera introduced in `v0.6.0-alpha1`
