### ISSUE TITLE
Channels list is empty

### ISSUE THREAD

**Issue by dennisreimann** [ZeusLN/zeus#2182]
### Describe the bug

Same as #1253, but with current versions (Zeus v0.8.4 and c-lightning-REST v0.10.7)

### Reproduce

Reproduce the bug step by step.

### ZEUS version

v0.8.4

### Node interface

Core Lightning (c-lightning-REST)

### Network

Clearnet

### Device

Android

### Device operating system

GrapheneOS

**Comment by kaloudis** [comment]
Fixed in v0.8.5

**Comment by dennisreimann** [comment]
Yep, can confirm it works again! Thanks a lot :)
