### ISSUE TITLE
Inbound routing fees

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#2185]
As of LND v0.18, you have the ability to set inbound fees on your channels. Let's ensure we cover this in our UI for all LND interfaces.

**Comment by Liongrass** [comment]
Tricky because they're actually negative inbound fees (discounts). The discussion could also already consider what the UI might look like with positive inbound fees, and negative outbound fees!

**Comment by twofaktor** [comment]
https://github.com/lightningnetwork/lnd/releases/tag/v0.18.0-beta

**Comment by kaloudis** [comment]
`UpdateChannelPolicy` has a dedicated parameter for `inbound_fee`

https://lightning.engineering/api-docs/api/lnd/lightning/update-channel-policy

**Comment by twofaktor** [comment]
https://docs.lightning.engineering/lightning-network-tools/lnd/inbound-channel-fees
