### ISSUE TITLE
Node Configuration: some buttons should be labels

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#2189]
### Describe your enhancement idea

In the Node Configuration screen there are `NODE CONFIG SAVED` and `NODE ACTIVE` buttons.

When you click `NODE CONFIG SAVED`, it saves the node config (although nothing was changed).
When you click `NODE ACTIVE`, it closes the settings.
-> Both doesn't make sense really/is not intuitive behaviour. Both buttons are just information, so no onPress action is needed and therefore they should be changed into labels.

**Comment by kaloudis** [comment]
Completely agree.

`NODE CONFIG SAVED` should never be displayed. We should just hide it if there are no changes.

`NODE ACTIVE` should be a badge of sorts
