### ISSUE TITLE
Opening a lightning channel

### ISSUE THREAD

**Issue by DeWe838** [ZeusLN/zeus#2194]
### Describe the bug

A bug happened! Yesterday I opened a lightning channel with my onchain liquidity. The onchain Tx went throug, but the channel is still on pending status.
The tx is: 12635e5bfb80c6fd99dd34d8998ac2b932310c1d9f2e9b918e927925e57b9c89
![photo_2024-05-20_13-37-54](https://github.com/ZeusLN/zeus/assets/157794103/d295b500-4866-466b-9552-33390a66c807)
![photo_2024-05-20_13-37-47](https://github.com/ZeusLN/zeus/assets/157794103/8f0f6ae2-e0c5-4997-afd5-d4f3241066cb)
![photo_2024-05-20_13-37-40](https://github.com/ZeusLN/zeus/assets/157794103/dd3f0e43-ce31-447b-95cc-8eaca26c57f1)
![photo_2024-05-20_13-37-26](https://github.com/ZeusLN/zeus/assets/157794103/e2d16530-02b8-4c58-88a1-6bf623c99cc2)

### Reproduce

Reproduce the bug step by step.

### ZEUS version

v0.8.4

### Node interface

Embedded LND

### Network

Clearnet

### Device

Xiaomi 9 Pro

### Device operating system

Android 12 SKQ 1.211019.001

**Comment by kaloudis** [comment]
Seems like you may be having issues synchronizing to chain properly.

You should review your neutrino peer list under Settings > Embedded Node > Peers > Neutrino, and hit the hourglass icon to test ping times for each. Over 200ms causes issues and you may want to delete them. Once you do that, restart the app.

Hopefully this addresses your issue.

**Comment by DeWe838** [comment]
Thx for your help Evan. It worked. Will zap you a few sats for your help. V4VOne more question if I open another channel, will it be 2 then or 1 bigger channel then, like in phoenix? Brgds--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 20.05.24, 17:20 schrieb Evan Kaloudis ***@***.***>:

   
  Seems like you may be having issues synchronizing to chain properly. 
  You should review your neutrino peer list under Settings > Embedded Node > Peers > Neutrino, and hit the hourglass icon to test ping times for each. Over 200ms causes issues and you may want to delete them. Once you do that, restart the app. 
  Hopefully this addresses your issue.

**Comment by kaloudis** [comment]
> Thx for your help Evan. It worked. Will zap you a few sats for your help. V4VOne more question if I open another channel, will it be 2 then or 1 bigger channel then, like in phoenix? Brgds--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 20.05.24, 17:20 schrieb Evan Kaloudis ***@***.***>: Seems like you may be having issues synchronizing to chain properly. You should review your neutrino peer list under Settings > Embedded Node > Peers > Neutrino, and hit the hourglass icon to test ping times for each. Over 200ms causes issues and you may want to delete them. Once you do that, restart the app. Hopefully this addresses your issue. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

It will be a second channel. We do not support splicing, like Phoenix does, yet.

**Comment by DeWe838** [comment]
Ok. Thx. Just sent 5000 sats to your nostr address.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 20.05.24, 18:10 schrieb Evan Kaloudis ***@***.***>:

   
   
   Thx for your help Evan. It worked. Will zap you a few sats for your help. V4VOne more question if I open another channel, will it be 2 then or 1 bigger channel then, like in phoenix? Brgds--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 20.05.24, 17:20 schrieb Evan Kaloudis @.>: Seems like you may be having issues synchronizing to chain properly. You should review your neutrino peer list under Settings > Embedded Node > Peers > Neutrino, and hit the hourglass icon to test ping times for each. Over 200ms causes issues and you may want to delete them. Once you do that, restart the app. Hopefully this addresses your issue. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> 
   
  It will be a second channel. We do not support splicing, like Phoenix does, yet.
