### ISSUE TITLE
Feature: Remove old unpaid invoices

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#22]

**Comment by kaloudis** [comment]
Will not fix as this is not supported in the APIs. If you want this functionality please file an issue in the lnd and c-lightning repos

**Comment by fiatjaf** [comment]
c-lightning by default removes unpaid expired invoices every day.

**Comment by kaloudis** [comment]
https://github.com/lightningnetwork/lnd/issue/1404

**Comment by ZeusLN** [comment]
Will leave this to the individual implementations.
