### ISSUE TITLE
POS: Product price has leading zero

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#2200]
### Describe your enhancement idea

When you create a product the price input forces a zero, it also stays as leading zero when you enter an amount.
-> Leading zeros should automatically be deleted.

![grafik](https://github.com/ZeusLN/zeus/assets/77545287/2337bbe2-e5a4-4d4b-a7c8-7e1620aab516)

**Comment by kaloudis** [comment]
I believe this has been fixed with the PR listed above
