### ISSUE TITLE
UI: Rework settings/menu

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#2203]
### Describe your enhancement idea

Right now everything is in Settings although there is also stuff which clearly is not settings related, like `Sign or verify message`, `Currency Converter`, `Point of Sale` etc.

I suggest we make a general menu with
- Settings
- Tools
- About

Mockup:
![grafik](https://github.com/ZeusLN/zeus/assets/77545287/20d10405-33a8-4e8e-b058-006b4e22230c)

@kaloudis if you agree, I'll take a closer look and make a proposal which stuff should go where.

**Comment by kaloudis** [comment]
Almost feel like tools could be in the right of the header.

I like the concept here though - but a lot of whitespace on this new proposed view
