### ISSUE TITLE
Zero Balance for On-Chain c-lightning-REST is always 0 (0.9.0-alpha5)

### ISSUE THREAD

**Issue by newtonick** [ZeusLN/zeus#2222]
### Describe the bug

c-lightning-REST always shows a balance of 0 for CLN node with 1 UTXO. I am able to see the On-chain balance in 0.8.4.

### Reproduce

I've deleted the app and reinstalled. Connect to c-lightning-REST with On-chain balance. CLN version v23.11.2.

### ZEUS version

v0.9.0

### Node interface

Core Lightning (c-lightning-REST)

### Network

Clearnet

### Device

iPhone 13 mini

### Device operating system

17.4.1

**Comment by newtonick** [comment]
I forgot to mention. I can see the UTXOs in Zeus even though the balance is 0. I can see the On-chain balance in RTL.

**Comment by kaloudis** [comment]
can you provide the c-lightning-REST version?

**Comment by newtonick** [comment]
> can you provide the c-lightning-REST version?

v0.10.7

**Comment by kaloudis** [comment]
Fix will roll out with `alpha6` https://github.com/ZeusLN/zeus/commit/9e5e3cad9f1029d899ba0443349e04c275e956c3

**Comment by newtonick** [comment]
Fixed
