### ISSUE TITLE
Channel list went to zero on Alpha7 CLN v24.05

### ISSUE THREAD

**Issue by sat-hoarder** [ZeusLN/zeus#2225]
### Describe the bug

I updated CLN to v24.05 (very new) and channel list went to zero.  I'm using Zeus Alpha 7 and the channels previously showed on CLN v24.02.02  

c-lightning REST v0.10.7

### Reproduce

Updating CLN to newest version 24.05 creates an error in the display of the node's channels and 0 show.

### ZEUS version

v0.9.0

### Node interface

Core Lightning (c-lightning-REST)

### Network

Clearnet

### Device

Samsung Flip 5 

### Device operating system

Android 14

**Comment by kaloudis** [comment]
No issues with CLN `v23.05` and c-lightning-REST `v0.10.7` interestingly

About to upgrade

**Comment by matevz** [comment]
For me, the Channels screen was also empty on CLN 24.02.2. And it is still empty when upgraded to 24.05. So it may not be only 24.05-related.

**Comment by bitcoinlizard** [comment]
Please see an issue I created with the c-lightning-REST developer and their response:
https://github.com/Ride-The-Lightning/c-lightning-REST/issues/214

**Comment by BitcoinQnA** [comment]
Confirming I am also seeing this on CLN 24.05 (start9)

**Comment by kaloudis** [comment]
Fix will be in the next build

**Comment by newtonick** [comment]
I can confirm this is fixed in v0.9.0-alpha12

**Comment by sat-hoarder** [comment]
Thank you so much!
