### ISSUE TITLE
Connect Zeus to Phoenixd server

### ISSUE THREAD

**Issue by EdoardoSnodato** [ZeusLN/zeus#2262]
### Describe the feature

Future release, is possible connect Zeus to phoenixd ?

https://phoenix.acinq.co/server

**Comment by kaloudis** [comment]
You can use it as the backend for LNbits and from there install the LNDHub plugin to connect to with Zeus

**Comment by EdoardoSnodato** [comment]
> You can use it as the backend for LNbits and from there install the LNDHub plugin to connect to with Zeus

But i don't have Public IP

**Comment by Darth-Coin** [comment]
> But i don't have Public IP

Use a VPS for your public lnbits. See mroe guides here: https://github.com/lnbits/lnbits/wiki/Tutorials-and-Guides

**Comment by kaloudis** [comment]
We're not going to support interfaces that have explicit vendor lock-in like this
