### ISSUE TITLE
The last item on the list of connected nodes sometimes shows up incorrectly

### ISSUE THREAD

**Issue by supertestnet** [ZeusLN/zeus#2271]
### Describe the bug

This copy of Zeus Wallet is used for testing various node features and consequently it is connected to a dozen or so nodes. I have to scroll to see them all, and when I scroll all the way to the bottom, this is what I see:

![bug-on-zeus](https://github.com/ZeusLN/zeus/assets/58400631/62f02bf8-a2c9-4fb4-85d0-27ff0d533a6e)

I cannot "scroll further" so the last node on my list is just kinda partially cut off.

### Reproduce

Step 1. Connect to a bunch of node backends

Step 2. Scroll to the bottom

Step 3. Weep, thou maker, and cry aloud, for though thy kingdom be vast as the plains of Moab, thou shalt never find its borders

### ZEUS version

v0.8.4

### Node interface

Multiple (specified in comments)

### Network

Tor

### Device

Google Pixel 6A

### Device operating system

Android 14

**Comment by kaloudis** [comment]
This is fixed in the v0.9.0 alphas

https://github.com/ZeusLN/zeus/commit/908e6db843be07970408da4186ea411722298649

**Comment by kaloudis** [comment]
fix in v0.9.0, out now
