### ISSUE TITLE
The 0.9.0-alpha - LND v0.18.0 - a recovery is not possible anymore

### ISSUE THREAD

**Issue by Perlover** [ZeusLN/zeus#2287]
### Describe the bug

This problem is not directly related to Zeus 0.9.*. But, since it has LND version 0.18.0 inside, I want to warn you about the potential risk that in LND 0.18, from my personal experience, recovery from seed + SCB is not functional. I've tried twice to restore funds - it didn't work. I was able to do it when I manually updated LND to version 0.17.5 and did a restore.

I suggest you to test the recovery of funds on Zeus 0.9.0-alpa11 before someone else encounters this problem personally. My experience is described in more detail here: https://github.com/lightningnetwork/lnd/issues/8880

### Reproduce

1) Create wallet, open channels, save SCB file. In addition to funds in channels, it is better to have funds on onchain wallet from LND.
2) Start a recovery procedure:
3) Create new .lnd empty directory with lnd.conf
4) Starting LND
5) I specified the password for the wallet, then specified the old seed and cipher seed phrase.
6)  Waiting for LND to synchronise. But it shows `walletbalance` completely zero, and also does not see the first top-up transactions to the node's wallet (lncli listunspent). 
7) `lncli restorechanbackup --multi_file /path/to/static.channel` will not help because a LND wallet doesn't see onchain transactions

### ZEUS version

v0.9.0

### Node interface

Embedded LND

### Network

Clearnet

### Device

Any Android and iPhone

### Device operating system

Any Android and iPhone OSes

**Comment by kaloudis** [comment]
Do you hit any errors running `lncli restorechanbackup`?

Also, note that the block sync process is not quite the same as the rescan recovery process. LND logs should give you insight on the latter.

**Comment by kaloudis** [comment]
When attempting to restore in Zeus v0.9 did you allow the Rescan progress bar to reach completion?

![Screenshot_1721011843](https://github.com/user-attachments/assets/7b7b6fc2-0bd8-4e5e-bfd6-8c29d708f47a)

**Comment by Perlover** [comment]
I apologize. I'm now running LND 0.18 recovery again and now I'm not observing any problems - LND wallet has successfully started finding all wallet transactions. However, my node has already restored the funds in the channels. Anyway, I don't know now if the problem was on my side or a bug that I won't be able to catch again. I'm closing the ticket.

**Comment by Perlover** [comment]
> Do you hit any errors running `lncli restorechanbackup`?

I didn't get to that at the time, as I was doing the first phase at the time - scanning and finding LND wallet transactions after entering seed. This command you are asking about runs after LND runs after the first run with a rescan of all found UTXOs of its wallet.

**Comment by Perlover** [comment]
> When attempting to restore in Zeus v0.9 did you allow the Rescan progress bar to reach completion?

The thing is, I was running LND on Linux. And I had problems there. Then I found out that LND 0.18 is available in Zeus 0.9 and wrote about it here.
