### ISSUE TITLE
Unable to exit UTXO selection screen when opening a channel

### ISSUE THREAD

**Issue by sha-265** [ZeusLN/zeus#2302]
### Describe the bug

When going to the UTXO selection screen in open channel screen, I can't exit the UTXO selection screen. The only way is to close the app. Maybe it's related to the fact that there is no UTXO to select in my case.

![image](https://github.com/user-attachments/assets/05e410ba-fee3-48ea-a0be-7ef704e28147)

### Reproduce

1. Create LND embedded node.
2. Go to open channel screen.
3. Go to UTXO selection screen.
4. Try to exit UTXO screen.

### ZEUS version

v0.8.5

### Node interface

Embedded LND

### Network

Clearnet

### Device

Pixel 4a

### Device operating system

Android 13

**Comment by kaloudis** [comment]
I believe this is patched in v0.9.0

**Comment by kaloudis** [comment]
Confirmed. No longer an issue in the v0.9.0 betas

**Comment by kaloudis** [comment]
v0.9.0 is out now with this functionality

https://github.com/ZeusLN/zeus/releases/tag/v0.9.0
