### ISSUE TITLE
lnd: close channel doesn't work on Inactive channels

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#231]
force close flag needed?

**Comment by DarkWingMcQuack** [comment]
when i try to close the inactive channels with lncli, it requires me to use the `--force` flag because the other party is not reachable

**Comment by kaloudis** [comment]
fixed in https://github.com/ZeusLN/zeus/pull/262

**Comment by ZeusLN** [comment]
Fixed in v0.2.2
