### ISSUE TITLE
Feature req: lnurl-auth

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#233]

**Comment by kaloudis** [comment]
https://github.com/lightningnetwork/lnd/pull/4495

**Comment by pseudozach** [comment]
I think this can be closed now :)

**Comment by theborakompanioni** [comment]
@pseudozach Why can this be closed?
I don't know why but Zeus is in the [awesome-lnurl](https://github.com/fiatjaf/awesome-lnurl#wallets) wallet list with a checkmark on lnurl-auth. But when I scan an lnurl-auth encoded link it displays an error message saying:
```
Error: Unsupported lnurl type: login
```

Am I missing something?
I am using v0.5.2.

**Comment by pseudozach** [comment]
@theborakompanioni can you please share which website you're trying on?

**Comment by theborakompanioni** [comment]
@pseudozach Ah, thanks - sorry, I was distracted by the checkmark in [awesome-lnurl](https://github.com/fiatjaf/awesome-lnurl#wallets) but now I see it has just been added recently. 
I try with multiple wallets on multiple websites - consider me trying _all_ wallets and _all_ websites.

Thank you! I am looking forward to testing the next version!

**Comment by pseudozach** [comment]
@theborakompanioni yeah maybe I got over excited and announced this is ready before release sorry about that. let us know if you find any services not working with Zeus, I'd like to test myself as well.
