### ISSUE TITLE
No way to add a description on a per-invoice basis

### ISSUE THREAD

**Issue by chrisguida** [ZeusLN/zeus#2336]
### Describe your enhancement idea

There needs to be a way to encode a description into the BOLT11! Making every invoice descriptionless makes it hard to track which payments are for what.

cc @niftynei

**Comment by kaloudis** [comment]
You're not allowed to add memos to invoices that are to be wrapped by the LSP for privacy purposes. If you disable invoice wrapping you can add a memo.

Furthermore, you can save a note locally to an invoice (or tx or outgoing payment) from the Activity view - wrapped or not.

**Comment by chrisguida** [comment]
This is not an LSP node, it's a CLN node

**Comment by kaloudis** [comment]
Found a regression in our LSP check code. Fix will be out in our next build. Thanks for reporting.

https://github.com/ZeusLN/zeus/commit/6dc4efe34c903967684805c7410e970273b12201
