### ISSUE TITLE
 Transaction lost (can't find address anymore in sparrow)

### ISSUE THREAD

**Issue by redOz92** [ZeusLN/zeus#2340]
Hello,

I've got a strange issue.
I transferred 1.5M sats from **Zeus Wallet** to Sparrow Wallet with the QR code on Sparrow but I can't find the address anymore in Sparrow and also I didn't receive anything. If you scan the QR code could Zeus make a mistake in scanning it?

https://mempool.space/tx/747063b45480f62f7a626cf19568077504d7df65f39a4d9530eaca34f46fe1f2?mode=details
https://mempool.space/address/bc1q0rx2d4rd4u3u4nwjdvjpduummu9qk2y4z3ta5c

This is my transaction but can't find it anymore.
I'm pretty sure I saw the transaction pop up on sparrow when it was send..

**Comment by kaloudis** [comment]
Zeus is not at fault for issues with receiving wallets. Please verify you have ownership of an address before you send.

If anything this issue should be opened in the Sparrow repo.
