### ISSUE TITLE
LNDHub: Custodial Warning: add option to dismiss

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#2344]
Many users have been complaining about the LNDHub warning we've added to the wallet header in the app.

On the warning page, let's give the users the option to dismiss the warning. In order to stifle bad actors, let's make the users very explicitly opt out with a list of checkboxes to make sure they understand the risks in dismissing the warning.

**Comment by newtonick** [comment]
+1 on this option.

I would like the option to disable the LNDHub custodial warning for LNDHub wallet/accounts I personally have custody of. I'm willing to jump through many hoops to make it harder for bad actors to take advantage of zeus users.

**Comment by kaloudis** [comment]
First draft of the checkbox text:

- [ ] `I know that I don't have custody of the funds in this wallet without the 12 or 24 word seed phrase`
- [ ] `I know that an LNDHub account password is not the same as a seed phrase`
- [ ] `I either set up this connection myself or I trust the person who set it up`
- [ ] `I'm not just lying to get this over with`
