### ISSUE TITLE
Remove the "Custodial wallet" badge for connecting an Alby account

### ISSUE THREAD

**Issue by MoritzKa** [ZeusLN/zeus#2384]
Alby is not offering managed accounts anymore to users. The LNDhub connection to Zeus is working with Alby Hubs, the new self-custodial wallet.

![chrome_mYlsygmzBu](https://github.com/user-attachments/assets/9232e9aa-4ecb-4e02-a146-cdd994e140b3)

**Comment by kaloudis** [comment]
Please see https://github.com/ZeusLN/zeus/issues/2344

**Comment by kaloudis** [comment]
Ability to dismiss added in `v0.9.1` - beta1 is now available for testing here: https://github.com/ZeusLN/zeus/releases/tag/v0.9.1-beta1

Please check it out if you have a moment. Thanks!

**Comment by kaloudis** [comment]
v0.9.1 is now available with the fix: https://github.com/ZeusLN/zeus/releases/tag/v0.9.1
