### ISSUE TITLE
Missing account

### ISSUE THREAD

**Issue by Retropex** [ZeusLN/zeus#2389]
### Describe the bug

After importing my seed signer account, Ind seems to have forget my account:

```
lnd[1832]: 2024-08-31 23:50:04.857 [ERR] RPCS: [/lnrpc.Lightning/NewAddress]: account name 'SeedSigner' not found
```

I'm not sure if this was due to a restart of lnd.

![image](https://github.com/user-attachments/assets/2efe7acc-d7fe-48f8-9581-a7e4c0f9196c)

### Reproduce

1. Import an account (seed signer in my case)
2. Tap on receive

### ZEUS version

v0.9.0

### Node interface

LND (REST)

### Network

Clearnet

### Device

iPhone 13 Pro

### Device operating system

iOS 17.6.1

**Comment by kaloudis** [comment]
So it sounds like the account is still being returned via `ListAccounts` but is throwing an error when attempting to create an address for the account.

Could you verify by running commands for these actions via CLI? We might have to file a bug upstream to LND.

**Comment by Retropex** [comment]
my seed signer account is effectively here

```
xxx@xxx~$ lncli walletbalance
{
    "total_balance":  "xxx",
    "confirmed_balance":  "xxx",
    "unconfirmed_balance":  "xxx",
    "locked_balance":  "xxx",
    "reserved_balance_anchor_chan":  "xxx",
    "account_balance":  {
        "SeedSigner":  {
            "confirmed_balance":  "xxx",
            "unconfirmed_balance":  "xxx"
        },
        "default":  {
            "confirmed_balance":  "xxx",
            "unconfirmed_balance":  "xxx"
        }
    }
}
```

**Comment by Retropex** [comment]
Found the problem, it’s was because i have changed the default address type to taproot.
