### ISSUE TITLE
Allow signing messages with BOLT12 address

### ISSUE THREAD

**Issue by mateuszmp** [ZeusLN/zeus#2391]
### Describe the feature

Some services require you sign a cryptographic message using your human readable BOLT12 address. I can generate a Lightning address in Zeus (connected to LND) and the address is of type name@zeuspay.com, however there is no way for me to sign such a cryptographic message using this zeuspay address.

**Comment by kaloudis** [comment]
I think you're conflating some things.

zeuspay.com lightning addresses are LNURL powered and use BOLT11. They're only supported with our embedded wallet and remote LND interfaces.

we also support BIP-353, BOLT12 lightning addresses powered by our friends at Twelve.cash for remote Core Lightning nodes.

Both implementations can sign messages under `Menu` > `Tools` > `Sign/verify messages`
