### ISSUE TITLE
When a payment fails, make it easier to copy the invoice

### ISSUE THREAD

**Issue by Sjors** [ZeusLN/zeus#2404]
### Describe the feature

Currently with CLN I often get a network timeout. Although this doesn't mean the payment failed (CLN's timeout is slightly longer), I would still like to be able to copy the invoice and try it in some other client.

This is especially useful in Nostr apps. E.g. Damus will open Zeus when you zap someone, but it never displays an invoice.

Workaround is to swipe left (on iOs) after a failure which takes you back to the "pay this invoice" page. Where you then click on the QR code and find the copy to clipboard option.

**Comment by kaloudis** [comment]
Should be easier with the addition of https://github.com/ZeusLN/zeus/pull/2381 - which will make its way into v0.9.1

**Comment by kaloudis** [comment]
The above PR is included in `v0.9.1` - beta1 is now available for testing here: https://github.com/ZeusLN/zeus/releases/tag/v0.9.1-beta1

Please check it out if you have a moment. Thanks!

**Comment by kaloudis** [comment]
v0.9.1 is now available with the fix: https://github.com/ZeusLN/zeus/releases/tag/v0.9.1
