### ISSUE TITLE
Unnecessary screen rendering when picking a contact to send to

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#2421]
### Describe your enhancement idea

Steps to reproduce:
Swipeable row -> Send -> Contact icon -> pick a contact (not one with multiple addresses)
--> Zeus will shortly display the contact detail view, then automatically proceed to Send, and eventually LnurlPay screen (or whatever makes sense, decided by handleAnything). The unnecessary contact detail view is visible even on the phone, where performance is much better than on an emulator.

In case a contact has multiple addresses, the contact detail view should of course be displayed so the user can pick where to send (ln address, BOLT 12 address, pubkey, whatever), but if there are no multiple addresses, this can be skipped which will lead to noticable better performance.

**Comment by shubhamkmr04** [comment]
I can't reproduce this issue
