### ISSUE TITLE
BIP-21 URI with bolt12 is ignored, e.g. bitcoin:?lno=lno1p... 

### ISSUE THREAD

**Issue by Sjors** [ZeusLN/zeus#2433]
### Describe the bug

If you click on a link with bolt12 offer in the form of bitcoin:?lno=lno1pg on iOs it opens Zeus, but then nothing happens.

This link format is used by e.g. https://satsto.me and afaik recommended by BIP-353.

### Reproduce

You can try this: https://satsto.me/sjors@sprovoost.nl

I'm CLNRest, but the dropdown below doesn't have it yet.

### ZEUS version

v0.9.0

### Node interface

Core Lightning (c-lightning-REST)

### Network

Clearnet

### Device

iPhone 15

### Device operating system

iOs 18

**Comment by kaloudis** [comment]
v0.9.2-beta1 is now available for testing with support for this. Hope you try it out!

**Comment by Sjors** [comment]
Works!
