### ISSUE TITLE
Payment workflow does not retain currency unit state 

### ISSUE THREAD

**Issue by luisschwab** [ZeusLN/zeus#2443]
When making a payment, the workflow does not retain state about the selected currency unit.

For example: On the main screen, I select to pay 10 USD. In the confirm payment screen, I am promped to make a payment of 10 sats. 

It should retain the selected unit.

Main screen (USD):
![photo_5170640819496005786_y](https://github.com/user-attachments/assets/fda6c891-5740-4540-801b-e70a73047367)

Confirm payment screen (sats):
![photo_5170640819496005787_y](https://github.com/user-attachments/assets/ec635f9f-1582-4011-aa6e-a175dca7a474)

version: 0.9.0
OS: android

**Comment by kaloudis** [comment]
Which backend interface are you using?

**Comment by luisschwab** [comment]
LND (REST)

**Comment by kaloudis** [comment]
Appears to only affect LNURL flows

https://github.com/ZeusLN/zeus/blob/master/views/LnurlPay/LnurlPay.tsx#L75:L81

**Comment by kaloudis** [comment]
v0.9.2-beta1 is now available for testing with a fix for this. Hope you try it out!

**Comment by kaloudis** [comment]
@luisschwab this should be addressed in v0.9.2 which is out now. Please reopen the issue if you continue to experience this. Thank you!
