### ISSUE TITLE
Display Not Scrolling

### ISSUE THREAD

**Issue by mjlamb** [ZeusLN/zeus#245]
Node configuration / settings screen, see attached, does not display full screen and is cut off at the bottom. Similar to Issue #168 which were fixed in v0.2.1
There is a green button hidden in screen shot.

![Screenshot_20200215-093305](https://user-images.githubusercontent.com/2274034/74565818-f2017980-4fd6-11ea-895e-ce2ec4f32951.jpg)

Expected behavior
To see all screens and able to scroll if more below.
There is a green button hidden in screen shot.

Screenshots
OS: Android
Device: Android
Zeus Version v0.2.1

**Comment by kaloudis** [comment]
Thanks for the report. Will have a fix in the next release.

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/263

**Comment by ZeusLN** [comment]
Fixed in v0.2.2

**Comment by mjlamb** [comment]
Tested with release v0.2.2 and confirmed working. Great work guys!
