### ISSUE TITLE
LNURL-Pay: Tor host: "Could not parse lnurl params"

### ISSUE THREAD

**Issue by 21M4TW** [ZeusLN/zeus#2458]
I am trying to pay to a LNURL generated by LNbits with Zeus, but I get the error "Could not parse lnurl params" right away after scanning the QR code. My LNURL decodes to an onion URL which has the format:
http://abc...xyz.onion:5123/lnurlp/Xxxx

I verified that the URL does not get contacted using tcpdump on the local interface (where the Tor service gets redirected to). Does Zeus support onion LNURLs and custom ports?

Thanks!

**Comment by kaloudis** [comment]
@21M4TW the LNURL querying does not use Tor by default. You should be able to access the endpoint if you pair ZEUS with a Tor networking app like Orbot.

**Comment by 21M4TW** [comment]
> @21M4TW the LNURL querying does not use Tor by default. You should be able to access the endpoint if you pair ZEUS with a Tor networking app like Orbot.

I already had Zeus selected in the list of apps for Orbot. Did you mean something else by "if you pair ZEUS with a Tor networking app like Orbot"?

**Comment by kaloudis** [comment]
Could be your Tor circuit, or a constraint of the `js-lnurl` library. Need to investigate if it's the latter

**Comment by 21M4TW** [comment]
> Could be your Tor circuit, or a constraint of the `js-lnurl` library. Need to investigate if it's the latter

Ok thanks. I did try with two different Android phones that use a different version of Orbot, one phone with the regular Android and another one with LineageOS. Got the same error from both phones. The error appears without any perceivable delay after scanning the QR code (<0.1 second for sure), so I don't think there is any attempt to resolve the host.

**Comment by remcoros** [comment]
@kaloudis looks like js-lnurl does not parse parse http .onion urls correctly: https://github.com/nbd-wtf/js-lnurl/blob/master/src/helpers/decodelnurl.ts#L10

**Comment by kaloudis** [comment]
> @kaloudis looks like js-lnurl does not parse parse http .onion urls correctly: https://github.com/nbd-wtf/js-lnurl/blob/master/src/helpers/decodelnurl.ts#L10

Not 100% sure on this yet. There seems to be some effort to handle onions later in the file https://github.com/nbd-wtf/js-lnurl/blob/master/src/helpers/decodelnurl.ts#L21

**Comment by 21M4TW** [comment]
Ok, so it turns out that Orbot's transparent VPN does not work on Android when another VPN is used at the same time, and I think this was the issue I was having. Multiple VPNs are possible with rooted devices. It is unfortunate that Orbot does not detect the issue and warn the user about it.
