### ISSUE TITLE
Tor LND node "active" but no balance, payments etc shown

### ISSUE THREAD

**Issue by AbelLykens** [ZeusLN/zeus#246]
**Describe the bug**
I _seem_ to be able to add my (TOR) lnd node to Zeus, but Zeus does not show balances (does not seem to get data from my lnd node).

**To Reproduce**
* Set up system:
```
# grep -E 'tlsextra|rpclist' .lnd/lnd.conf | grep -Ev '^;'
tlsextradomain=3mbmmlopuelmnajf.onion
rpclisten=0.0.0.0:10009
# tail /etc/tor/torrc 
HiddenServiceDir /var/lib/tor/lnd_api/
HiddenServiceVersion 2
HiddenServiceAuthorizeClient stealth pocodroid
HiddenServicePort 10009 127.0.0.1:10009
# cat /var/lib/tor/lnd_api/hostname
3mXXXXXXXXXXXXXX.onion XXXXXXXXXXXXXXXXXXXXXX # client: pocodroid

```
* Add tor hidden service to orbot
* Generate QR 
`[root@srv44 ~]# lndconnect --host XXXXXXXXXXXX.onion  `
* Scan QR with Zeus
* Click save
* View settings
* See "Active" for this node

**Expected behavior**
I expect to see balances, and to be able to make payments et cetera.

**Screenshots**
![image](https://i.imgur.com/AiqSiD6.png"image")

**Smartphone (please complete the following information):**
 - Device: PocoPhone
 - OS: Android 9
 - Zeus Version 0.2.1

**Additional context**
LND 0.9.0-beta

**Comment by AbelLykens** [comment]
I do see traffic if I tcpdump port 10009. No idea where to continue debugging.

**Comment by kaloudis** [comment]
Zeus uses REST, not RPC. That's your issue

**Comment by AbelLykens** [comment]
Ah, whoa. Yeah that indeed fixes it. Thank you!
