### ISSUE TITLE
Bug: Fiat Currency Rate not retained

### ISSUE THREAD

**Issue by mjlamb** [ZeusLN/zeus#248]
When you have 2 nodes configured
The fiat Currency Rate is not saved when switching between node configuration.
The fiat currency rate changes back to Disabled

**To Reproduce**
Have 2 x nodes in configuration.
Go to settings
Change Fiat Currency Rate, in my case "NZD"
Tap "Save Settings"
Go back main screen, Fiat currency is able to be displayed.
Go to settings
Tap second node config to load
Fiat Currency is "Disabled"
Go to settings
Tap first node config to load
Fiat Currency is "Disabled"

**Expected behavior**
Expected behavior is to save the Fiat currency either per node config or per application.
Neither is retained when switching between node configs.

 - OS: Android
 - Device: Huawei
 - Zeus Version v0.2.1

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/264

**Comment by ZeusLN** [comment]
Fixed in v0.2.2

**Comment by mjlamb** [comment]
Tested with release v0.2.2 and confirmed working. Great work guys!
