### ISSUE TITLE
Bug: Password not retained

### ISSUE THREAD

**Issue by mjlamb** [ZeusLN/zeus#249]
Password is not retained once set.
Could be related to previous bug submitted. https://github.com/ZeusLN/zeus/issues/248

**To Reproduce**
Set password via password form
Save
Go to main screen.
Close app
Open app
Password correctly prompts ok
Go to settings
Set a Fiat currency, i.e. NZD
Save
Go to main screen.
Close app
Open app <- password not prompted.

**Expected behavior**
Password should be maintained indefinitely until blanked in password form.

OS: Android
Device: Huawei
Zeus Version v0.2.1

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/264

**Comment by ZeusLN** [comment]
Fixed in v0.2.2

**Comment by mjlamb** [comment]
Test with release v0.2.2 and confirmed working.
