### ISSUE TITLE
Wallet name "unknown" after fresh setup

### ISSUE THREAD

**Issue by myxmaster** [ZeusLN/zeus#2541]
### Describe your enhancement idea

When you create a new embedded node (not sure if it only happens via quick start at first Zeus start) and open the hamburger menu, you can see the wallet name "unknown".

It should display "My Lightning Node" or whatever.

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/blob/master/components/NodeIdenticon.tsx#L27
