### ISSUE TITLE
"error connecting to your node. Please check your settings and try again" after updating btcpay-server with "sudo btcpay.update.sh"

### ISSUE THREAD

**Issue by teval20** [ZeusLN/zeus#261]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Zeus Version [e.g. v0.1.0]

**Additional context**

**Comment by kaloudis** [comment]
@teval20 sounds like an issue with BTCPayserver, have you posted an issue in their repo?

**Comment by ZeusLN** [comment]
Not a Zeus bug, closing
