### ISSUE TITLE
Destination address not shown in transaction

### ISSUE THREAD

**Issue by Lagrang3** [ZeusLN/zeus#2636]
### Describe the bug

The "Activity" screen show a list of on-chain and lightning transactions.
I noticed that clicking on on-chain transactions I get the transaction details screen
where I can see the "Transaction Hash", "Block Height", amount, "Destination Address", etc.

The issue is that the "Destination Address " is not shown in this screen. Instead a text "false"
appears. The text contains a link to "https://mempool.space/address/undefined".
This happens with both incoming and outgoing on-chain transactions.

![Untitled](https://github.com/user-attachments/assets/85e1a3b2-69be-4fd6-9cf7-506e6138c475)

I am not sure if this a missing feature of Zeus or a communication problem with the CLN
API. I checked that core-lightning's RPC "listtransactions" shows for each transaction output
the "scriptPubKey", isn't this not enough to deduce the type of address?

### Reproduce

1. make on-chain payment
2. wait for confirmation
3. go to Activity screen and click on the last transaction
4. "Destination address" shows as "false"

### ZEUS version

v0.9.3

### Node interface

Core Lightning (CLNRest)

### Network

Clearnet

### Device

Shitty chinese android phone

### Device operating system

Android 11

**Comment by kaloudis** [comment]
Could you provide CLN and CLNRest versions?

**Comment by Lagrang3** [comment]
cln is v24.11
clnrest is the default that comes with core-lightning.

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/2638

**Comment by kaloudis** [comment]
Fix available for testing in ZEUS v0.9.4-beta1 https://github.com/ZeusLN/zeus/releases/tag/v0.9.4-beta1
