### ISSUE TITLE
Allow user to choose if they want to use an external QR code reader or not

### ISSUE THREAD

**Issue by fiatjaf** [ZeusLN/zeus#273]
This might be a good idea and sufficiently easy to implement.
Just leaving the suggestion here for the future.

**Comment by Kixunil** [comment]
I wonder, is external QR code reader even secure? I suspect it could be sniffed by other application, but I'm not an Android dev, so someone experienced should look at it.

**Comment by fiatjaf** [comment]
Well, when you start questioning these things you never stop. Is your Android installation secure? Is your phone hardware secure?
I think an external QR code reader can be safer than your Android installation, if you know what you're installing.

**Comment by Kixunil** [comment]
Well the specific concern I have is that other apps may be able to read the connection string and steal, not that the reader itself is backdoored (however, still better to have a reliable Open Source implementation than 3rd party reader).

When you use copy-paste, other apps can read stuff, so asking if it's similar in case of links seems appropriate.

**Comment by DocBrown101** [comment]
Will there be a build in qr-reader then?

I have only problems with the external readers and currently Zeus is the only supported app for raspiblitz 1.7 therefore I am currently dependent on it.

In theory, one can argue about which is safer. In practice, I need an app that works in daily use.

**Comment by ZeusLN** [comment]
Closing this as external QR code readers will break the multi-part QRs we'll be integrating for PSBT reads and channel imports in `v0.6.0`. Further more we've found a way to use `react-native-camera` and still upload builds to F-Droid.
