### ISSUE TITLE
Transaction Awaiting Confirmation Crashes the app.

### ISSUE THREAD

**Issue by mjlamb** [ZeusLN/zeus#283]
**Describe the bug**
Transaction Awaiting Confirmation Crashes the app.

**To Reproduce**
1. Send a txn to LND node so that you have a "Awaiting Confirmation" txn listed in UI
2. Tap on the txn for details.
3. App bombs out and disappears.

**Expected behavior**
Txn details displayed. App should not crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/2274034/83745160-3eb9af00-a6b1-11ea-9358-90b30901cf74.png)

 - Android
 - Zeus - Version 0.2.2

**Comment by dsche-cyber** [comment]
Just happend to me, too.
I am not sure how to provide useful information here.

System:
Miui 11.0.5.0 stable (QFJEUXM)
Android QKQ1.190825.002

**Comment by ZeusLN** [comment]
Fixed in v0.3.0

**Comment by mjlamb** [comment]
Yes confirmed working in v0.3.0
