### ISSUE TITLE
F-Droid link in README.md is broken

### ISSUE THREAD

**Issue by AndySchroder** [ZeusLN/zeus#304]
README.md has a link to F-Droid pointing to https://f-droid.org/packages/app.zeusln.zeus/ , which gives a 404 error. The correct link appears to be https://f-droid.org/en/packages/com.zeusln.zeus/ .

Also, F-Droid seems to have a very outdated version of zeus though. Any idea how to request that to be updated by F-Droid?

**Comment by ZeusLN** [comment]
We jumped the gun updating our links - there will be new pages for Zeus on Google Play and F-Droid shortly. They've been restored for now

You can follow progress on F-Droid in this issue: https://github.com/ZeusLN/zeus/issues/268

Their build process if a little finicky but we're going to try our best to get it updated with v0.3.0 this week
