### ISSUE TITLE
BtcPayServer clightning QR not connecting

### ISSUE THREAD

**Issue by Fonta1n3** [ZeusLN/zeus#316]
**Describe the bug**
BTCPay c-lightning rest QR not connecting see screenshot for error.

**To Reproduce**

Install btcpayserver, access via tor url, scan c-lightning rest QR with Zeus latest version.

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/30832395/89116039-de34cb80-d4c1-11ea-82c6-d350b682d993.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Tor Browser

**Smartphone (please complete the following information):**
 - Device: iphone 7+
 - OS: 13.3.1
 - Zeus Version 0.3.0

**Additional context**
T

**Comment by kaloudis** [comment]
That's peculiar. Is this BTCPay instance running over http or using a self-signed cert?

**Comment by Fonta1n3** [comment]
> That's peculiar. Is this BTCPay instance running over http or using a self-signed cert?

It is running via localhost and Tor, so http via onion. I would guess you need to allow http in your info.plist for iOS?

**Comment by Fonta1n3** [comment]
Looks like it may be a btcpayserver bug.. the QR code shows `xtwoxociawqd.onion/lnd-config/1054022979/lnd.config` when it should probably show `ciawqd.onion/clightning-rest/btc`?

**Comment by kaloudis** [comment]
@Fonta1n3 mind trying this out on the new v0.3.1 release?

**Comment by ZeusLN** [comment]
Fixed in v0.3.1
