### ISSUE TITLE
Bitmex Deposit address - Scan as invalid.

### ISSUE THREAD

**Issue by mjlamb** [ZeusLN/zeus#317]
When scanning the Bitmex bitcoin deposit address [onchain], Zeus fails the scan and says it is invalid.

The format of the bitmex deposit address QR code =
bitcoin:[BTC_Address_Here]?label=BitMEX%3A%20[Account_Username_here]

I suggest it is the label or the stating [bitcoin:] part that it is tripping on ?

**To Reproduce**
Scan a Bitmex deposit address.

**Expected behavior**
Can scan the address and is presented and valid.

**Smartphone (please complete the following information):**
 - Device: Android
 - Zeus Version v0.3.0

**Comment by kaloudis** [comment]
Great find. Thanks for filing! https://github.com/ZeusLN/zeus/pull/321

**Comment by kaloudis** [comment]
@mjlamb this has been fixed in v0.3.1, please test it out when you get a chance. thanks!

**Comment by mjlamb** [comment]
Unfortunately it is still giving the same error.
bitcoin:[BTC_Address_Here]?label=BitMEX%20Deposit%20-%20[Account_Username_here]

I have noticed the label has changed a bit, but do not think that is the problem. Is it the scanner I'm using? I think Zeus is using a 3rd party one, how do I tell / change ?

**Comment by mjlamb** [comment]
Further to this when the above is scanned via a R Code, Zeus displays as 
bitcoin:[BTC_Address_Here]?label=BitMEX%3A%20[Account_Username_here]
So it has cut out some of the data.... when decoding.

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/343/files

**Comment by mjlamb** [comment]
This is working for me in BETA v0.4.0beta, I also had trouble scanning a Electrum QR also, and this beta version worked with that also.

**Comment by ZeusLN** [comment]
Fixed in v0.4.0

**Comment by mjlamb** [comment]
It is correct block order now. Thanks
