### ISSUE TITLE
Certificate Installation Instructions

### ISSUE THREAD

**Issue by modl21** [ZeusLN/zeus#318]
**Describe the bug**
Instructions should mention that the file type should be changed to .crt if it is a .cert. Android won't let you install it otherwise.

**Screenshots**
![image](https://user-images.githubusercontent.com/50266466/89200676-5c56a800-d57e-11ea-9851-d4c3d8e5a235.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3A
 - OS: Graphene OS
 - Zeus Version: v0.3.0

**Comment by Kixunil** [comment]
Actually, this should be completely useless. The URI contains the certificate already, so the app should be able to use it. Zap can do it.

Also please see an [issue at Zap where we discuss improvements to the TLS UX](https://github.com/LN-Zap/zap-android/issues/203).

**Comment by kaloudis** [comment]
> Actually, this should be completely useless. The URI contains the certificate already, so the app should be able to use it. Zap can do it.
> 
> Also please see an [issue at Zap where we discuss improvements to the TLS UX](https://github.com/LN-Zap/zap-android/issues/203).

For now it's needed. Moving forward we will write some native code to prompt the user to auto-import on Android. 

I need to see if that's possible on iOS

**Comment by Kixunil** [comment]
Why not do it the way Zap does it then? It's much better UX, no prompt needed and it works. It's also possible on iOS (I worked with some custom TLS verification code for iOS in the past.)

**Comment by kaloudis** [comment]
@Kixunil Zap uses GRPC instead of REST. With a GRPC client you can easily specify a self-signed cert to accept from the server, it's not as straightforward with REST and React Native.

**Comment by kaloudis** [comment]
@Kixunil would appreciate some help with making this better on iOS if you are able to, just lmk!

**Comment by kaloudis** [comment]
Original issue fixed here: https://github.com/ZeusLN/zeus/pull/315

Added new issue for auto-processing certs here: https://github.com/ZeusLN/zeus/issues/335

**Comment by Kixunil** [comment]
Wanted to look into it better but I'm low on time lately. Apple documented the API quite reasonably, so shouldn't be a huge problem but feel free to ping me and ask about specific things if you hit issues.
