### ISSUE TITLE
Have Zeus open when you encounter a Bitcoin or Lightning address in your web-browser

### ISSUE THREAD

**Issue by ZeusLN** [ZeusLN/zeus#32]
I believe it is called 'intent'

**Comment by Dauta** [comment]
Hi 👋
I can take a look at this one. I think in React Native it's handled with Linking API. But as a heads up, this will be my first look at the code base, so can't promise super quick delivery.

**Comment by kaloudis** [comment]
@Dauta any update?

**Comment by fiatjaf** [comment]
https://github.com/BlueWallet/BlueWallet/blob/7a62a2ae6609d32f6540081a82fc32a591d1c81d/App.js#L57

**Comment by ZeusLN** [comment]
Now available in v0.2.1

https://github.com/ZeusLN/zeus/pull/241
