### ISSUE TITLE
Receive On-Chain addresses generated in Zeus seem to be of different derivation than those generated using other wallets linked to the same node

### ISSUE THREAD

**Issue by davterra** [ZeusLN/zeus#340]
I'm using Zeus on Android, connected to myNode via Tor.

Friday, I bot some Sats using Cash App and wanted to send the Sats to my Zeus wallet.

I generated an on-chain receive address with Zeus and put it into the Cash App withdraw function,
then *double-checked* the address for accuracy. About 5 minutes after hitting "Send" on the Cash App, I got a message saying that the tx had been confirmed. 

That was 3 days ago, and the tx has numerous confirms...correct amount/correct address... but is still not showing in my Zeus on-chain balance. I know the wallet is otherwise working OK, as I had previously sent some Sats to a receive address generated by RTL, and they showed up fine in Zeus. I have been able to pay a Lightning invoice with Zeus, and have other transactions initiated by either RTL or ThunderHub, and all are showing correctly in my Zeus wallet.

Also, I generated about a dozen new Receive on-chain addresses using each:
Zeus, RTL, and ThunderHub.

RTL & THunderHub generated the same list of addresses, but the address list generated by Zeus was not the same as RTL/THunderHub.

I am attaching a screenshot showing the Zeus on-chain address generated in my yet-to-be-received txfr, along with a screenshot showing the confirmed send by CashApp to the address generated by Zeus.
![Screenshot_20200829-094950_Zeus](https://user-images.githubusercontent.com/37884409/91665163-82516880-eaa8-11ea-91ff-9d03567c2a3d.jpg)
![Screenshot_20200830-101436_Brave](https://user-images.githubusercontent.com/37884409/91665396-1bcd4a00-eaaa-11ea-9b54-a38ececdc604.jpg)

**Comment by kaloudis** [comment]
Zeus no longer saves on-chain addresses, you now have to generate them every time so this sort of issue should now be avoided.
