### ISSUE TITLE
Screen cut on-top when scanning invoice

### ISSUE THREAD

**Issue by tongokongo** [ZeusLN/zeus#345]
**Describe the bug**
I was able to replicate this bug 3 times, each time before scanning the invoice I had a copied payload in phone memory, not being a lightning invoice (lnb...). After scanning the invoice the fields related to invoice details and confirmation button are hidden behind the "black screen". Video of two instances attached. Clicking on the amount restores the view. If the action is abandoned, all the rest of wallet functionalities are hidden behind this "black screen".

**To Reproduce**
1. Copy a text or website  to a payload
2. Open Zeus app (mine through Orbot) and scan invoice.
3. Should be black screen

**Expected behavior**
Full invoice visible

**Screenshots**
Video: https://drive.google.com/file/d/1-Q6FS9cXxNkLfmcrQbMve-uvmisDjpba/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: XIAOMI Redmi Note 5A
 - OS: MIUI GLOBAL 11.0.3 based on Android 7.1.2 N2G47
 - Zeus Version 0.3.1

**Additional context**
I was able to use scanning invoices on the same phone in past without this bug. I didn't have a TOR connection though, and nothing in the payload. No black screen at that time. It also might have been an older Zeus version at that time.

**Comment by Bosch-0** [comment]
Is this still an issue in latest releases @tongokongo ?

**Comment by kaloudis** [comment]
Closing this out as this is from a really old release.
