### ISSUE TITLE
Add option to set invoice expiry

### ISSUE THREAD

**Issue by ZeusLN** [ZeusLN/zeus#35]

**Comment by ZeusLN** [comment]
Fix with https://github.com/ZeusLN/zeus/pull/38

**Comment by schmitmd** [comment]
For anyone else who runs into this, it seems that LNDhub _itself_ is what doesn't support custom expiry. There's an [open issue on that project](https://github.com/BlueWallet/LndHub/issues/527).

The code in Zeus that deals with that is [here](https://github.com/ZeusLN/zeus/blob/master/views/Receive.tsx#L1071).

Looking forward to upstream fixing this.
