### ISSUE TITLE
Onchain Balance listed in reverse block order.

### ISSUE THREAD

**Issue by mjlamb** [ZeusLN/zeus#353]
Since version 0.3.1
The onchain transaction list on the front screen has reversed and shows the oldest transactions at the top.

Open Zeus and view Onchain Transaction list.

**Expected behavior**
Should be in block height order, newest block transactions at top.

 - Device: Android
 - Zeus Version [e.g. v0.3.1]
- LND V0.11.0 beta

**Comment by kaloudis** [comment]
Pinning down where the change happened right now. I'm unsure if it's v0.11 or v0.10. v0.9 doesn't have this problem.

**Comment by kaloudis** [comment]
seems to be exclusive to the v0.11 beta

**Comment by mjlamb** [comment]
Looks like I was running LND 0.10.4-beta was the last version the ordering was ok.

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/369/files

**Comment by ZeusLN** [comment]
Fixed in v0.4.0

**Comment by mjlamb** [comment]
It is correct block order now. Thanks
