### ISSUE TITLE
Locale gets reset on node config changes

### ISSUE THREAD

**Issue by ZeusLN** [ZeusLN/zeus#373]
also send, receive, and scan buttons may not properly be rigged up

**Comment by kaloudis** [comment]
this PR fixes the buttons: https://github.com/ZeusLN/zeus/pull/374

**Comment by kaloudis** [comment]
this PR fixes the main issue: https://github.com/ZeusLN/zeus/pull/375

**Comment by ZeusLN** [comment]
Fixed in v0.4.0

**Comment by Perlover** [comment]
Hi,

I tested last release from Google Play (v0.6.4) - it has the same bug:

How reproduce:

1. Install wallet, connect own node (The LND/REST API method for example type) and choose in setting other than English language
2.Everything is OK
3. But if I click Zeus icon (left top corner) then tap node config name then I see node name again (with settings icon). If I click by this line I see loading config node page with Zeus logo and after I see Zeus main dashboard with interface is English...
