### ISSUE TITLE
Trying to close a channel ruins the whole application forever

### ISSUE THREAD

**Issue by ghost** [ZeusLN/zeus#378]
**Describe the bug**
Tried to close a channel, it didn't close it and the app become useless, without any info displayed and with an error message. Cannot recover.

**To Reproduce**
Pick an inactive channel
Close it

**Expected behavior**
Channel is closed 

**Screenshots**
![error](https://user-images.githubusercontent.com/49699337/96250763-41090f80-0fa7-11eb-9fca-db4665bc96a7.jpg)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 
 - OS: Android 11
 - Zeus Version v0.3.1-play

**Additional context**
Zeus is connected via Tor to my LND node. It is run using Orbot with a client cookie. Payments send/receive work, can see channels. After trying to close a channel, all the info in the app vanishes and the error shown is the only thing that can be seen.
Using ```lnd v0.11.1-beta.rc4```

**Comment by Bosch-0** [comment]
Doesn't seem to be an issue anymore, tested on Android + iOS.
