### ISSUE TITLE
Zeus Beta: Fee Report shows same (wrong) amount for today, this week, and this month.

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#381]
For my c-lightning node using Zeus on my Android Galaxy 7 Andriod version 8.0.0,

Non-Beta Zeus tells me my fees are 354.565 sats. Yay!
Beta Zeus tells me: 
Earned Today: 95.363 sats
Earned this week: 95.363 sats
Earned this month: 95.363 sats

It would be nice if it also indicated:
Earned since ____ (If I could pick a number of days, __THAT__ would be awesome! If not, maybe 3 months?  Or all time?): ____ sats

**Comment by fiatjaf** [comment]
This is related to c-lightning-REST, not Spark. c-lightning-REST doesn't implement `day_fee_sum`, `week_fee_sum`, `month_fee_sum`, only the deprecated `total_fee_sum`.

**Comment by fiatjaf** [comment]
But actually this has led me to discover issues on Spark and Eclair too, so that was something.
