### ISSUE TITLE
After disengaging the scanner, most of the screen is black.

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#383]
**Describe the bug**
Engaging and the backing out of the scanner leaves the area of the screen in which the camera image was displayed black.

**To Reproduce**
1. In Zeus Beta 0.4.0-beta-3, click "Scan."
2. Click the back arrow at the top of the screen.
3. If you have already used Zeus beta to pay an invoice, note whether or not it shows up again (a different bug, perhaps unrelated), but either way, repeat step 2 until you are back at the screen where you see your onchain and lightning balances.
4. Note that the bottom part of the screen is black.

**Expected behavior**
The full screen should be used to display the "home screen" for the node you're using.

**Screenshots**
![Screenshot_20201017-212639_Zeus Beta](https://user-images.githubusercontent.com/1767796/96358769-dd263a00-10bf-11eb-8b41-1ce34472aeb0.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy 7
 - OS: Android 8.0.0
 - Zeus Version v0.4.0-beta3

**Additional context**

**Comment by Bosch-0** [comment]
Seems to be fixed in latest release, tested on iOS and Android. Let us know if this issue persists @dscotese
