### ISSUE TITLE
First open of an eclair node actually opens the previous(?) node in the list of nodes.

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#384]
**Describe the bug**
A connected Eclair node always fails the FIRST time you try to open it in Zeus beta.

**To Reproduce**
1. Ensure that you've connected Zeus beta to a node that isn't Eclair (I used c-lightning, so that might be necessary).
1. Ensure that you have also connected Zeus beta to an Eclair node that you're running on a different device.  It might not need to be different, but mine is.
1. Click on the NON Eclair node and see that it opens normally.
1. Close the Zeus Beta  app.
2. Open the Zeus Beta app.
2. Wait a while so you know that Zeus beta has finished all of its initialization.
3. Note that it doesn't say "Active | eclair," it just says "eclair" for the eclair node.  Click on the Eclair node to open it.
4. Note that Zeus beta has opened a different node than your Eclair node.
5. Back out of the other node and note that for the Eclair node, now it says "Active | eclair."
6. Click on it to see that it connects to the correct node now.

**Expected behavior**
If Zeus cannot open a connection to the selected node, it should say so, it should NOT open a connection to a different node as this is very confusing.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 7
 - OS: Android 8.0.0
 - Zeus Version v0.4.0-beta3

**Comment by dscotese** [comment]
I was wrong. The instructions still show that opening the Eclair node actually opens my CL node.  Re-opening...

**Comment by kaloudis** [comment]
Eclair is now deprecated
