### ISSUE TITLE
Eclair fee report shows same amount for day, week, and month.

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#392]
**Describe the bug**
Eclair fee report shows same amount for day, week, and month.

**To Reproduce**
1. Run and connect Zeus to Eclair.
2. Click on your eclair node
3. Click the little circled i in the upper left for node info.
4. Click the fees tab.
5. Note that all three periods show the same amount.

**Expected behavior**
Each period should show the correct amount.

**Screenshots**
![Screenshot_20201122-195328_Zeus](https://user-images.githubusercontent.com/1767796/99928240-1c6a2b00-2cfd-11eb-9404-4379c2a89376.jpg)

**Smartphone (please complete the following information):**
 - OS: Android 8
 - Browser Chrome
 - Version 4

**Comment by dscotese** [comment]
There are two APIs in Eclair that report fees, but one only reports the total fees for each channel for all time.  The other is `audit` which reports every single relay the node has ever done, optionally between two timestamps.  This second API seems like the right way to provide the month/week/day total routed numbers.

**Comment by ZeusLN** [comment]
@dscotese has this been fixed?

**Comment by dscotese** [comment]
I got a new version, 0.5.0-play, and the dates are fixed but this issue is not.  The fees are still displayed as the same number for all three periods.

**Comment by benthecarman** [comment]
I have the same issue

**Comment by kaloudis** [comment]
Eclair is now deprecated
