### ISSUE TITLE
Add ability to copy displayed text

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#393]
When I view a channel, I see lots of useful information.  There doesn't seem to be any way to select and/or copy any of it, so I've been sending a screenshot to anyone who wants that information, but they can't copy the text from the screenshot either, so someone ends up having to type it all out, which is ridiculous!

Any identifiers (channel points, node IDs, addresses, whatever) should be selectable to be copied to the clipboard, in my opinion.

**Comment by kaloudis** [comment]
Added in https://github.com/ZeusLN/zeus/pull/1192

**Comment by kaloudis** [comment]
Released in v0.7.0
