### ISSUE TITLE
Feature Request: Give the ability to set private flag when generating an invoice

### ISSUE THREAD

**Issue by mandelmonkey** [ZeusLN/zeus#395]
When creating an invoice we can flag the private flag and thus the invoice will not include route hints for private channels

## Description

A simple toggle when creating an invoice to let the user include route hints, I understand zeus calls the LND make invoice rpc call, so it would just need to set ```isPrivate``` to 1 and LND will include route hints in the invoice

## Context

I use zeus to connect to my LND node, however my LND node only has one private channel, when I make an invoice using zeus, the invoice cannot be paid as the sender can not find a route due to my private channel. LND allows you to set ```isPrivate``` when generating an invoice to allow routine to be possible.

Wallet such as Nayuta Core only have private channels as well as people running LND on lower end hardware or run nodes that don't want to be routing nodes all use private channels, current zeus does not work with them.

## Possible Implementation

A simple toggle when creating an invoice? or an option in advanced settings to always set private flag to true when making an invoice?

**Comment by kaloudis** [comment]
Adding this ASAP

**Comment by kaloudis** [comment]
Added in https://github.com/ZeusLN/zeus/pull/529
