### ISSUE TITLE
Spaces should be stripped from before or after amount entry.

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#396]
Try to open a channel and enter an amount with a space before the number.  I see no danger in interpreting " 5000000" as the number 5000000.  The danger is that the error " 5000000 must be an amount in satoshis," or whatever the node says about it, will not make sense to most people.

**Comment by Bosch-0** [comment]
This appears to be fixed, tested on Android. Is this still an issue for you @dscotese ?
