### ISSUE TITLE
Camera error

### ISSUE THREAD

**Issue by epicmario7133** [ZeusLN/zeus#398]
**Describe the bug**
when i want to configure my node via qr code it doesn't make me start the camera

Sorry, the Android camera encountered a problem. You may need to restart the device

**Screenshots**
https://ibb.co/kxvpKYn

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy a71]
 - OS: [ Android 10]
 - Zeus Version [the last on play store]

**Comment by Bosch-0** [comment]
Closing this as there have been many camera updates since, if the issue still persists open another issue @epicmario7133.
