### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [ZeusLN/zeus#400]
**Describe the bug**
In the process of using, I found a bug in layout / display. As shown in the figure,  the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
App version is 0.4.0, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
**To Reproduce**
1. Go to first page
2. See error

**Expected behavior**

I hope I can increase the height of button to display full text.

**Screenshots**
<img width="444" alt="bug-zeus" src="https://user-images.githubusercontent.com/18572115/103154713-46b77880-47d4-11eb-8da2-422a0f6a00ac.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Google nexus 6
 - OS: [e.g. iOS8.1] Android 8.0
 - Zeus Version [e.g. v0.1.0] 0.4.0

**Additional context**

**Comment by kaloudis** [comment]
Not applicable to the latest release, v0.6.0.
