### ISSUE TITLE
Zeus Alpha (5.0 alpha 2) displays incorrect dates for payments from Eclair 0.4.2

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#405]
**Describe the bug**
The dats reported under "payments" are incorrect.

**Screenshots**
![baddates](https://user-images.githubusercontent.com/1767796/104828221-b8a34080-581b-11eb-89b2-f61d53f10381.jpg)

**Smartphone (please complete the following information):**
 - Samsung Galaxy 7
 - Android 8.0.0
 - Zeus Version 5.0 Alpha 2

**Comment by ZeusLN** [comment]
Fixed in v0.5.0
