### ISSUE TITLE
ZeusLN reports ERROR No Route but then reports success if you just ignore it for a while when connected to Eclair.

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#407]
**Describe the bug**
Zeus reports ERROR No Route but then reports success if you just ignore it for a while

**To Reproduce**
1. Connect Zeus 5.0.0 alpha3 to Eclair.
2. Pay an invoice to a node to which you don't have a direct channel.
3. Pay close attention because sometimes a red screen showing ERROR No Route Found.
4. Notice that after a while (sometimes) the error goes away.

**Expected behavior**
The error report should be replaced with a message that says the payment is pending.  Replacing an ERROR with success is confusing and can lead people to double-pay.

**Smartphone (please complete the following information):**
 - Samsung Galaxy 7
 - OS: Android 8.0.0
 - Zeus Version 5.0.0 alpha3

**Comment by kaloudis** [comment]
@dscotese can you try in v0.5.1?

**Comment by dscotese** [comment]
I tried it and it worked.  This may be because I had a direct channel to the payer.  I'll keep an eye out in the future.

**Comment by kaloudis** [comment]
Eclair is now deprecated
