### ISSUE TITLE
Feature request: connect to URI

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#414]
If you add the ability to have Zeus tell one of your managed nodes to connect to a URI, there are some great things that will be easier, like using the @LightningLiquidityBot from the devices we use to run our nodes using Zeus.

**Comment by pseudozach** [comment]
is this request still valid? If this is to open channels to a peer, I feel like this can be automated using lnurl-channel which just got merged.

**Comment by dscotese** [comment]
It's still relevant, I think.  With LNURL, you scan something right?  Perhaps, if you have some way to turn the URI into a QR code, then having Zeus scan it would do the trick.  As it is, however, sometimes we don't have a way to turn a URI into a QR code.  I should get the latest version and explore before going on.  :-)

**Comment by kaloudis** [comment]
Unclear of what the ask is here

**Comment by dscotese** [comment]
You may already have implemented it, but the ask is to enable Zeus users to paste a URI into a field in Zeus for one of the nodes it's managing, and have Zeus instruct that managed node to open a connection to that URI.  RideTheLightning has an interface that has a connect button "Add Peer" and allows the user to open a connection to the peer, and not for any particular reason.  It works against both c-lightning (sorry, forgot the new name) and Eclair.

**Comment by kaloudis** [comment]
Add peer functionality has been added in v0.8.0
