### ISSUE TITLE
Payments tab does not discriminate between successful and failed transactions

### ISSUE THREAD

**Issue by cat-bytes** [ZeusLN/zeus#417]
**Describe the bug**
The Payments tab shows all transactions (failed or complete) and does not discriminate which is which.
Either exclude failed transactions in list, or highlight in red to indicate they failed.

**To Reproduce**
Modify JSON to have a "status":"failed"

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS14.4
 - Zeus Version:  iOS (v50.5.0-beta3)

**Additional context**
c-lightning-REST  api v1/pay/listPayments

**Comment by ZeusLN** [comment]
@cat-bytes can you try with v0.5.1?

**Comment by cat-bytes** [comment]
Still an issue with v0.5.1.

Ken

**Comment by kaloudis** [comment]
I believe this has been fixed in v0.6.0. @cat-bytes
