### ISSUE TITLE
Lightning payment gave False Failure status

### ISSUE THREAD

**Issue by cat-bytes** [ZeusLN/zeus#418]
**Describe the bug**
Sent test payment to yalls.org  and received red error screen with exclamation and payment hash.  v1/pay/listPayments api shows payment successful 'complete', and yalls.org page opened up (received payment).

Payments tab did not refresh to show the new payment.  I had to force-quit and re-open the app and then the Payments tab showed the new payment transaction.

**To Reproduce**
Try a test on
https://yalls.org/groups/97d67df1-d721-417d-a6c0-11d793739be9:768f7b83-8b5a-44b9-9a5e-b802ceab5290

**Expected behavior**
No error status.  Payments tab shows new payment transaction.

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS14.4
 - Zeus Version: iOS (v0.5.0-beta3)

c-lightning-REST

**Comment by dmamira** [comment]
having same issue.

**Comment by ZeusLN** [comment]
Fixed with https://github.com/ZeusLN/zeus/pull/505

Look out for it in v0.6.0+
