### ISSUE TITLE
Feature Request: Set fees for multiple channels.

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#419]
On the screen where we see the channels, it should be possible to select one or more of them and have a "With Selected ..." menu item that lists things we can do with them, like:

- Cooperative Close Request
- Close, forcibly if necessary
- Set new base fee AND new fee rate
Some items that would be more complicated and also very handy:
- Set new base fee (but leave rates alone)
- Set new fee rates (but leave base fee alone)

**Comment by kaloudis** [comment]
Most of this functionality exists in v0.6.0 now. Check it out.
