### ISSUE TITLE
Top Buttons on IOS Difficult to Press

### ISSUE THREAD

**Issue by penguin4111** [ZeusLN/zeus#423]
**Describe the bug**
The issue is very simple: when on IOS, pressing the buttons on the extreme top right and top left (usually settings and the back arrow) is very difficult, usually taking 5 or 6 tries. This could be because the buttons are too small, or because they are so close to the corners that they are starting to overlap with the IOS functionality (battery, time, sometimes IOS also shows its own back arrow on the top left). I am using an iPhone 12 and the issue may be specific to the newer models that have the screen taking over the whole front of the phone, I am not sure about that part.

**To Reproduce**
1. Open the app on IOS
2. Try and press the buttons on the top left (node info) or top right (settings cog).
3. Once successful, try pressing back arrow on top left.
4. How many tries did it take you to successfully press the buttons?

**Expected behavior**
Pressing buttons should be easy and happen consistently on the first try, for ease of use. 

**Screenshots**
![Zeus Screenshot](https://user-images.githubusercontent.com/78497785/110241433-b22d6d00-7f1e-11eb-92e4-e866782e0d09.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.4
 - Zeus Version version 0.5.0 on testflight

**Comment by entreprenewer** [comment]
Second this on the published App Store version.

**Comment by kaloudis** [comment]
Got a fix!

https://github.com/ZeusLN/zeus/pull/467

**Comment by ZeusLN** [comment]
Address in v0.5.2
