### ISSUE TITLE
[Bug] Cannot create invoice with eclair with no memo

### ISSUE THREAD

**Issue by benthecarman** [ZeusLN/zeus#433]
Attempted to create an invoice with eclair v0.5.1 and got this

 ![image](https://user-images.githubusercontent.com/15256660/112105018-e5f0cf80-8b79-11eb-9a86-112c3654b7aa.png)

On latest testflight version

**Comment by pseudozach** [comment]
I'm not able to reproduce this issue, is this still happening for you @benthecarman ?

**Comment by Bosch-0** [comment]
Still an issue @benthecarman ?

**Comment by benthecarman** [comment]
I no longer have an eclair node but I think it was fixed
