### ISSUE TITLE
Payments over-reported C-Lightning-REST and iOS

### ISSUE THREAD

**Issue by willcl-ark** [ZeusLN/zeus#450]
**Describe the bug**
When using [C-Lightning-REST](https://github.com/Ride-The-Lightning/c-lightning-REST/) to connect to C-Lightning and Zeus on iOS "Payments" are over-reported by slightly more than 42x.

**To Reproduce**
* Install C-Lightning v0.10.0
* Connect to node via IP

**Expected behavior**
* Accurate count of payments
* Note: UTXO and lightning channel total are displayed correctly

**Screenshots**
![IMG_3067](https://user-images.githubusercontent.com/6606587/115772498-19a45c80-a3a7-11eb-9e91-1b4b0847d410.jpeg)

<img width="1196" alt="Screenshot 2021-04-22 at 20 11 52" src="https://user-images.githubusercontent.com/6606587/115773625-718f9300-a3a8-11eb-8135-e01e5bb07710.png">

**OS:**
 - OS: iOS 14.5
 - Debian GNU/Linux 11 (bullseye)
 - Zeus v0.5.1

**Comment by kaloudis** [comment]
@willcl-ark this should be fixed in v0.6.0

**Comment by willcl-ark** [comment]
Thanks @kaloudis !
