### ISSUE TITLE
LNDhub wallet from Umbrel LNDhub

### ISSUE THREAD

**Issue by Darth-Coin** [ZeusLN/zeus#452]
Please can you check if Zeus is compatible with the LNDhub from Umbrel LNDhub (Bluewallet LNDhub) ?
I tried to scan the QR code for LNDhub from Umbrel, using onion address.
It scan it, but then the app crashed & restart
I tried to put manually the host, port etc, but gives error lndhub url

I am connected with Zeus 0.5.1 successfully with following:
- Umbrel node LND wallet (tor)
- lntxbot wallet (lndhub clearnet)
- BW lndhub wallet (BW servers clearnet)
- LNbits (lndhub) from Umbrel (tor)

**Comment by kaloudis** [comment]
Will investigate this for you tonight

**Comment by ZeusLN** [comment]
Addressed in v0.5.2
