### ISSUE TITLE
Chosen fee not used when opening channel for c-lightning.

### ISSUE THREAD

**Issue by dscotese** [ZeusLN/zeus#460]
**Describe the bug**
I changed the sats per byte from 2 to 3 and then opened a channel.  I don't see a log I can send you to prove that the 3sats per byte setting was used so we'll have to trust my memory.  The transaction shows 1.007 sat/vByte (234 bytes, but only 154 vBytes).  This seems like a bug.

**To Reproduce**
1. Choose a node with which to open a channel from your c-lightning node that you connected to Zeus-LN
2. Scan or enter the info for the node.
3. Set the sats-per-byte to something higher than the default (which was two when I tried it)
4. Open the channel.
5. Look up the transaction (ID available from the Open channels screen, but only as a link to blockstream) and note that the sast per byte is different from what you chose.

**Expected behavior**
The setting chosen for sats-per-byte should be used in the channel opening transaction.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 7
 - OS: Android 8.0.0
 - Zeus Version 0.5.1-Play

**Comment by kaloudis** [comment]
Thanks for filing. Will tackle this asap.

c-lightning support should improve as I'm adding a dedicated node to my setup.

**Comment by kaloudis** [comment]
looks like you need to enter in `urgent`, `normal`, or `fast`

https://github.com/Ride-The-Lightning/c-lightning-REST/blob/master/docs/channelmgmt.md#fundchannel

we will add some better UI controls here

**Comment by dscotese** [comment]
It's true that RTL does not provide access to c-lightning's API capability of specifying a perkb or perkw number of sats, but the support is there and the default is perkb, as you can see at https://lightning.readthedocs.io/lightning-fundchannel.7.html.  It may be the case that the REST interface doesn't handle the fine-tuning support and that would explain why RTL doesn't either.

**Comment by ZeusLN** [comment]
Addressed in v0.5.2
