### ISSUE TITLE
Filepath & node version are leaked into apk in index.android.bundle file

### ISSUE THREAD

**Issue by emanuelb** [ZeusLN/zeus#463]
Comparing 0.5.1 github apk: https://github.com/ZeusLN/zeus/releases/download/v0.5.1/zeus-v0.5.1.apk
with f-droid apk: https://f-droid.org/repo/app.zeusln.zeus_24.apk

BlueWallet also suffer from the diff in `./res/raw/node_modules_elliptic_package.json` & node-version variation in same function, details at: https://github.com/BlueWallet/BlueWallet/issues/3239

Files ./FromGithub/assets/index.android.bundle and ./FromFDroid/assets/index.android.bundle differ

```
__d(function(g, r, i, a, m, e, d) {
    var f, n = r(d[0]),
        t = r(d[1]);
    if (e.pbkdf2 = function(f, n, o, u, c, p) {
            if ('function' == typeof c && (p = c, c = void 0), t(o, u), 'function' != typeof p) throw new Error('No callback provided to pbkdf2');
            setTimeout(function() {
                p(null, e.pbkdf2Sync(f, n, o, u, c))
            })
        }, process.browser) f = 'utf-8';
    else {
        var o = parseInt("v10.15.0".split('.')[0].slice(1), 10);
        f = o >= 6 ? 'utf-8' : 'binary'
    }
```

in above function the node version leaked:
```diff
+        var o = parseInt("v10.15.0".split('.')[0].slice(1), 10);
-        var o = parseInt("v8.11.1".split('.')[0].slice(1), 10);
```

and also there is filepath/buildpath leakage which is related to next diff:

```diff
+            ["elliptic@6.5.3", "/Users/scorpius/zeus"]
-            ["elliptic@6.5.3", "/home/vagrant/build/app.zeusln.zeus"]
```
```diff
+        _where: "/Users/scorpius/zeus",
-        _where: "/home/vagrant/build/app.zeusln.zeus",
```

in `./res/raw/node_modules_elliptic_package.json` file there path leakage `/Users/scorpius/zeus` used on github version while `/home/vagrant/build/app.zeusln.zeus` used in vagrant version, filepath of buildpath should not be leaked into the APK.
```diff
   "_args": [
     [
       "elliptic@6.5.3",
-      "/Users/scorpius/zeus"
+      "/home/vagrant/build/app.zeusln.zeus"
     ]
   ],
   "_from": "elliptic@6.5.3",
@@ -28,7 +28,7 @@
   ],
   "_resolved": "https://registry.npmjs.org/elliptic/-/elliptic-6.5.3.tgz",
   "_spec": "6.5.3",
-  "_where": "/Users/scorpius/zeus",
+  "_where": "/home/vagrant/build/app.zeusln.zeus",
```

**Comment by kaloudis** [comment]
How do we fix this?

**Comment by emanuelb** [comment]
Find where the problematic source-code and make change/PR to it, it might be in some upstream components or toolchain, writing minimal/reduced example is also useful for easier debugging.

The node version changes in code from this file:
https://github.com/crypto-browserify/pbkdf2/blob/4a0bc7bc576418f6d0e7f47339b6054f00d07718/lib/default-encoding.js#L6-L8

which might be because `rn-nodeify` is called in postinstall step in this repo, thus maybe need to open bug upstream, but better to do it with minimal code & steps to reproduce.

Regarding the path leakage, no idea what cause it, thus the cause need to figure out before opening bug upstream (it maybe bug in other component) https://github.com/indutny/elliptic

**Comment by kaloudis** [comment]
I see. This can also be fixed in our efforts to create reproducible builds. We are aiming to have a Docker environment for building everything by `v1.0.0`

**Comment by kaloudis** [comment]
This is now solved with the addition of reproducible builds https://github.com/ZeusLN/zeus#reproducible-builds
