### ISSUE TITLE
[Feature request] Add PIN to open the app

### ISSUE THREAD

**Issue by Darth-Coin** [ZeusLN/zeus#466]
Having Zeus connected straight to my node on a mobile device, have to be secured with an extra step.
I am not comfortable having direct access to my whole node without a secured PIN or password to enter into Zeus app.
A plausible deniability option also could be nice to have.

**Comment by kaloudis** [comment]
This is coming in the redesign

**Comment by Darth-Coin** [comment]
Works great in 0.6.0 beta 2. We can close this request now.
