### ISSUE TITLE
Using multipath payment - Zeus app crashed

### ISSUE THREAD

**Issue by Darth-Coin** [ZeusLN/zeus#482]
Environment used:
- Umbrel node 0.3.13 (on Debian 10)
- Zeus v.0.5.1 on Android 8.1
- connected to own Umbrel node using Tor (integrated in Zeus, not Orbot)

Regular LN txs works OK, even if are slow due to Tor connection
Tried to do a multipath tx of 500k sats (have enough liquidity on the node). Set 4 max path, max 40sats fee, 30 sec timeout
When I clicked on pay using multipath button, app crash and appear a message to restart it.
I open it several times and did the same payment settings, I even changed the timeout and fee but is doing the same, crashing.
I was thinking that is a Tor issue so once I force closed the app then open it again as fresh, wait to appear all the balance and txs, went to browse inside to let the Tor do its stuff to be well connected and then paste the invoice and select again the MPP.
It crashed.

If you need more details let me know.

**Comment by kaloudis** [comment]
is LND still v0.12.1?

**Comment by Darth-Coin** [comment]
in RTl it says: LND 0.12.1-beta commit=v0.12.1-beta

**Comment by kaloudis** [comment]
Tor is the issue here I believe. For now to use MPP over Tor you have to use it with Orbot instead of Zeus' built in Tor service.

We'll work on a fix for this.

**Comment by ZeusLN** [comment]
Relates to https://github.com/ZeusLN/zeus/issues/439

**Comment by kaloudis** [comment]
This is fixed in Zeus v0.6.0 as long as you're upgraded to lnd v0.13.0+. Stay tuned for the alpha release this week.

**Comment by Darth-Coin** [comment]
Just an update on this.
Used v.0.6.0 alpha 5
Umbrel 0.4.11 (lnd 0.14.1)
Scanning QR invoice didn't worked so I paste the invoice code (50k sats)
Selected MPP with no selection of nodes, put 200 seconds timeout and 10 max paths, no max fee.

Sending tx timeout after 10 seconds, with no explanation.

Later I tried also selecting 1st and 2nd hop of 2 channels I have with enough liquidity and good peers.
Also didn't go through, ended in timeout.

Would be nice to have some kind of debug log tool in the app. At least to be able to send to devs to see what is failing.

**Comment by kaloudis** [comment]
@Darth-Coin assuming you are using Tor? The library times out at 10 seconds. We're aware of this issue. I will get this fixed or potentially even take over maintenance of the Tor library before we release the v0.6.0 GM
