### ISSUE TITLE
Error: Connect timed out

### ISSUE THREAD

**Issue by viperperidot** [ZeusLN/zeus#483]
**Describe the bug**
When connecting to Zeus over Tor from my lightning node I get the message Error: Connect timed out.

**To Reproduce**
Steps to reproduce the behavior: See above

**Expected behavior**

Wallet connects to node and I am able to use normally.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxy A11
 - OS: [e.g. iOS8.1] Android
 - Zeus Version [e.g. v0.1.0] Latest F-Droid

**Additional context**

**Comment by rene78** [comment]
I'm having exactly the same problem.

**Comment by kaloudis** [comment]
This should be fixed in the latest v0.6.0 releases
