### ISSUE TITLE
Keysend not working with lnd 0.13.0 and zeus 0.5.2

### ISSUE THREAD

**Issue by cercatrova21** [ZeusLN/zeus#495]
**Describe the bug**
After upgrading my node to lnd 0.13.0 the keysend function (channels -> keysend) is not working anymore. After inputing some sats as amount, an error is showing: incorrect_payment_details. (and a payment hash)

**To Reproduce**
1. Go to 'channels'
2. Click on 'a channel'
3. Scroll down to 'keysend'
4. enter some amount and click send
5. See error above

**Smartphone:**
 - OS: iOS
 - Device: iPhone XR
 - Version zeus 0.5.2
 - version LND: 0.13.0

The keysend option in my lnd.conf file is activated. Even the amp is set to true.

**Comment by kaloudis** [comment]
Keysend is being deprecated in favor of AMP https://github.com/lightningnetwork/lnd/issues/5190#issuecomment-816878950

**Comment by kaloudis** [comment]
You'll still be able to send to pubkeys in the same manner, we just need to add in the functionality https://api.lightning.community/?shell#sendpayment-2

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/529

Will get this out the door in the v0.6.0-alpha1 release. Stay tuned.

**Comment by cercatrova21** [comment]
Tested it on v0.6.0-alpha1, works for me now
