### ISSUE TITLE
C-Lightning-REST: Offers

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#526]
https://github.com/Ride-The-Lightning/c-lightning-REST/pull/67/files

**Comment by kaloudis** [comment]
The biggest issue is that c-lightning doesn't currently store your subscriptions, it has to be handled at the app layer. This could be annoying if you are using multiple interfaces to manage your node, eg. Zeus + RtL

**Comment by tukac** [comment]
I can't connect to REST even after RTL is stopped (same REST port as RTL). I tried http+onion, https+onion and https+clearnet (my c-lightning uses both) but no success. What is correct approach?

**Comment by Bosch-0** [comment]
Discussion for this has moved to this newer issue. Hoping to add this in 0.7.0! https://github.com/ZeusLN/zeus/issues/890
