### ISSUE TITLE
Lurking mode not hiding all values

### ISSUE THREAD

**Issue by StijnBTC** [ZeusLN/zeus#540]
**Describe the bug**
Lurking mode does not hide all sat values on the wallet screen and channel screen. 

**To Reproduce**
1. Go to settings 
2. Set lurking mode to enabled
3. Click on save
4. Go to wallet screen
5. Total is hidden but the onchain and lightning amounts are still visible 

**Expected behavior**
I expected the onchain balance and lightning balance to be hidden 

**Screenshots**
![Screenshot_20210818-082412_Zeus.png](https://user-images.githubusercontent.com/10080035/129851715-280041fc-e50d-4b63-98a6-290faaf3fb3b.png)

**Smartphone (please complete the following information):**
 - Device: [oneplus 6]
 - OS: [lineage os 18.1]
 - Zeus Version [v0.6.0-alpha1]

**Additional context**

**Comment by kaloudis** [comment]
Thanks for the report - this is being addressed!

**Comment by kaloudis** [comment]
This is fixed in v0.6.0-alpha2
