### ISSUE TITLE
iOS: Invoice toggles not hanging right

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#542]
![nnjXtJM](https://user-images.githubusercontent.com/1878621/129931379-7870bf67-b18c-450c-a347-5b629b8a4846.png)

**Comment by 0xtrr** [comment]
Here is a screenshot of what I think is the same bug: https://imgur.com/a/pY2ka8B

**Comment by kaloudis** [comment]
That's exactly it, @0xtrr. Adding it to my original post. Thank you.

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/546

**Comment by kaloudis** [comment]
This is fixed in v0.6.0-alpha2
