### ISSUE TITLE
Channel fee settings

### ISSUE THREAD

**Issue by Deekee62** [ZeusLN/zeus#547]
**Describe the bug**
When viewing a channel and selecting "Set New Fees" both fees show 1/1 and I'm unable to set new fees at all.

**To Reproduce**
1. Go to 'Channel'
2. Click on 'any Channel'
3. Scroll down to 'Bottom'
4. Click on 'Set New Fees'
4. See fees set Base Fee msat 1 / PPM (Parts Per Million) 1

**Expected behavior**
Currently set fees should be shown

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhone6]
 - OS: [iOS14.7.1]
 - Zeus Version [e.g. v0.6.0-alpha1]

**Additional context**
It would be great to see the currently set fees in the channel view.

**Comment by kaloudis** [comment]
What node implementation and version are you on?

**Comment by Deekee62** [comment]
Umbrel 0.3.14

**Comment by kaloudis** [comment]
This has been fixed in v0.6.0-alpha2

**Comment by Deekee62** [comment]
Seems to work perfectly, thanks!
