### ISSUE TITLE
Android [Redesign]: Black screen when pressing back button on wallet view

### ISSUE THREAD

**Issue by TiKawamoto** [ZeusLN/zeus#566]
Pressing the back button on the main wallet screen will display a black screen. In most apps this action exits the app.

Pressing the back button a second time (when on the black screen) will properly exit the app.

 - Device: Samsung Galaxy S10+
 - OS: Android 11
 - Zeus 0.6.0-alpha2

**Comment by kaloudis** [comment]
Thanks for the report, Ti!

That black screen you're seeing is actually the placeholder for the password login screen. We need to re-arrange the way our page navigation stack operates. It's on the TODO list for the `v0.6.0` general release.

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/713
