### ISSUE TITLE
Routing: account for msats

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#569]

**Comment by deregs** [comment]
@kaloudis this is already implemented right?

for c-lightning and eclair I see msats:
<img width="438" alt="Screen Shot 2022-02-06 at 7 46 07 PM" src="https://user-images.githubusercontent.com/93104057/152718021-39c272bc-84cb-481c-972f-dd5884b59c75.png">

and it doesn't look possible to display msats for lnd routing fees, /v1/fees does not return msats

**Comment by kaloudis** [comment]
`/v1/switch` does though, see https://api.lightning.community/#lnrpcforwardingevent

**Comment by deregs** [comment]
oh cool I'll try implementing this then

**Comment by deregs** [comment]
@kaloudis you can close this issue
