### ISSUE TITLE
Multiple requests when scanning lnurl-pay

### ISSUE THREAD

**Issue by akovalenko** [ZeusLN/zeus#572]
**Describe the bug**
When scanning a lnurl-pay, the endpoint gets a cascade of similar https requests. 

**To Reproduce**
1. Select a destination on https://lnurl-pay.me
2. Scan QR code with ZeusLN.
3. In some cases (frequently enough) see you hitting a rate limit and getting 503 from the server.

**Expected behavior**
lnurl-pay is decoded, exactly one request hits its endpoint before the confirmation dialog

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - OS: Android
 - Zeus Version v0.6.0alpha2

**Comment by setpill** [comment]
Can confirm this also applies to LNURL-withdraw QR codes.

Zeus v0.6.0-alpha3

**Comment by setpill** [comment]
Seems like it just keeps scanning, even after it's already opened the "Receive" view. If I hold my phone up to the QR code I can see the requests streaming in.

**Comment by kaloudis** [comment]
Fixed in v0.6.0-alpha4 https://github.com/ZeusLN/zeus/releases/tag/v0.6.0-alpha4
