### ISSUE TITLE
Getting started going back after selecting node option

### ISSUE THREAD

**Issue by kevkevinpal** [ZeusLN/zeus#579]
**Describe the bug**

**To Reproduce**
https://user-images.githubusercontent.com/15950706/132710541-8c22dbee-c86b-49e1-8242-b5213347be9e.mov

**Expected behavior**
It should go back to that previous setup page

**Screenshots**
Added a video in the reproduce section

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Ipod touch 7th gen]
 - OS: [iOS14.5]
 - Zeus Version [v0.6.0-alpha2]
 This is in the simulator

**Additional context**
I wanna just see if this is a change we want to make I should be able to go in and implement

**Comment by kaloudis** [comment]
Should be an easy fix and good first PR. Go for it!

**Comment by kevkevinpal** [comment]
> Should be an easy fix and good first PR. Go for it!

Awesome I'll assign myself this issue

**Comment by Bosch-0** [comment]
Appears to be fixed in latest Alpha's.
