### ISSUE TITLE
App crashes when clicking on a channel [android][0.6.0-alpha2][tor]

### ISSUE THREAD

**Issue by phasnox** [ZeusLN/zeus#580]
### Issue
When clicking on a channel from the *channels* list, the app crashes.

### Env Info
**OS:** Android GrapheneOS
**Zeus Version:** 0.6.0-alpha2
**Node Version:** c-lightning 0.10.1
**Connection type:** TOR c-lightning REST

**Comment by openoms** [comment]
Reproduced this on CalyxOS
Connected to CL-REST v0.5.2
over VPN
Zeus v0.6.0-apha3

**Comment by willcl-ark** [comment]
FWIW this is also the case on iOS:

* iPhone 12 Pro, iOS 15.2
* CL-REST v0.5.2 [clearnet]
* Zeus v0.6.0-alpha3
* C-Lightning v0.10.2

**Comment by Bosch-0** [comment]
Is this still an issue for you guys? @phasnox @openoms @willcl-ark

**Comment by willcl-ark** [comment]
Not for me on 0.6.0 beta 2 :)
