### ISSUE TITLE
"Unexpected token" JSON errors (LND)

### ISSUE THREAD

**Issue by futurepaul** [ZeusLN/zeus#581]
**Describe the bug**
Errors from the LND backend that complain about JSON parsing are usually because an API that returns JSON on success is returning non-JSON on failure, but we're trying to parse that error or whatever it is as JSON.

if you look at the Eclair backend it try / catches parsing the error as json:
```javascript
    if (status < 300) {
        return response.json();
    } else {
        let errorInfo;
        try {
            errorInfo = response.json();
        } catch (err) {
            throw new Error(
                'response was (' +
                    status +
                    ')' +
                    response.text()
            );
        }
        throw new Error(errorInfo.error);
    }
```

but LND just forges ahead:

```javascript
    if (response.info().status < 300) {
        return response.json();
    } else {
        const errorInfo = response.json();
        throw new Error(
            (errorInfo.error && errorInfo.error.message) ||
                errorInfo.message ||
                errorInfo.error
        );
    }
```

**Screenshots**

![Screenshot_20210911-110930622](https://user-images.githubusercontent.com/543668/132954340-df00110a-4726-49d2-a51a-4a821b45acfd.png)

**Comment by BitcoinLabrador** [comment]
I have the same bug but only on the latest RC, any payment. When I install v0.5.2 everything works fine.

**Comment by kn0wmad** [comment]
I get a similar error when attempting to simply load the connected LND node's main page

SyntaxError: JSON Parse error: Unexpected token: C

**Comment by kaloudis** [comment]
This has been fixed in newer releases. Feel free to reopen if you see this again.
