### ISSUE TITLE
Alpha2 - Crash - First Hop Selection

### ISSUE THREAD

**Issue by pardus79** [ZeusLN/zeus#583]
**Describe the bug**
Paying a lighting invoice and choosing first hop, app crashes if you don't select a channel but click the "Set Channel" button.

**To Reproduce**
1. Import/scan lightning invoice to pay
2. Click on First Hop>Select Channel To Use
3. Click on "Set Channel" without choosing a channel first.
4. App closes

**Expected behavior**
A message indicating that a channel must be selected should happen in this case.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11
 - Zeus Version Alpha2

**Comment by kaloudis** [comment]
Addressed in https://github.com/ZeusLN/zeus/pull/667

**Comment by kaloudis** [comment]
Fixed in v0.6.0-beta1
