### ISSUE TITLE
Alpha2 - First Hop Selection Doesn't Load After Canceling

### ISSUE THREAD

**Issue by pardus79** [ZeusLN/zeus#584]
**Describe the bug**
After loading a lighting invoice to pay, if you go to choose a first hop, then cancel, you can't load the first hop channel screen without backing out of the invoice first.

**To Reproduce**
1. Load/scan an invoice to pay
2. Click on First Hop>Select Channel to Use
3. Click Cancel
4. Click on First Hop>Select Channel to Use
5. Nothing happens

**Expected behavior**
It should reload the first hop channel list.

**Smartphone (please complete the following information):**
 - Device: Pixel 4A
 - OS: Android 11
 - Zeus Version Alpha 2

**Comment by kaloudis** [comment]
Addressed in https://github.com/ZeusLN/zeus/pull/667

**Comment by kaloudis** [comment]
Fixed in v0.6.0-beta1
