### ISSUE TITLE
Alpha2 - Back Button on Lightning Invoice Screen Just Reloads Inv

### ISSUE THREAD

**Issue by pardus79** [ZeusLN/zeus#585]
**Describe the bug**
Instead of going back to the main wallet page, the "back" button (arrow at top left) just reloads the lightning invoice and stays on that screen. Using the phone's "back" function (swipe from phone edge in my case) works fine. Suspect that the back arrow is actually reloading the lightning invoice from the clipboard instead of telling the app to go back.

**To Reproduce**
1. Click on scan/send to load invoice from clipboard
2. Click on arrow at top left to go back

**Expected behavior**
Should go back to home screen. Just reloads lightning invoice instead.

**Smartphone (please complete the following information):**
 - Device: Pixel 4A
 - OS: Android 11
 - Zeus Version Alpha 2

**Comment by kaloudis** [comment]
Fixed in v0.6.0-alpha4 https://github.com/ZeusLN/zeus/releases/tag/v0.6.0-alpha4
