### ISSUE TITLE
Alpha2 - Not Clearing Prior Failed Payment From Invoice Screen

### ISSUE THREAD

**Issue by pardus79** [ZeusLN/zeus#586]
**Describe the bug**
Clicking on Scan/Send button, it reloads the last failed/unpaid invoice that was attempted instead of pulling new invoice from clipboard. Clicking the "back" arrow will reload the screen with the new invoice. But even if the new one is paid successfully, it will still re-load the prior failed one when going back to the payment screen.

**To Reproduce**
1. Load a lightning invoice. Attempt & fail at payment.
2. Copy a new lightning invoice to clipboard
3. Click on Scan/Send button

**Expected behavior**
The lightning invoice currently in the clipboard should be loaded. If none, the camera should be enabled to scan a QR.

**Smartphone (please complete the following information):**
 - Device: Pixel 4A
 - OS: Android 11
 - Zeus Version Alpha 2

**Comment by kaloudis** [comment]
This has been addressed by https://github.com/ZeusLN/zeus/pull/626
