### ISSUE TITLE
Incorrect timeout error when paying LN invoice

### ISSUE THREAD

**Issue by pseudozach** [ZeusLN/zeus#588]
**Describe the bug**
When trying to make an LN payment, screen shows timeout while the payment may have succeeded.

**To Reproduce**
1. Scan an LN invoice
2. Pay
3. Wait until payment completes
4. Red error screen that says `timeout` 

**Expected behavior**
Timeout should only be shown if payment actually times out, not for successful payments.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android Pixel 3
 - OS: Android 11
 - Zeus Version alpha1

**Additional context**
Not sure if this is known/fixed, I can try to reproduce and fix it myself. Just wanted to document it.

**Comment by Firewalker99** [comment]
Same here.

**Comment by RicardoCapricciosa** [comment]
I can confirm this with v0.6.0-alpha4

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/620

**Comment by kaloudis** [comment]
Fixed in v0.6.0. Out now.
