### ISSUE TITLE
Will not open camera to scan QR Code

### ISSUE THREAD

**Issue by miningdave** [ZeusLN/zeus#595]
**Describe the bug**
Will not open camera to scan QR code. When you go to scan a code the app wants to open CVS app or SoCatch APP

Phone: OnePlus Nord N10 5G
Zeus version: 0.5

![messages_0](https://user-images.githubusercontent.com/61623195/135734444-63547ed4-6c01-48ee-a3a9-ef2f6155929c.jpeg)
.2

**Comment by kaloudis** [comment]
This should be fixed for you in the v0.6.0 releases

**Comment by Bosch-0** [comment]
@miningdave have you tested this out witth the latest beta release?

**Comment by miningdave** [comment]
I can only see 0.5.2 in the play store. Is there an APK I can grab?

**Comment by Bosch-0** [comment]
Yep you can find the latest beta here https://github.com/ZeusLN/zeus/releases/tag/v0.6.0-beta2

**Comment by miningdave** [comment]
Works properly now. Thanks. Can close unless you need me to test something else.
