### ISSUE TITLE
Onchain receive shows old address by default

### ISSUE THREAD

**Issue by pseudozach** [ZeusLN/zeus#596]
This is not exactly a bug but maybe more of a suggestion/request.

When receiving onchain bitcoin, zeus shows the most recent address by default. Isn't this bad practice? Shouldn't the wallet generate a new address by default?

User can already check their previous UTXOs from the coins screen so I think it would be better if onchain receive screen would generate a new address by default.

**Comment by kaloudis** [comment]
Addressed in v0.6.0-alpha4 https://github.com/ZeusLN/zeus/releases/tag/v0.6.0-alpha4
