### ISSUE TITLE
CL MPP shown as different payments 

### ISSUE THREAD

**Issue by openoms** [ZeusLN/zeus#597]
**Describe the bug**
connected to C-lightning REST over VPN
sent 1 * 9676 sats payment which was MPP in 7 parts
all entries have the same payment hash
but it should show only as one!

**To Reproduce**
MPP from CLI
click on up arrow for history

**Expected behavior**
Should show as one and maybe inform about payment parts with the overall fee paid

**Screenshots**
![IMG_20211007_064946_652](https://user-images.githubusercontent.com/43343391/136327142-8a746ae9-1ff4-4a26-8950-d927c16d97c0.jpg)

**Smartphone (please complete the following information):**
 - Device: [Pixel 3aXL]
 - OS: [CalyxOS 2.9.0, Android 11 ]
 - Zeus Version [e.g. v0.6.0rc3]

**Additional context**
Connected to C-lightning REST https://github.com/Ride-The-Lightning/c-lightning-REST/releases/tag/v0.5.2

C-Lightning v0.10.1 + on master

**Comment by openoms** [comment]
cdecker in https://t.me/lightningd/7843

>That looks like it just returns the listsendpays result when it should be using listpays. The former accounts each htlc separately and is part of the low-level interface whereas the latter groups by pay invocation (and with #4567 will keep them separate if you manually try to pay the same invoice multiple times)

**Comment by kaloudis** [comment]
related to https://github.com/ZeusLN/zeus/issues/450

**Comment by kaloudis** [comment]
Fixed in v0.6.0-alpha4 https://github.com/ZeusLN/zeus/releases/tag/v0.6.0-alpha4
