### ISSUE TITLE
Alpha3: Fiat conversion not working

### ISSUE THREAD

**Issue by cercatrova21** [ZeusLN/zeus#600]
Found a bug in the new release alpha3: if you‘re going to the channel page, click on a channel and hit the Keysend button, the screen with an empty amount is displayed. If you hit on the „amount“ text, the currency changes. If you hit there for example USD and type 1 in and send it, it sends only 1 sat. So every Fiat input is taken in sats. 
(Moscow time isn‘t 1 yet 😉)

Tested it on iOS and Android, same behavior. Also tried it with 2 different currency, same issue.

**Comment by kaloudis** [comment]
Fixed in v0.6.0-alpha4 https://github.com/ZeusLN/zeus/releases/tag/v0.6.0-alpha4
