### ISSUE TITLE
[Feature request] Some UX changes for easy usage

### ISSUE THREAD

**Issue by Darth-Coin** [ZeusLN/zeus#602]
Ok, these are not bugs or issues, just some UX improvements if are possible.
I am testing the new version 0.6 Alpha and I notice that some parts can be improved.
![image](https://user-images.githubusercontent.com/56997124/138295627-111f2479-fea4-4ba3-a701-5b82ee96b03b.png)

It could be nice to have displayed the name of the wallet/node on top. I have like several wallets/nodes in my Zeus app (lndhub, lnd nodes etc) and could be helpful to have displayed the name of the wallet you have active without going to settings page.

1 - When you click on Lightning button, better to open like LN wallet of your node and list all your LN txs and also the option to start a new  LN txs directly (see point 3)
2 - When you click on Bitcoin button, to open the onchain txs listing and be able to start an onchain tx from there.
3 - that will be nice to be a split button, when you click it to have like 3 options:
- send Lightning address (type a new one or select from a contact list)
- scan a QR code
- paste a BTC/LN invoice

Beside of these, just wanted to report about this new version: using Tor still hangs. Sometimes it connects immediately, sometimes I have to refresh the connection, going to alternative wallets, open them, coming back to node connection until finally connects.
Meanwhile Zap (latest version with Tor integrated) it connects instant to my Umbrel node.

Anyway, good work with this new version!

**Comment by Bosch-0** [comment]
Thanks for the feedback! I have actually been thinking of all the issues you have pointed out, below is an early concept that addresses all the points you've brang up. See the video below showing the changes I am thinking about. 

https://www.youtube.com/watch?v=pcfDvZng-yY
