### ISSUE TITLE
Beta testing for iOS (Zeus v0.6.0-alpha3)

### ISSUE THREAD

**Issue by dcar2121** [ZeusLN/zeus#608]
I have made multiple attempts to open the Zeus app v0.6.0-alpha3 on iPhone 11 Pro Max 256GB in iOS beta with Apple developer beta profile. Opening Zeus app via TestFlight but I continue to receive no response. ![image](https://user-images.githubusercontent.com/90586784/140549499-29728217-b4f3-4926-ad51-aadb36554958.png)
![image](https://user-images.githubusercontent.com/90586784/140549523-3629e800-1b05-4ff6-8349-de146699b1b8.png)

**Comment by dcar2121** [comment]
![image](https://user-images.githubusercontent.com/90586784/141651770-8b272a60-ec47-4f72-8802-f29fbccc1abe.png)

**Comment by dcar2121** [comment]
This is a closed issue

**Comment by kaloudis** [comment]
Closing in favor of https://github.com/ZeusLN/zeus/issues/641
