### ISSUE TITLE
App not loading

### ISSUE THREAD

**Issue by SecretestSquirrel** [ZeusLN/zeus#644]
Just installed newest Alpha version. Upon opening the app, it simply hangs on the startup screen, never progressing past it. Included screen grab video. Previous version worked perfectly fine. Have attempted force stop of the app and restart of the phone to no avail.

https://user-images.githubusercontent.com/74485231/144221399-317b169e-db8e-46e7-bbd8-24106b4a9d67.mp4

**App version:** v0.6.0-alpha4
**Device:** Google Pixel 4a
**OS:** CalyxOS v2.11.0 (November Security Update)/Android 11

**Comment by The34Goon** [comment]
can confirm

**Comment by kaloudis** [comment]
Sorry, there's a bug for people with previous installs. You need to uninstall and reinstall to fix - unfortunately clearing your saved data. We will likely put out a quick alpha5 in a few days to patch.

**Comment by kaloudis** [comment]
Fixed in v0.6.0-beta1
