### ISSUE TITLE
No Polish language or currency

### ISSUE THREAD

**Issue by pysiak** [ZeusLN/zeus#645]
**Describe the bug**
I translated all labels for polish language (PL) but the polish language is not showing up on the list in latest version.
Translations: https://www.transifex.com/ZeusLN/zeus/language/pl/

Also, there is no Polish Zloty (PLN) as currency on the list.

**To Reproduce**
1. Go to Settings -> Language
2. See there is no "Polski" to choose from. Polski means "Polish" in Polish
3. Go to Settings -> Currency
4. See there is no "Polish Zloty (PLN)" on the list

**Expected behavior**
Polish translation labels and Polish Zloty (PLN) added as currency

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.1
 - Zeus Version v0.6.0-alpha4 downloaded 01-DEC-2021

**Comment by pysiak** [comment]
Any ideas? Something wrong with PL translation on transifex?

**Comment by kaloudis** [comment]
Fixed the issue here https://github.com/ZeusLN/zeus/pull/673

There is support already for the Polish Zloty though

**Comment by kaloudis** [comment]
Fixed in v0.6.0-beta1

**Comment by pysiak** [comment]
Thanks, I confirm it works!
