### ISSUE TITLE
Overwrite Lightning invoice with custom amount does not work (?)

### ISSUE THREAD

**Issue by rene78** [ZeusLN/zeus#646]
**Describe the bug**
If one tries to overwrite the invoice amount with a custom value the transaction is sent with the original invoice amount.

**To Reproduce**
1. Click on "Support the project" on the [mempool sponsorship page](https://mempool.space/de/sponsor) and click on "Get invoice"
2. Change QR Code to "Lightning"
3. Scan QR Code with Zeus
4. Change value to 10k sats and send
5. Transferred amount was still the invoice amount (100k sats)

**Expected behavior**
Send the entered amount (10k sats)

**Smartphone:**
 - Device: Xiaomi Redmi Note 5
 - OS: Android 8
 - Zeus Version v0.5.2
 - Tor via Raspiblitz

**Comment by kaloudis** [comment]
Can you provide info on what kind of node you are using?

**Comment by kaloudis** [comment]
I believe the spec has changed. You used to be able to overpay up to 15% but not overpay. We're going to remove this functionality from the app.

**Comment by rene78** [comment]
I connect Zeus to a Raspiblitz, but I guess this is not relevant anymore.
Thanks for the info. I am going to close the issue.
