### ISSUE TITLE
NFC appearing when connecting new node iOS

### ISSUE THREAD

**Issue by Bosch-0** [ZeusLN/zeus#647]
A NFC popup appears when attempting to connect a new node to Zeus when it shouldn't. 

Tested on iOS 15.1 iPone 11 Pro Max.

![IMG_4618](https://user-images.githubusercontent.com/55287964/145041186-3e1429ce-7048-4d5e-9b4f-4f4dded2be8d.PNG)

**Comment by kaloudis** [comment]
Fixed in v0.6.0-beta1
