### ISSUE TITLE
Issue with LNbits LndHub support

### ISSUE THREAD

**Issue by Chris869218** [ZeusLN/zeus#651]
**Describe the bug**
When scanning either the 'lndhub invoice' QR code or the 'lndhub admin' QR code in LNbits, which claims to currently be "supported by Zeus and BlueWallet" an "Error fetching lndconnect config" is thrown. 

Have tried using LNbits over Tor (checking the 'use Tor' box) as well as a clearnet LNbits hosted version (without 'use Tor' checked) and get the same error for both.

**To Reproduce**
1. Go to https://legend.lnbits.com
2. Give the wallet a name and hit 'add new wallet'
3. Under extensions (left hand side) enable the "LndHub" extension
4. In Zeus , add a new node, select "SCAN LNDCONNECT CONFIG" and scan the QR code provided in the LNbits LndHub extension
4. Get "Error fetching lndconnect config"

**Expected behavior**
Zeus successfully connects to the LNbits wallet in order to query payments and balances, generate invoices and make payments.

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020
 - OS: 15.0.2
 - Zeus Version v0.6.0-alpha4
 - Clearnet or Tor (tired both)

**Comment by kaloudis** [comment]
You need to specify `LNDHub` under implementation and then press `Scan LNDHub config`

**Comment by Bosch-0** [comment]
Did you manage to connect using Evans recommendation @Chris869218 ?

**Comment by Chris869218** [comment]
Thanks for the reminder, I hadn't gotten a chance to try it yet. Yes, that did work. Thanks for clearing up my mistake!
