### ISSUE TITLE
pod install fails on M1 Mac (I have a workaround)

### ISSUE THREAD

**Issue by futurepaul** [ZeusLN/zeus#680]
**Describe the bug**
Setting up a fresh clone of Zeus on my M1 Macbook and I get a crash during pod install, something related to ffi. There's an issue that seems to be about this problem in the ffi repo: https://github.com/ffi/ffi/issues/864

The recommended solution there worked for me:
```
gem install --user-install ffi -- --enable-libffi-alloc
```

But figured it would be good to make an issue for this to track until it's truly resolved.

**To Reproduce**
1. Clone zeus
2. cd ios && pod install

**Expected behavior**
pod install should work

**Screenshots**

<img width="1135" alt="Screen Shot 2022-01-18 at 10 38 46 AM" src="https://user-images.githubusercontent.com/543668/149979958-8d7e3a09-1cb5-44d2-849a-df899343eff6.png">

**Desktop (please complete the following information):**
 - OS: macos 12.1
 - Ruby Gems: 2.6.0 (default with OS)

**Comment by kaloudis** [comment]
Appreciate it. M1 offers some great performance updates but dev environments are going to have quirks like this for the next few years.

**Comment by kaloudis** [comment]
Check out https://reactnative.dev/blog/2021/10/01/version-066#better-support-for-apple-silicon-xcode-13-and-ios-15

**Comment by kaloudis** [comment]
this may also be helpful (precursor to solution above) https://github.com/react-native-community/releases/issues/238#issuecomment-890367992

**Comment by atothewest** [comment]
I ran into this issue on another project and I believe it is resolved when using newer versions of Ruby and `cocoapods`. I am using Ruby `3.1.1`.

After installing Ruby with your manager of choice...
```
$ ruby -v
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
$ gem install cocoapods
$ (cd ios && pod install)
```

MacOS 12.2 (M1)

FWIW, prior to that running `gem install --user-install ffi -- --enable-libffi-alloc` had not fixed the crash for me, so hopefully the above steps might help anyone else hitting the same issue.
