### ISSUE TITLE
Retire RNCamera in favor of Vision Camera

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#687]
https://github.com/mrousavy/react-native-vision-camera

**Comment by deregs** [comment]
I think we'll have to use [vision-camera-code-scanner](https://github.com/rodgomesc/vision-camera-code-scanner), which is based on react-native-vision-camera. Vision camera doesn't support scanning QR codes.

**Comment by myxmaster** [comment]
FYI: https://github.com/rodgomesc/vision-camera-code-scanner/issues/155#issuecomment-1695864607
