### ISSUE TITLE
 HTLC unit shows as sat instead of msat

### ISSUE THREAD

**Issue by refazi** [ZeusLN/zeus#705]
Looking at the channel peer info, minimum HTLC value, the unit shown is sats, but the value is in msats

**To Reproduce**
1. Go to channels view via the button at the button right 
2. Click on channel
3. Scroll to htlc values 
4. See value in wrong unit

**Expected behavior**
Value should be shown in sats, should be decided by 1000
**Screenshots**
![3620C450-1E05-46ED-B3F1-5D4A24C6A806](https://user-images.githubusercontent.com/30083994/150627375-932eb598-d506-4367-a40b-96d63fc3a5bf.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.2
 - Zeus Version 0.6.0 beta1
 - Tor

**Additional context**

**Comment by kaloudis** [comment]
The API response is confusing here. Min HTLC is `min_htlc` and Max HTLC is `max_htlc_msat` so I thought `min_htlc` was in sats

**Comment by refazi** [comment]
Absolutely confusing, but I guess min htlc is more granular for dust

**Comment by kaloudis** [comment]
This is fixed in the latest releases

**Comment by refazi** [comment]
Thank you!
