### ISSUE TITLE
[Feature request] Select active account before starting to connect

### ISSUE THREAD

**Issue by Darth-Coin** [ZeusLN/zeus#725]
**Description**
Managing multiple accounts/nodes/wallets sometimes is buggy, in special when are different types of connections, to - non-tor etc.
A simple selection of desired account to use will avoid many connectivity issues at startup.

**Expected behavior**
To have like a prompt, when the app is open, after introducing the PIN (if is set), to select a specific account already configured in settings.
So, in this way, is not taking the last open account. Maybe you want to open an account that it doesn't have Tor activated. That will speed up a lot the opening of the wallet, not being necessary to open the last account, got to settings, choose another wallet etc

**Comment by Bosch-0** [comment]
This is in the latest beta release
