### ISSUE TITLE
Feature Request: Hide balance

### ISSUE THREAD

**Issue by michaelWuensch** [ZeusLN/zeus#744]
If I want to pay using the new Zeus Beta, everyone can have a glimpse on my whole nodes balance. 
There should be an option in the security settings where hiding at least the balances on the start screen can be enabled.

**Comment by kaloudis** [comment]
Try Settings > Privacy > Lurker mode

We'll also be adding a new default screen on the wallet that doesn't show the balance. But that will probably be in v0.7

**Comment by michaelWuensch** [comment]
Ah, thats what Lurker mode is. Nice!
I don't even think an extra starting screen without balance is even necessary then.
The only downside of lurker mode is that if you have multiple nodes, you can't destingusih between them.
I think just keeping the node images constant would be enough without leaking any information.

**Comment by kaloudis** [comment]
Good call. Made a change here:

https://github.com/ZeusLN/zeus/pull/747

**Comment by michaelWuensch** [comment]
Awesome, thanks!
