### ISSUE TITLE
Keysend using AMP Fails in v0.6.0-beta2

### ISSUE THREAD

**Issue by deregs** [ZeusLN/zeus#746]
**Describe the bug**
**To Reproduce**
1. Click on send lightning payment
2. Scan keysend address
3. Fill in amount
4. Press send
5. Payment fails, shows ERROR: failure_reason_incorrect_payment_details

**Expected behavior**
Payment should succeed. Tested keysend using current v0.5.2, and payment succeeds. However, 0.5.2 is using keysend, not AMP.

Also, in version 0.6.0-beta2 I tested the keysend pathway (supportsAMP set to false) and the keysend payment succeeded, so this is definitely an issue with the AMP pathway.

Issue happens when amp is set to true here: https://github.com/ZeusLN/zeus/blob/e49f1f947b0f98bf26d3250d6c501a66ae2b9710/stores/TransactionsStore.ts#L184

**Smartphone:**
 - Device: Tested on iPhone 8 as well as iPhone 11 Pro simulator
 - OS: iOS 13.7
 - Zeus Version v0.6.0-beta2
 - Tor

**Additional context**
Keysend through AMP does appear to work when I test on regtest lightning nodes (lnd 0.14.1-beta), but fails for my Mainnet node (also lnd 0.14.1-beta). 

However, when testing through regtest I had a channel open directly to the node I was sending a keysend payment to, and on Mainnet I did not. 

lnd logs for failed payment:
```
Attempt 14 for payment 6d219c0daf77c7b1a774313118885cdad3c553f64078f298a1472c272d6ccdd9 failed: IncorrectOrUnknownPaymentDetails(amt=1000 mSAT, height=720958)@4
Payment 6d219c0daf77c7b1a774313118885cdad3c553f64078f298a1472c272d6ccdd9 failed: final_outcome=incorrect_payment_details, raw_err=IncorrectOrUnknownPaymentDetails(amt=1000 mSAT, height=720958)@4
Payment 6d219c0daf77c7b1a774313118885cdad3c553f64078f298a1472c272d6ccdd9 failed: incorrect_payment_details
```

**Comment by deregs** [comment]
[/v2/router/send](https://api.lightning.community/#v2-router-send) docs says "If no payment request is specified, the following fields are required: dest, amt and payment_hash."

It looks like payment_hash wasn't being specified for AMP keysend payments. Although I tried adding payment_hash for AMP payments and it's still giving the same error.

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/748

**Comment by deregs** [comment]
This was only happening because I was trying to send to a c-lightning node, which doesn't support amp yet.
