### ISSUE TITLE
Check if the node on the receiving end of the keysend supports AMP

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#750]
If so check should be put in place before allowing user to attempt payment

**Comment by Bosch-0** [comment]
I know you were investigating this @deregs, any updates?

**Comment by deregs** [comment]
> I know you were investigating this @deregs, any updates?

It isn't possible to check if the receiving node supports AMP. So while AMP is a more experimental feature, [this toggle](https://github.com/ZeusLN/zeus/pull/840) should fix it. Now at least LND users have the option to send a non-AMP keysend if AMP is failing.

**Comment by Bosch-0** [comment]
Awesome, yeah toggle makes sense while it gets more widely adopted. Closing this issue then. 

I'll also include something in the docs about searching the 'Research' issue tag for things like this that may likely come up again by others in the future.
