### ISSUE TITLE
Zeus force-closes after tapping on "About"

### ISSUE THREAD

**Issue by rene78** [ZeusLN/zeus#783]
**Describe the bug**
Zeus force-closes after tapping on "About"

**To Reproduce**
1. Click on the gearwheel
2. Click on 'About Zeus'
3. App closes

**Expected behavior**
App shows me version information, etc.

**Smartphone:**
 - Device: Xiaomi Redmi Note 5
 - OS: MIUI Global 11.0.3
 - Zeus Version 0.5.2
 - Tor

**Comment by kaloudis** [comment]
Known issue. You're in for a real treat thought when `v0.6.0` releases in the next week or so.

**Comment by rene78** [comment]
Looking forward to it!
