### ISSUE TITLE
"Scan LNDCONNECT Config" suggested when attempting to connect c-lightning-REST

### ISSUE THREAD

**Issue by kn0wmad** [ZeusLN/zeus#789]
**Describe the bug**
"Scan LNDCONNECT Config" suggested when attempting to connect c-lightning-REST

**To Reproduce**
1. Go to 'Add a new node'
2. Click on 'c-lightning-REST'
3. See error

**Expected behavior**
Ideally, offer to scan for host and macaroon separately

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel
 - OS: Graphene
 - Zeus Version 0.6.0-rc2
 - Tor

**Comment by kaloudis** [comment]
Good suggestion. We're actually thinking of proposing a new protocol that takes into consideration all the different implementations

**Comment by kn0wmad** [comment]
That sounds ideal - I was also going to feature request the ability to scan a QR for the Spark interface.  Thanks for your work

**Comment by kaloudis** [comment]
I believe this has been fixed in v0.7.0. There's now a c-lightning-REST QR scanner too

**Comment by kn0wmad** [comment]
I was able to briefly connect before being plagued by ECONNREFUSED, host unreachable, and Tor daemon error messages.  It seems the issue at hand is definitely addressed though - closing.  Thank you!
