### ISSUE TITLE
LND: ability to use full UTXO during channel open or on-chain payment

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#790]
https://api.lightning.community/#estimatefee

We can use this to calculate fees for coin control so users can use their full UTXO

**Comment by kaloudis** [comment]
This doesn't have everything we need. Need some changes upstream in LND. Tracking here: https://github.com/lightningnetwork/lnd/issues/6949

**Comment by hieblmi** [comment]
> This doesn't have everything we need. Need some changes upstream in LND. Tracking here: [lightningnetwork/lnd#6949](https://github.com/lightningnetwork/lnd/issues/6949)

The OpenChannel PR in LND is tracked here https://github.com/lightningnetwork/lnd/issues/6955

**Comment by kaloudis** [comment]
@hieblmi excellent progress. looking forward to this

**Comment by hieblmi** [comment]
Same, but https://github.com/lightningnetwork/lnd/pull/6903 needs to get in first :D

**Comment by hieblmi** [comment]
@kaloudis both PRs here were merged -> more power to Zeus

**Comment by kaloudis** [comment]
@hieblmi amazing. great work!

**Comment by expatri0tic** [comment]
@kaloudis 
Will this solve the issue in Zeus of being able to:
1. Hit send
2. Input bitcoin on-chain address
3. Select desired UTXO(s)
4. Select desired miner fee (sat/vB)
5. Hit fundmax flag
6. Send entire UTXO to address minus fees

**Comment by hieblmi** [comment]
Hi @expatri0tic, the features added so far only allow utxo control for channel openings. You are referring to sending on-chain transactions through Zeus. There is active work on an `lnd` PR to add manual coin selection. This could then be integrated into Zeus. See PR https://github.com/lightningnetwork/lnd/pull/8516

**Comment by kaloudis** [comment]
https://github.com/lightningnetwork/lnd/pull/8955
