### ISSUE TITLE
QA for wallet scan

### ISSUE THREAD

**Issue by Bosch-0** [ZeusLN/zeus#791]
Going forward I will regularly be conducting quality assurance (QA) on the wallet redesign frames. Below is the format I will be using, let me know if this suits the devs / anything I can do to make things easier for you guys. 

The left frame is what it currently looks like in Zues, middle is the redesign and on the right is all the specs to follow. 

This QA is a small one just covering the wallet scan frame. This frame is reached by clicking the scan icon in the top right of the home and channels page. 

Figma source file for this QA can be found [here](https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/Zeus?node-id=4512%3A47120). Let me know if you need any help exporting anything from Figma. 

![image](https://user-images.githubusercontent.com/55287964/153149413-2caba2da-4443-469d-9808-b4e5f980a365.png)

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/796

No image import yet. Margins of the scan frame need tweaks. Other than that good to go.

**Comment by Bosch-0** [comment]
Tested on iOS.

One thing is the button text should be lower cased and yeah the margins - everything else looks great! Feels much slicker to scan :)

**Comment by kaloudis** [comment]
Need to revisit margins at some other point but added a noUppercase prop to the `Button` component https://github.com/ZeusLN/zeus/pull/816

**Comment by Bosch-0** [comment]
Awesome! All looks good to me then :)
