### ISSUE TITLE
Flip the use tor switch on automatically when scanning tor url

### ISSUE THREAD

**Issue by deregs** [ZeusLN/zeus#819]
Think it might be better ux to switch the Use Tor switch on when scanning an LND Connect config or BTCPAY config with a tor url.

Would also reduce the number of steps listed on compatible nodes. For ex, remove step 4 in the Umbrel connection instructions:

1. Open the Zeus app on your phone.
2. Tap "Scan lndconnect config".
3. Scan this QR Code (click to enlarge)
4. Check "Use Tor".
5. Tap "Save Node Config".
6. Tap "I understand, save my node config".

@kaloudis @Bosch-0 let me know if this would be worth implementing, or if you prefer current functionality.

**Comment by Bosch-0** [comment]
Yep I think this would be better UX for sure, unless there is some technical reason it is not auto-selected I am not aware of I think this would be a great addition.

**Comment by kaloudis** [comment]
I thought we had this at some point, must have had some code regression. Definitely want that functionality.

**Comment by kaloudis** [comment]
This should sort it: https://github.com/ZeusLN/zeus/pull/829/files

**Comment by kaloudis** [comment]
Fixed in v0.6.0. Out now.
