### ISSUE TITLE
Look into hosted channels for node operators

### ISSUE THREAD

**Issue by Bosch-0** [ZeusLN/zeus#820]
From https://sbw.app/posts/scaling-ln-with-hosted-channels/

> Hosted channels (HC) is an extention to LN protocol which allows two LN nodes to establish a new type of channel between them which is intentionally not backed on chain.
> 
> One side of such channel is called a Host because it’s a side where the actual money is stored, the other side is called a Client and it’s the one which trusts Host (amount of trust can be measured as HC capacity).
> 
> HCs are not enforceable on chain but still preserve Client privacy and Host’s balance obligations are cryptographically provable at all times so the only type of scam a Host can viably perform is an exit scam.
> 
> Established HC can be announced to Lightning network: doing so increases overall network liquidity and makes it more capital-efficient since other LN nodes can now use public HCs for routing without added trust assumptions on their side.

As many Zeus users operate multiple nodes, having it possible for them to open hosted channels between themselves (and other trusted nodes) would be a cool feature and helps with scaling the network.

**Comment by kaloudis** [comment]
This is not the way to go imho, especially as the world becomes more volatile

https://twitter.com/SimpleBtcWallet/status/1496829453775044612

**Comment by Bosch-0** [comment]
I was thinking of it more to have it as an advanced feature for routing node operators who have more than one node so they can open hosted channels between their own nodes. So we wouldn't be hosting the channels or anything like that.

**Comment by kaloudis** [comment]
This has manifested itself in the ability to open up trusted channels to the embedded LND node in v0.8.0+

https://docs.zeusln.app/for-users/embedded-node/trusted-funding
