### ISSUE TITLE
Keyboard doesn't collapse on Node Fees page

### ISSUE THREAD

**Issue by deregs** [ZeusLN/zeus#824]
Issue found on iPhone 8 iOS 14.8.1 running Zeus 0.6.0-rc2.

On the routing > node fees page, the keyboard will not collapse to reveal the submit new fees button. Ideally, there would be a return key on the keyboard that would collapse the keyboard (like on the Node Configuration screen), or the keyboard should also collapse when tapping anywhere on the screen outside of the text input fields.

![image](https://user-images.githubusercontent.com/93104057/154097727-e1f64a12-395d-4e1c-bdfc-d49a0f088943.png)

**Comment by kaloudis** [comment]
Might be worth trying the `number-pad` `keyboardType` on the `TextInput`s 

See https://reactnative.dev/docs/textinput#keyboardtype

**Comment by deregs** [comment]
working on this one

**Comment by kaloudis** [comment]
Fixed in v0.6.0 https://github.com/ZeusLN/zeus/pull/834
