### ISSUE TITLE
Redesign accounts page (V1)

### ISSUE THREAD

**Issue by Bosch-0** [ZeusLN/zeus#835]
This QA is for the current home / accounts page that is shown first when a user opens the app. This is V1 as there will be quite a few changes once we introduce the number pad home page - will do a QA once that is ready and call it V2. 

![image](https://user-images.githubusercontent.com/55287964/154211324-f8717096-fdad-4d96-aa1e-b53d14427929.png)

[Figma source](https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/Zeus?node-id=4566%3A21812)

**Comment by Bosch-0** [comment]
Would be cool to get this squeezed into 0.6.1 @kaloudis @deregs 😆

**Comment by deregs** [comment]
@Bosch-0 I'm unsure if I'll have time to pick this up this week. One thing I was wondering, are we changing the background color for every screen on the app with this change? I saw it's being changed to a different navy color, and I think background color remains the same on all screens.

**Comment by Bosch-0** [comment]
The primary background color for pretty much every page should be #1F242D

**Comment by Bosch-0** [comment]
Partially done in https://github.com/ZeusLN/zeus/pull/904
