### ISSUE TITLE
Node fees not updating on Your Node Fees page

### ISSUE THREAD

**Issue by deregs** [ZeusLN/zeus#838]
**To Reproduce**
1. On home page click on lightning > routing > button in top right corner
2. On Your node fees page, change the base fee
3. Click submit, should see successfully set fees message
4. Back out of Set node fees page and click on the button in top right corner to go back into the Set node fees page
5. Base fee is set back to what it was before submitting new fees

**Expected behavior**
I think the value should update, but let me know if this is actually the intended functionality.

Found this issue with an lnd 0.14 node on iPhone 11 emulator running iOS 13.7

**Comment by deregs** [comment]
Did some more testing, and this isn't much of an issue.

When pressing submit on your node fees page, the base fee (or whatever other fields you input) are applied across all open channels successfully. 

However, you can only get base fees, fee rate, etc. on a per channel basis. For example, lnd [`/v1/fees/`](https://api.lightning.community/#v1-fees) route returns all of the info per channel, and we would have to check if the base fee/fee rate etc. was consistent across every single channel and display that. So we couldn't display an accurate value unless all channels have the exact same configuration values - is this typical behavior for lightning node operators? I'm not sure.

Perhaps we could eliminate the preset values like not displaying 1 for Base Fee, 0.001 for fee rate etc. in order to not confuse the user, but overall I don't think this issue is a big deal.

**Comment by kaloudis** [comment]
Let's remove the the preset values but leave the placeholders

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/issues/838
