### ISSUE TITLE
error cannot read property "result" of undefined

### ISSUE THREAD

**Issue by zynos** [ZeusLN/zeus#839]
**Describe the bug**
I am sending a payment of 1 satoshi via this QR Code:
https://tippin.me/@Stadicus3000
 And I get the red full screen error message
` error cannot read property "result" of undefined`

But when i check the channel balances, i see, that the 1 satoshi reached remote!

So the transcation worked but i still received the error message.

**To Reproduce**
I am connected via a direct channel to this node.
I am running my private raspibolt node and connected ZEUSLN via LNDConnect
see -> https://raspibolt.org/bonus/lightning/zeus-over-tor.html

**Smartphone (please complete the following information):**
 - Device: Iphone 12 Pro
 - OS: iOS 15.2.1
 - Zeus Version v0.6.0-rc2
 - lnd over Tor

**Additional context**
Zeus in testflight

**Comment by kaloudis** [comment]
Fixed with https://github.com/ZeusLN/zeus/pull/826

We'll roll out RC3 on TestFlight this week with the fix.

**Comment by zynos** [comment]
Ah cool, I wil try again with the new version and report back, thank you guys!

**Comment by kaloudis** [comment]
Fixed in v0.6.0. Out now.
