### ISSUE TITLE
Add `maxfeepercent` for C-Lightning `pay` command to permit higher payment success rate

### ISSUE THREAD

**Issue by willcl-ark** [ZeusLN/zeus#846]
I have been having some difficulty paying to Muun wallet from my C-Lightning node, as they appear to have some very high-fee channels on the recipient side at the moment...

![signal-2022-02-16-185919_001](https://user-images.githubusercontent.com/6606587/154459898-e8192de4-fcc2-459c-bbae-0b557330f30a.png)

This is solvable when interacting directly with my node, by increasing the allowed `maxfeepercent` parameter on the `pay` command, e.g. instead of:

`lightning-cli pay bolt11`

...which will fail with "fee exceeds our fee budget", I can use:

`lightning-cli pay -k bolt11=invoice maxfeepercent=0.6`

...which increases the fee budget and can therefore find more routes to try.

I think it would be generally useful if we could somehow integrate a `maxfeepercent` toggle into the UI? Perhaps it could appear only after first payment failure, if it's deemed "too advanced" (or to be even more precise, could appear if the returned `failreason` contains `Fee exceeds our fee budget`, or else could be in an "advanced" tab when scanning the invoice?

**Comment by deregs** [comment]
#860

**Comment by Bosch-0** [comment]
Sounds good to me! Looks like it can be apart of 0.6.0 thanks to Deregs <3

**Comment by kaloudis** [comment]
This has been added to v0.6.0. Can you test it out @willcl-ark?

**Comment by willcl-ark** [comment]
Thanks guys. I have tested this on 0.6 today but unfortunately fee situation has improved on Muun wallet node, so I wasn't able to invoke the new behaviour even with a 5 sat payment :(

After the conference I plan to create a dummy node which will have a very high fee channel so that I can force the new mode.

**Comment by willcl-ark** [comment]
I think I can close this for you now, right? let me know if you want it re-opened for some reason.
