### ISSUE TITLE
App crashes when clicking send or receive (Lightning or On-Chain) [calyxos][0.6.0-beta1][tor]

### ISSUE THREAD

**Issue by bobrubin** [ZeusLN/zeus#848]
**Issue**
When clicking on send or receive buttons for either lightning or on-chain, the app crashes.

**Env Info**
OS: CalyxOS
Zeus Version: 0.6.0-beta1
Node: Umbrel 0.4.14
Connection type: TOR

**Comment by kaloudis** [comment]
This has been fixed. Please upgrade to rc2 or wait for general release next week.

**Comment by bobrubin** [comment]
Thanks - upgraded to rc2 and send / receive no longer crashes.
