### ISSUE TITLE
Add PIN/Duress PIN and Duress Password

### ISSUE THREAD

**Issue by deregs** [ZeusLN/zeus#857]
Duress modes only enabled if main password/PIN is set. User can enter duress pin to delete all their node configs. Can be added for v0.6.1.

**Comment by deregs** [comment]
Working on this, couldn't find an existing open issue for it.

**Comment by deregs** [comment]
@kaloudis @Bosch-0 I saw this screen in figma:
![Screen Shot 2022-02-19 at 2 32 48 PM](https://user-images.githubusercontent.com/93104057/154816496-0bb4a2b6-e7c4-433d-8e0e-79632925bbd7.png)

Along with implementing duress pin/password, do we want to change this screen to set a pin instead of password?

<img width="372" alt="Screen Shot 2022-02-19 at 2 44 06 PM" src="https://user-images.githubusercontent.com/93104057/154816625-ed7829e5-248a-4331-a261-1c3f98de1e93.png">

If so, which is higher priority? Should we implement duress password then later convert everything to pin, or switch to pin before implementing duress pin?

**Comment by Bosch-0** [comment]
I think by default every user should have to set a PIN when they first register with Zeus - this is the easier option that most users will most likely use and is in general a good security practice. In the settings, users should have the option to disable this PIN and have an option to use passphrase over a the PIN. Depending on which lock screen method they have set they should be able to set a duress that is the same as the lock screen method they have set (keeps the UI clean that way).

**Comment by deregs** [comment]
Sounds good, will get everything working for passphrase / duress passphrase first, and then we can add pin / duress pin.
