### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [ZeusLN/zeus#872]
```
A problem occurred evaluating script.
> /builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/index.js:48  } catch {}          ^SyntaxError: Unexpected token {    at createScript (vm.js:80:10)    at Object.runInThisContext (vm.js:139:10)    at Module._compile (module.js:616:28)    at Object.Module._extensions..js (module.js:663:10)    at Module.load (module.js:565:32)    at tryModuleLoad (module.js:505:12)    at Function.Module._load (module.js:497:3)    at Module.require (module.js:596:17)    at require (internal/module.js:11:18)    at Object.<anonymous> (/builds/linsui/fdroiddata/build/app.zeusln.zeus/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:28:21)
```

Could you please take a look? Thanks!

**Comment by kaloudis** [comment]
We've moved over to our own self-hosted F-Droid repo for a few reasons: https://zeusln.app/download/

**Comment by tomichec** [comment]
Some of the reasons are mentioned in https://github.com/ZeusLN/zeus/issues/1807#issuecomment-1785302005

But I think the main one is that it's not fully free software (and open source) as it includes [proprietary Google libs][1] inside through react-native-vision-camera. Hence it would be rejected by the f-droid build, unless https://github.com/ZeusLN/zeus/issues/3232 is solved.

[1]: https://github.com/ZeusLN/zeus/issues/910#issuecomment-1259634078
[2]: https://github.com/mrousavy/react-native-vision-camera/blob/8e919c8ba574cf766463666b82d7ad2180855f1f/package/android/build.gradle#L204
