### ISSUE TITLE
tls.cert doesn't install automatically on iPhone, manual renaming to .crt is necessary

### ISSUE THREAD

**Issue by tukac** [ZeusLN/zeus#873]
Suggestions for making TLS certificate instructions more detailed in the app:

1. iPhone will not recognise .cert file, manual renaming to .crt is necessary.

2. Actual mailing is necessary, other transfer methods don't work on iPhone (saving mail draft, dropboxing etc)

3. Menu General > Settings > Profiles will appear only once .crt file is clicked. This menu doesn't exist on itself. Once profile is created this menu disappears again. Created profile is stored under General > VPN & Device Managemant.

4. Default LND tls.cert validity is 10080 hours (approx. 14 months), and it can be changed with following line in LND config:
tlscertduration=10080h

0.6.0 looks great, nice work!!! :)

edit: I've successfully installed tls.crt profile but I still get: Error: The certificate for this server is invalid. Connection is successful without certificate. What did I miss to do?

**Comment by kaloudis** [comment]
You probably need to set `tlsextraip` or `tlsextradomain` in your lnd.conf

**Comment by tukac** [comment]
I can't get certificate working even within local network. Without certificate Zeus connects fine locally.

I have added in LND config (myNode):
tlsextraip=127.0.0.1
tlsextraip=192.168.0.x (local IP of LND)

Afterwards I have regenerated and reinstalled on iPhone the new certificate afterwards. What should I do?

**Comment by deregs** [comment]
@tukac I can't recreate your issue. I'm on iPhone too, and I renamed the .cert to .crt and installed it, and I'm able to connect successfully with cert enabled within my local network.

One thing to check, when you added the `tlsextraip`s in your config, did you delete the old certificate files and restart your node to regenerate the new cert? Zap's documentation has more [detailed instructions](https://docs.zaphq.io/docs-desktop-lnd-configure#regenerate-tls-certificate) on this.

**Comment by tukac** [comment]
@deregs I use myNode and LND 0.14.1. I have regenerated and downloaded new certificate with myNode GUI.

I will try manually in terminal.

**Comment by deregs** [comment]
Hmm, I'm using LND 0.14.1, iOS 13.7, and Zeus 0.6.0 so I'm not sure what the issue could be. One more thing to check that your certificate is being correctly generated, ssh to your node and run `openssl x509 -text -noout -in ~/.lnd/tls.cert`. It should show all the `tlsextraip`s that you added.

**Comment by tukac** [comment]
Thanks for suggestion. I have run `openssl x509 -text -noout -in ~/.lnd/tls.cert` and it shows all `tlsextraip`s ok. Also iPhone profile shows correctly IPs.

I will upgrade myNode to latest to see if any improvement.

**Comment by bijeebuss** [comment]
I'm also having this issue. If it helps, the exact same configuration and certificate works on android but not in iOS.

**Comment by bijeebuss** [comment]
Ok I figured it out. In addition to adding the profile and installing it. You also have to go to a different t area in the setting and trust it 
![BFD73D7A-1EFE-45F0-A702-5B9DEB40D7D1](https://user-images.githubusercontent.com/11799228/170377236-18db014f-fe8a-4d92-999d-43234546ad92.png)

**Comment by tukac** [comment]
Yes, this was it!

Genetal > About > Certificate trust settings > enable your certificate

@kaloudis updating tls.crt installation for iOs probably would be good idea

1. iPhone will not recognise .cert file, manual renaming to .crt is necessary.

2. Actual mailing is necessary, other transfer methods don't work on iPhone (saving mail draft, dropboxing, etc)

3. Menu General > Settings > Profiles will appear only once .crt file is clicked. This menu doesn't exist on itself. Once profile is created this menu disappears again. Profile can also is stored and can be enabled under General > VPN & Device Managemant.

4. You must enable your certificate in Genetal > About > Certificate trust settings.

5. This is optional. Default LND tls.cert validity is 10080 hours (approx. 14 months), and it can be changed with following line in LND config: `tlscertduration=10080h`

**Comment by kaloudis** [comment]
Let's fix this for v0.7.1

**Comment by eliotcougar** [comment]
I just wanted to add that renaming .cert to .crt is needed on Android as well… Took me a moment to figure out when I configured the app for the first time…

**Comment by kaloudis** [comment]
I took a stab at updating them here: https://github.com/ZeusLN/zeus/pull/1220/files

**Comment by kaloudis** [comment]
Release in v0.7.1 - out now
