### ISSUE TITLE
Channels screen showing (0) in header after refresh

### ISSUE THREAD

**Issue by deregs** [ZeusLN/zeus#874]
EDIT:
Calling getChannels multiple times is not actually causing the issue, but it should be fixed. I will log a separate bug detailing the duplicated getChannels call in more detail.

The actual issue causing this bug has to do with how the headerString is being set in ChannelsPane

Original bug report:

Reproduce: go to channels screen > tap settings in top left > tap back to go back to channels screen

Channels screen will then refresh multiple times and then usually display (0) channels even with channels open (sometimes it randomly shows correct amount).

Cause of this issue:
getChannels method in ChannelsStore is being called multiple times in quick succession from different places. 

It's getting called in both:
https://github.com/ZeusLN/zeus/blob/982ac06e7917ee52fefedf70fdff51f763276d68/views/Wallet/Wallet.tsx#L187
https://github.com/ZeusLN/zeus/blob/982ac06e7917ee52fefedf70fdff51f763276d68/views/Channels/ChannelsPane.tsx#L97

**Comment by deregs** [comment]
Working on this

**Comment by Bosch-0** [comment]
Fixed in https://github.com/ZeusLN/zeus/pull/875 yeah?

**Comment by deregs** [comment]
> Fixed in #875 yeah?

yup
