### ISSUE TITLE
Display memo in payments you've made

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#878]
`payment_request` is returned so you can parse that to display the memo

**Comment by Tyler-McIntyre** [comment]
Is this issue still valid? If so, what view are we intending to display the memo in?

**Comment by kaloudis** [comment]
Yes, on the Payment view.

Apr 4, 2022, 17:09 by ***@***.***:

**Comment by kaloudis** [comment]
Added here: https://github.com/ZeusLN/zeus/pull/1146

Will be available in v0.7.0

**Comment by AndySchroder** [comment]
This is not working for keysend payments where we can input a memo.
