### ISSUE TITLE
Add support for generating BIP21 payment requests

### ISSUE THREAD

**Issue by Bosch-0** [ZeusLN/zeus#879]
@sbddesign recently started a [campaign](https://github.com/sbddesign/bip21-site) to get more wallets supporting BIP21 unified payment requests that have embedded Lightning invoice. 

Zeus should be able to generate BIP21 payment requests.

Once this issue is done we can deal with scanning unified QR codes.

**Comment by pseudozach** [comment]
I came here to open this issue, I think it's important to support it for onchain tx even without lightning fallback. of course much better to do it with lightning.
I'm happy to help out with implementation once design is settled.

**Comment by Bosch-0** [comment]
Will be working out all the sending / requesting flows for the 0.7.0 release - will ping you once they are ready to be implemented!

**Comment by kaloudis** [comment]
PR is just about ready https://github.com/ZeusLN/zeus/pull/1076

**Comment by kaloudis** [comment]
Shipping in v0.7.0 next week

**Comment by kaloudis** [comment]
Need to update the BIP-21 site: https://github.com/sbddesign/bip21-site/pull/87
