### ISSUE TITLE
QR for macaroon

### ISSUE THREAD

**Issue by P0u1us** [ZeusLN/zeus#88]
Hi, I was seeking the feature request, but only found bug reporting, thus sorry that this is put here!

I was attempting to install the android wallet and am stuck with entering the hex macaroon...
simply impossibly with the large field to enter that without mistakes!

I do notice that for both LNDconnect and BTCpayserver you provide the ability to QR scan the code!
Thus my Q is: why not enabling to scan the HEX macaroon?
there are simple tools (like: FreeQRcreator) or even with your example json that could convert the output of xxd into an QR stamp that could be imported flawlessly into the wallet?

**Comment by ZeusLN** [comment]
I'll consider this, but why not just use lndconnect?

**Comment by P0u1us** [comment]
that is fine as well, just any means where all needed parms can be scanned; i did not see any refs on lndconnect in your app or on the website though? as an typical end-user: i do wonder if trying to find (and having to install) lndconnect QR creation (which is proprietary on linux), might be an overcomplex thing for the average user again?

**Comment by Kixunil** [comment]
Not sure if useful to reply a year later, but anyway, you can [create the link using bash](https://github.com/LN-Zap/lndconnect/blob/master/lnd_connect_uri.md#create-and-show-a-qr-code-using-command-line). If you install qrencode from the repository, you can pipe the output into it directly.
