### ISSUE TITLE
Amount formatting bug

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#880]
![image](https://user-images.githubusercontent.com/1878621/156785918-8f92a017-5bb2-4595-8be1-9cafce78bc35.png)

From Kevin P on Slack

**Comment by deregs** [comment]
I don't think Zeus is formatting this amount. I think this is an issue with how lnmarkets is formatting the LNURL message.

https://github.com/ZeusLN/zeus/blob/8549aa8461e64d61ebabdbb3831296bfa1242527/views/LnurlPay/Success.tsx#L41-L52
