### ISSUE TITLE
Investigation: Android device compatibility for v0.6.0+

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#882]
We've got a min sdk version of 26 and target of 31. Let's see if we can bring it down for the next minor release to have Zeus compatible on as many devices as possible

**Comment by kaloudis** [comment]
Seems to be affecting Android 8 devices

**Comment by kaloudis** [comment]
Let's do some testing with the following config: https://github.com/ZeusLN/zeus/blob/v0.6.0-beta2/android/build.gradle#L8

```compileSdkVersion = 28
targetSdkVersion = 29```

Probably just bumped these up unnecessarily in the RN upgrade

**Comment by kaloudis** [comment]
We might be screwed here on the Google Play front https://stackoverflow.com/questions/41362619/google-play-store-does-not-downgrade-the-target-sdk-version-in-my-updated-applic

**Comment by kaloudis** [comment]
Might be ok, it may just apply to certain versions. Have to test in Google Play to be sure.

**Comment by rene78** [comment]
Hi @kaloudis, I am one of those users who cannot upgrade ("This app is no longer compatible with your device"). If you need some feedback once v0.6.1 is out you can message me.

**Comment by kaloudis** [comment]
This was the problem: https://github.com/ZeusLN/zeus/pull/1047

Now anyone running Android 9+ should be able to pull Zeus from Google Play regardless if they have NFC or not. Closing.
