### ISSUE TITLE
c-lightning-REST: bolt12 support

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#890]
https://github.com/Ride-The-Lightning/c-lightning-REST/blob/243494f4e75d9098e8b36c5fa4a9d5a545130654/controllers/offers.js

**Comment by kaloudis** [comment]
Could be a good reference: https://github.com/Ride-The-Lightning/RTL/pull/834

**Comment by Bosch-0** [comment]
There is a lot of extra user benefits that BOLT12 can offer, should we just start with simply being able to generate one and later expand on all the different functionalities like subscriptions, sending invoices etc.?

**Comment by kaloudis** [comment]
Out the gate we'll let users generate offers and subscriptions with all of the params you can use on c-lightning via CLI today as c-lightning-REST has exposed them. We'll also have support to pay them and return paid and generated invoices in Activity.

We just won't have the subscription management pane set up. At the very least we need to try to encourage the implementations to do the storage of subscriptions on their layer. It would be a poor experience having one set of subscriptions in RtL, for example, and another in Zeus.

**Comment by Bosch-0** [comment]
Moved below content from issue https://github.com/ZeusLN/zeus/issues/526 which was a duplicate of this.

https://github.com/Ride-The-Lightning/c-lightning-REST/pull/67/files

> @kaloudis 
> The biggest issue is that c-lightning doesn't currently store your subscriptions, it has to be handled at the app layer. This could be annoying if you are using multiple interfaces to manage your node, eg. Zeus + RtL

> @tukac
> I can't connect to REST even after RTL is stopped and c-lightning restarted (using same REST port as RTL). I tried http+onion, https+onion and https+clearnet (my c-lightning uses both) but no success. What is correct approach?
> 
> edit: useful feature would be QR code scanner as option to enter text in fields, text scanner is sweet though :)

**Comment by Sjors** [comment]
The easiest place to start might be to just scan and pay them.

Ideally it should also warn the user that `experimental-offers` is not enabled, if they scan a bolt12 invoice.

**Comment by AndySchroder** [comment]
Definitely interested in the blinded paths portion of BOLT12. Also, would like to use the refund/withdrawal offers to make a lightning version of the Bitcoin Fluid Dispenser (http://andyschroder.com/BitcoinFluidDispenser/2.3/) and a non-micropayments version of Distributed Charge (http://andyschroder.com/DistributedCharge/).

**Comment by newtonick** [comment]
Would be awesome to “just” pay a bolt12 offer as an intermediate step

**Comment by Sjors** [comment]
I guess this should be reopened as bolt12 support for CLNRest?

**Comment by kaloudis** [comment]
> I guess this should be reopened as bolt12 support for CLNRest?

CLNRest also supports BOLT 12 in v0.9.0

**Comment by Sjors** [comment]
Indeed I noticed the offer list.

**Comment by kaloudis** [comment]
Added in v0.8.5
