### ISSUE TITLE
crashes on ISK currency

### ISSUE THREAD

**Issue by woeisme** [ZeusLN/zeus#891]
**Describe the bug**
Zeus crashes when displaying balance in Icelandic Krona currency 

**To Reproduce**
1. Go to Settings -> Currency 
2. Click on 'Icelandic Krona'
3. Return to main app
4. Cycle through currency displays (btc, sats, fiat)
5. App crashes.

**Expected behavior**
Display wallet balance in selected fiat currency 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser N/a

**Smartphone (please complete the following information):**
 - Device: Samsung SM-G390F
 - OS: android 9
 - Zeus Version v0.6.0
 - Tor

**Additional context**
It would Be nice to enable multiple fiat currency selections

**Comment by kaloudis** [comment]
Do you experience crashes with other currency selections?

**Comment by kaloudis** [comment]
Looks like CoinGecko, our source for rates, may have removed ISK. Investigating...
