### ISSUE TITLE
Unable to connect node anymore (tor)

### ISSUE THREAD

**Issue by Deekee62** [ZeusLN/zeus#895]
**Describe the bug**
Unable to connect node anymore (tor)

**To Reproduce**
1. Open APP on iPhone
2. See error: bad URL

**Expected behavior**
Immediate connection establishment to node

**Screenshots**
![telegram-cloud-photo-size-4-5861496157417618083-y](https://user-images.githubusercontent.com/33904339/157819373-83b6c39c-4444-413c-a086-d9f67605dd97.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone7s
 - OS: iOS 15.3.1]
 - Zeus Version v0.6.0-rc3]
 - Tor

**Additional context**

**Comment by kaloudis** [comment]
You probably need to restart Tor on your node

**Comment by Deekee62** [comment]
Why, it seems Tor run fine on my node?

**Comment by Deekee62** [comment]
A peer of mine just did a restart, doesn't seem to help!

**Comment by Bosch-0** [comment]
Try using the non rc version, 0.6.0 is live on the app stores

**Comment by Deekee62** [comment]
It seems to work by now after I did a full restart of my node, restarting TOR and LND only didn't help.

Sorry for the troubles caused :-)
