### ISSUE TITLE
UTXO appears unconfirmed when it is not

### ISSUE THREAD

**Issue by benthecarman** [ZeusLN/zeus#934]
**Describe the bug**
I have a utxo with 400+ confirmations however zeus shows it as unconfirmed and a part of my pending balance. 

**Screenshots**

Can dm some if needed, would doxx my funds. 

**Smartphone (please complete the following information):**

IPhone 15.4 with Zeus 0.6.2

**Additional context**
The transaction contains an op return, maybe that is causing the issue

**Comment by kaloudis** [comment]
Still using Eclair?

**Comment by kaloudis** [comment]
Interesting. My bet is it's down the stack in lnd or btcd. Could you check out what balances lncli returns?

**Comment by benthecarman** [comment]
> Interesting. My bet is it's down the stack in lnd or btcd. Could you check out what balances lncli returns?

Looks it is, closing!
