### ISSUE TITLE
Add ability to view hardware stats within Zeus

### ISSUE THREAD

**Issue by Bosch-0** [ZeusLN/zeus#935]
**Describe the feature**

For node runner power-users it would be useful if they could monitor their hardware stats from within Zeus. For example, view storage, CPU temp, board you are using etc. 

**Designs / mockups**

None yet, just making an issue while it's on my mind.

**Additional context**

Ideally this could be a stepping stone towards making Zeus as powerful as say [thunderhub](https://www.thunderhub.io/). Rarely having to log directly into my node would be great. 

Maybe we could start with just viewing then move into actually modifying things from within Zeus.

**Comment by kaloudis** [comment]
Great idea, but nodes don't have APIs that expose this info, unfortunately.
