### ISSUE TITLE
Connect to CLN node using Tor 

### ISSUE THREAD

**Issue by pratapc65** [ZeusLN/zeus#939]
I am not able to connect to the CLN node via tor  from the Zeus wallet.
Node Interface: c-lightning-REST
Host: tor address
REST Port: 3002
Macaroon : macaroon in hex format.
Please let me know if I am missing any additional details.

**Comment by Bosch-0** [comment]
Thanks for filing this issue! Few more details may make this easier to address:

- Device and OS you are using
- Version of Zeus you are running

**Comment by pratapc65** [comment]
Device  : Iphone X
OS : 13,5,1
Zeus : v0.6.1-beta1
I am able to connect using local host but not behind Tor.

**Comment by Bosch-0** [comment]
0.6.2 is out now: https://github.com/ZeusLN/zeus/releases/tag/v0.6.2, could start with trying that

**Comment by pratapc65** [comment]
I have updated the app to 0.6.2 and get error "An SSL error has occurred and a secure connection to the server cannot be made".
when I try to connect to node via tor.

**Comment by pratapc65** [comment]
The issue was I did not use the tor address for the REST plugin . Once I generated the REST tor address and was able to connect the node via Tor.
