### ISSUE TITLE
Add new home page

### ISSUE THREAD

**Issue by Bosch-0** [ZeusLN/zeus#941]
Already have a PR open for this but opening an issue to make it easier to track on the Hermes project / post specs in. 

Current WIP Figma: https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/Zeus?node-id=5340%3A28205

**Comment by Bosch-0** [comment]
Home page designs finished @kaloudis @deregs 

Main Figma source file: https://bit.ly/374Bydn

Live prototype: https://bit.ly/3s63PaV

How to view prototype on your mobile / view specs for the design: https://bit.ly/3F1A1Bv

Moving from Design phase into Dev phase for Hermes release.

**Comment by kaloudis** [comment]
Added in v0.7.0
