### ISSUE TITLE
Add new loading animation icon

### ISSUE THREAD

**Issue by Bosch-0** [ZeusLN/zeus#952]
### Describe the feature

Created a new loading animation to replace the current electricity circle which detail isn't so clear, especially on low res screens. 

Yellow (for darker backgrounds): https://lottiefiles.com/share/842gjjkn
Navy (for lighter backgrounds): https://lottiefiles.com/share/ujopzbyv

**Comment by kaloudis** [comment]
Added in v0.7.3
