### ISSUE TITLE
Lightning invoice QR cut off

### ISSUE THREAD

**Issue by sebastianelsner** [ZeusLN/zeus#953]
Hi, 

I found that a lightning invoice QR is not working when scanned from another mobile phone with Wallet of Satoshi. I think it is due to the QR not being displayed completely. Please see picture below. Is this assumption correct  or am I missing something?

![Screenshot_20220419-214408.png](https://user-images.githubusercontent.com/902798/164084037-eabf175c-b5ce-487e-a920-fe23faa35cba.png)

**Comment by deregs** [comment]
Could you please include what model phone you're using?

**Comment by sebastianelsner** [comment]
It's a Motorola Moto G7 Plus. More details here: https://wiki.lineageos.org/devices/lake/

**Comment by kaloudis** [comment]
Fixed in v0.6.4. Please re-open if the issue persists.
