### ISSUE TITLE
lndconnect string from myNode doesn't work

### ISSUE THREAD

**Issue by kaloudis** [ZeusLN/zeus#955]
Users report that the QR doesn't work and copy-pasting the string crashes Zeus.

**Comment by cmdruid** [comment]
I have this same issue. I'm not sure if the error is internal or related to a malformed string. Is there an option to dump crash logs to storage?

**Comment by kaloudis** [comment]
@cmdruid are you still having this issue?

**Comment by cmdruid** [comment]
I haven't had it recently.

When I was having this issue, I narrowed it down to bad encoding of the macaroon.
