### ISSUE TITLE
No on chain balance on main screen

### ISSUE THREAD

**Issue by exitfiat** [ZeusLN/zeus#963]
### Describe the bug

A bug happened!

I have one utxo with >800 confs in my c-ln on chain wallet <1mio sats. On the Main screen in Zeus it shows 0 sats but when i open "on chain" the utxo shows up. I could also spend it without problems. Refreshing and restarting the app didnt help. Lightning balance works fine.
Also the incoming utxo (from channel close) hasnt shown up in the activities window.

### Reproduce

Reproduce the bug step by step.
Get channel collaborative closed by peer, 
wonder where your sats went, click on "On-chain", see the utxo is there.

### Zeus version

v0.6.2

### Network

Tor

### Device

Google Pixel 4

### Device operating system

Graphene OS Android 13

**Comment by kaloudis** [comment]
Patch coming out in v0.6.3 in the next few days.

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/commit/84dc844a550f4ff9dfac795ca87d4fa3b2c8aaac

**Comment by kaloudis** [comment]
Fixed in v0.6.4
