### ISSUE TITLE
Add updateSettings method

### ISSUE THREAD

**Issue by deregs** [ZeusLN/zeus#966]
### Describe the feature

Every `setSettings` call requires all current settings to be passed in, along with the settings that you're updating. Example:

https://github.com/ZeusLN/zeus/blob/6ae3721ca48ea15b6a5bdca03b3e86e27952f8b0/views/Lockscreen.tsx#L179-L191

Propose adding an `updateSettings` method that takes only the settings we're updating.

**Comment by kaloudis** [comment]
maybe this could help: https://github.com/jasonmerino/react-native-simple-store

**Comment by kaloudis** [comment]
Took a stab at this while migrating our persistent storage library here: https://github.com/ZeusLN/zeus/pull/1229
