### ISSUE TITLE
iOS Error while Loading

### ISSUE THREAD

**Issue by riegersan** [ZeusLN/zeus#971]
### Describe the bug

I currently get a the following Error:

Error: called ´Result::unwrap()´on an Err 
value: BootStrapError(„Unable to read daemon control info“)

### Reproduce

1. Starting the App
2. Error appears

App Restart and reinstall does not help.

### Zeus version

v0.6.2

### Network

Tor

### Device

iPhone 12 mini

### Device operating system

15.4.1

**Comment by Bosch-0** [comment]
Likely an issue with Tor, have you tried connecting over clearnet? We will have a secure, non-Tor way to connect in the future but for now Tor can be pretty buggy

**Comment by riegersan** [comment]
Yeah, could be possible.

Today it's working again!

**Comment by zynos** [comment]
For me it stopped working today with the same error as mentioned above.
Before, zeus was working fine for like 3 month straight
I have zeus version 0.6.4

**Comment by adamteale** [comment]
I've been having the same issue over the last few weeks as well. Using tor (connecting to an Umbrel node).
I've tried the latest app store release as well as the ones available in Testflight.
Anything else that I can try?
It had been working solidly for the previous months.
I'm on iOS 15.4.1

**Comment by karelbh** [comment]
I have iPhone 7 (iOS v. 15.4.1), Zeus v.0.6.4, Umbrel Node. Tor doen't work. Tailscale is the solution in this case.

**Comment by kaloudis** [comment]
We've improved the error message here in v0.7.0.

For a Tor alternative check out Lightning Node Connect, Tailscale/Zerotier, or a home VPN solution.
