### ISSUE TITLE
LNURLp parsing issue inconsistent working.

### ISSUE THREAD

**Issue by brianoflondon** [ZeusLN/zeus#979]
### Describe the bug

I'm entering LNURLp by photographing a QR code or by typing it in.

When I put in the following it works:

`podping@v4v.app`

if I enter 

`brianoflondon@v4v.app`

it fails with `Error fetching Lightning Address data`.

That should just be calling GET on this: `https://v4v.app/.well-known/lnurlp/brianoflondon`

If I put exactly the same into Breez it works.

If I use `lightning:podping@v4v.app` in a QR code generator as text it works, switch to `lightning:brianoflondon@v4v.app` it fails.

I wrote the API that serves the response from V4V.app and it can be seen here: `https://api.v4v.app/docs` 

Zeus never even calls this API when I try the `brianoflondon@v4v.app` address. I'm genuinely mystified by this.

It seems that any valid Hive account address works except for MINE! And I wrote this API! However my address does work in Wallet of Satoshi, Breez and others.

### Reproduce

Open Zeus.

Open camera point at:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/28054569/168631563-ce4695e8-dfb7-4167-bb23-3b3a2b757061.png">

Fails with unable to read brianoflondon@v4v.app

Point at:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/28054569/168631844-dd535646-0e88-4327-9190-c5aaf54bbf17.png">

Opens up to send 1000 sats to podping@v4v.app

### Zeus version

v0.6.4

### Network

Clearnet

### Device

iPhone X

### Device operating system

iOS 15.4.1

**Comment by kaloudis** [comment]
I'm unable to recreate. Loads every time I scan it.

Very peculiar.
