### ISSUE TITLE
Add Lottie files support

### ISSUE THREAD

**Issue by Bosch-0** [ZeusLN/zeus#982]
### Describe the feature

Currently we use GIFs to render our animations in Zeus. Before we start getting more animations intergrated into Zeus we should move towards using Lottie files over GIF files. There is a huge amount of benefits of using Lottie files over GIF files, some are listed below:

- Much smaller size (Our current loading GIF is 176KB and the Lottie version of this is 6.3KB). This makes loading and disk usage smaller so the animations renders much faster and caters better to older devices. 
- Animations are higher quality
- More transparent (less janky edges) 

Using LottieFiles also gives as access to easily using the hundreds of thousands of animations on the LotteFiles website. For generic animations this will save us a whole lot of time compared to custom making them. An example is this NFC animation we can integrate into the NFC broadcast button when clicked: https://lottiefiles.com/91927-nfc-red 

These points are elaborated further in this post: https://lottiefiles.com/blog/tips-and-tutorials/lottie-vs-gif 

Lottie files integrate very nicely with React Native, and there is a well maintained Lottie component for react native which we could use: https://www.npmjs.com/package/lottie-react-native

**Comment by kaloudis** [comment]
https://github.com/ZeusLN/zeus/pull/1314

Added in v0.7.3
